export const bookingCopy = {
  en: {
 detail:{
 narrow:"Narrow the list", rejectedTitle:"Rejected at {time} today - {reason}",
      rejectedBody:"Hoteliana has taken the request back to the agent. It cannot be reopened, by you or by them.",
      rejectedNote:"The {rooms} rooms stayed in your allotment, and stop sale was applied to Standard Room for 24 - 26 September as you asked - so the rooms are there but those nights are not selling until you reopen them.",
      rejectedOverline:"WHAT HAPPENED TO YOUR ROOMS",
      rejectedHeading:"Nothing left your allotment",
      rejectedLead:"Rejecting never takes rooms. The only change is the stop sale you ticked on the way out.",
      rejectedNight:"unchanged · now on stop sale",
      rejectedRateTitle:"The rate is untouched",
      rejectedRateBody:"Half Board on those nights still carries {now}. Stop sale keeps the rate and the rooms - it only stops new bookings.",
      expiredTitle:"This request expired at {time} today",
      expiredBody:"Three hours passed with no answer, so the system closed it by itself. You can no longer confirm or reject it.",
      expiredNote:"Your {rooms} rooms were never taken. They are still in the allotment for 24, 25 and 26 September, and the room is still on sale.",
      expiredOverline:"WHAT THIS COST",
      expiredHeading:"The rooms were free the whole time",
      expiredLead:"Nothing blocked this booking except the clock. That is the part worth fixing.",
      expiredNight:"were free the whole time",
      expiredRateTitle:"A {total} SAR booking was not answered in time",
      expiredRateBody:"Hoteliana placed the guest elsewhere. You had the rooms - answering before the deadline keeps bookings like this with you.",
      issueChip:"Issue open · {id} ›",
      rejectOverline:"{id} · {guest} · {rooms} ROOMS · {nights} NIGHTS",
      rejectTitle:"You cannot take this booking",
      rejectBody:"Hoteliana takes the request back to the agent and you cannot reopen it. The {rooms} rooms stay in your allotment and the room stays on sale.",
      rejectReasonLabel:"WHY CAN YOU NOT TAKE IT? · REQUIRED",
      rejectReasons:["No availability","Rate error","The hotel is not available","Room out of service","The hotel is overbooked","Operational issue","Outside our control","Other reason"],
      rejectReasonsNote:"Fixed list: No availability · Rate error · The hotel is not available · Room out of service · The hotel is overbooked · Operational issue · Outside our control · Other reason",
      rejectDisagree:"Your calendar disagrees with you",
      rejectDisagreeBody:"It says 12, 9 and 7 Standard Rooms are free on 24, 25 and 26 September. If that is not true, the next agent will hit the same wall - stop the sale on those nights too.",
      rejectStopSale:"Also stop sale on Standard Room for 24 - 26 September",
      rejectStopSaleNote:"Rates and rooms are kept - you can open it again any time.",
      rejectNoteLabel:"NOTE TO HOTELIANA · OPTIONAL",
      rejectNotePh:"Anything the agent should be told",
      rejectRecorded:"Your reason, your name and the time are recorded on the booking. This cannot be undone, and Hoteliana is told the moment you press it.",
      rejectKeep:"The rooms stay yours.",
      rowOpen:"Open the booking",
      rowAddNumber:"Add the confirmation number",
      rowCopy:"Copy reference",
      rowExport:"Export this booking",
      filterHotelTitle:"Pick one hotel or see them all.",
      filterStayTitle:"Filters on the nights the guest stays.",
      filterBookedTitle:"Filters on when the agent made the booking.",
      filterSortTitle:"Changes the order of the rows only.",
      bookingsCount:"{count} bookings",
      arrivingToday:"Arriving today",
      departingToday:"Departing today",
      thisMonth:"This month",
      anyTime:"Any time",
      today:"Today",
      last7:"Last 7 days",
      last30:"Last 30 days",
      pickRange:"Pick a date range",
      pickRangeNote:"choose your own dates",
      sortArriving:"Arriving soonest",
      sortDeadline:"Answer deadline first",
      sortDeadlineNote:"requests that expire soonest",
      sortRate:"Highest rate first",
      clear:"Clear",
      cancelCta:"Cancel",
      allFilters:"All filters",
      back:"Back to bookings",
      meta:"{id}  ·  {hotel}  ·  booked by a Hoteliana agent today at {time}",
      slaTitle:"Answer by {time} today - {left} minutes left",
      slaBody:"Hoteliana allows {hours} hours on this hotel and the request arrived at {arrived}. If nothing is answered by then it expires by itself, and after that you can no longer confirm or reject it.",
      slaChip:"{hours} hours",
      slaChipNote:"set by Hoteliana, not by you",
      heldNote:"{rooms} rooms are held on 24, 25 and 26 September while the request is open. Reject it or let it expire and they go straight back on sale - nothing is lost either way.",
      beforeOverline:"BEFORE YOU DECIDE",
      beforeTitle:"You have the rooms - and this booking is not on your current rate",
      beforeBody:"Two things worth seeing before you answer. Neither of them decides for you.",
      roomsLeft:"rooms left of {of}",
      needs:"this booking needs {rooms}",
      afterBooking:"after this booking",
      rateTitle:"This booking was sold at {sold} a night - you have since raised Half Board to {now}",
      rateBody:"The agent booked before your change was published, so {sold} is what you are owed on it. A price change is not a reason to reject a booking that was already sold.",
      calendarOverline:"WHAT CHANGED IN YOUR CALENDAR",
      calendarTitle:"Two rooms a night left the allotment",
      calendarBody2:"Every meal plan on Standard Room sees the same numbers - one allotment, shared by all of them.",
      keptTitle:"This booking stays at {sold} a night",
      keptGroupTitle:"This booking keeps the {group} price",
      keptBody:"You raised Half Board to {now} after it was sold. The booking keeps the rate and the policy it was sold at - that never changes.",
      detailsOverline:"BOOKING DETAILS",
      detailsTitle:"Everything needed to run the stay",
      statusRow:"Status",
      statusPending:"Pending confirmation",
      statusReference:"Confirmed · reference pending",
      statusConfirmed:"Confirmed",
      guestsOverline:"GUESTS",
      guestsTitle:"Sent by the agent",
      requestsOverline:"SPECIAL REQUESTS",
      requestsTitle:"Not part of the contract - do what you can",
      answerOverline:"YOUR ANSWER",
      answerTitle:"Can you take this booking?",
      answerBody:"Confirming takes {rooms} rooms out of the Standard Room allotment on 24, 25 and 26 September. Other meal plans on that room lose those {rooms} rooms too - one allotment, shared.",
      ifConfirm:"If you confirm",
      ifConfirmBody:"The booking becomes Confirmed, your confirmation number is stored against it and Hoteliana tells the agent. The {rooms} rooms leave your allotment straight away.",
      ifReject:"If you reject",
      ifRejectBody:"You pick a reason from a fixed list and can add a note. Hoteliana takes it back to the agent, and your room stays on sale unless you stop it yourself.",
      ifNothing:"If you do nothing",
      ifNothingBody:"At {time} the request becomes Expired on its own. After that you cannot confirm or reject it, and Hoteliana places the guest elsewhere.",
      recorded:"Whatever you choose is recorded with your name and the time.",
      rejectCta:"Reject the request",
      confirmCta:"Confirm this booking",
      confirmedTitle:"Confirmed at {time} today - Hoteliana has told the agent",
      confirmedBody:"You confirmed without the hotel number. The guest is confirmed either way; the number is paperwork Hoteliana still needs.",
      confirmedBodyRooms:"You confirmed without the hotel numbers. The guest is confirmed either way; the numbers are paperwork Hoteliana still needs.",
      addNumber:"Add the confirmation number",
      addNumbers:"Add the confirmation numbers",
      leftOverline:"ONE THING LEFT",
      leftTitle:"Hoteliana is waiting for your confirmation number",
      leftTitleRooms:"Hoteliana is waiting for the hotel numbers · {in} of {rooms}",
      leftBody:"Type the number the hotel gave you. You will get one reminder today at 18:00 until it is in.",
      leftBodyRooms:"Type the number the hotel gave each room. You get one reminder today at 18:00 until every room has one.",
      leftPoints:[["The guest is safe","Confirmed is confirmed. The rooms are held and the agent has been told."],["You get one reminder","Today at 18:00, and it sits in your tasks until the number is added."],["Hoteliana sees the same flag","Nobody has to chase you - they can see the number is pending."]],
      leftPointsRooms:[["The guest is safe","Confirmed is confirmed. The rooms are held and the agent has been told."],["You get one reminder","Today at 18:00, and it sits in your tasks until every room has its number."],["Hoteliana sees the same flag","Nobody has to chase you - they can see the number is pending."]],
      doneTitle:"Confirmed · {number} is on the file",
      doneTitleBoth:"Confirmed · both rooms have their number",
      doneTitleEvery:"Confirmed · every room has its number",
      partialChip:"{in} of {numbers} in",
      partialTitle:"Confirmed \u00b7 {in} of {rooms} have a number",
      partialBody:"Room {done} is on the file. Room {left} is still pending - the reminder runs for that room only.",
      addMissing:"Add the missing number",
      numbersOverline:"HOTEL CONFIRMATION NUMBERS \u00b7 ONE PER ROOM",
      numbersHeading:"{in} of {rooms} have a number",
      numbersHeadingBoth:"Both rooms have their number",
      numbersHeadingEvery:"Every room has its number",
      roomLine:"Room {n}",
      cancelledChipTitle:"Confirmed \u00b7 {rooms} cancelled",
      cancelledNote:"Room {n} was cancelled on {on}, so 1 room a night went back to the Standard Room allotment on 24, 25 and 26 September.",
      cancelledNumbersHeading:"{active} room active \u00b7 {void} number void",
      roomCancelledVoid:"Room cancelled \u00b7 number void",
      cancelledBandTitle:"Room {n} cancelled",
      cancelledBandBody:"The agent cancelled Room {n} ({who}) on {on} under the booking policy. Its number {number} is void - it no longer shows on the voucher or in Masar. 1 room a night went back to your allotment.",
      cancelledTag:"cancelled",
      rowRoomsCancelled:"{left} of {total} \u00b7 Room {n} cancelled",
      rowOccupancyCancelled:"2 adults \u00b7 Room {left} only",
      rowTotalCancelled:"{total} SAR \u00b7 {rate} \u00d7 {nights} nights \u00d7 {rooms} room",
      rowChargeLabel:"Cancellation charge",
      rowCharge:"100% (non-refundable) \u00b7 {total} SAR \u00b7 Room {n} \u00b7 {rate} \u00d7 {nights} nights",
      doneOverline:"NOTHING LEFT TO DO",
      doneCardTitle:"This booking is complete",
      doneCardBody:"The guest is confirmed, every room has its number and the rooms are out of your allotment.",
      doneAgentTitle:"The agent has it",
      doneAgentBody:"Room {n} removed from the voucher and Masar.",
      doneCalendarTitle:"Your calendar is updated",
      doneCalendarBody:"{left} room is out of the Standard Room allotment on all three nights; Room {n} went back.",
      doneWrongTitle:"If something goes wrong",
      doneWrongBody:"You cannot cancel a confirmed booking - report an issue and Hoteliana handles it.",
      editNumbers:"Edit the numbers",
      numberAdded:"Number added",
      numberPending:"Pending",
      notAddedYet:"not added yet",
      leftTitlePartial:"Room {left} still needs its number",
      leftBodyPartial:"Type Room {left}'s number when the hotel issues it. You get one reminder today at 18:00 until it is in.",
      leftSafeTitle:"The guest is safe",
      leftSafeBody:"Confirmed is confirmed. The rooms are held and the agent has been told.",
      leftReminderTitle:"You get one reminder",
      leftReminderBody:"Today at 18:00, for Room {left} only, until its number is added.",
      leftFlagTitle:"Hoteliana sees the same flag",
      leftFlagBody:"Nobody has to chase you - they can see the number is pending.",
      leftFoot:"You cannot cancel a confirmed booking yourself - use Report an issue.",
      doneBody:"Everything Hoteliana needs is in. Nothing on this booking is waiting on you any more.",
      doneHeading:"This booking is complete",
      doneLead:"The guest is confirmed, the number is stored and the rooms are out of your allotment.",
      donePoints:[["The agent has it","Hoteliana passed your confirmation number on."],["Your calendar is updated","2 rooms left the Standard Room allotment on all three nights."],["If something goes wrong","You cannot cancel a confirmed booking - report an issue and Hoteliana handles it."]],
      cannotCancel:"You cannot cancel a confirmed booking yourself - use Report an issue.",
      reportIssue:"Report an issue",
      addNumberCta:"Add the number",
      allotmentNote:"The {rooms} left the Standard Room allotment on {days}. Room Only and Bed & Breakfast on that room lost them too.",
    },
    overline:"BOOKINGS", title:"Bookings", needAnswerPill:"{count} need an answer", subtitle:"Everything agents have booked on your hotels, and the two things waiting on you.", export:"Export", arrivals:"Arrivals today · {count}", departures:"Departures today · {count}", changes:"Change requests", needYou:"{count} requests are waiting for your answer", needYouNote:"These are On Request bookings. Hoteliana gives you 3 hours on this hotel - after that the request expires by itself and you can no longer take it. Times are Saudi time (UTC+3).", cardRoom:"ROOM", cardStay:"STAY", cardSize:"SIZE", cardTotal:"YOUR TOTAL", cardSize2:"{nights} · {rooms}", respondBy:"Respond by {time} today  ·  {left} min left", arrived:"arrived {time}", openDecide:"Open and decide", onRequest:"On Request", all:"All", answer:"Needs an answer", confirmed:"Confirmed", cancelled:"Cancelled", rejected:"Rejected", expired:"Expired", cancelAsked:"Cancellation asked", amendAsked:"Amendment asked", searchLabel:"Search", search:"Search guest, reference or hotel", hotelLabel:"Hotel", allHotels:"All {count} hotels", stayLabel:"Stay dates", allStays:"Any", anyStayDate:"Any stay date", bookedLabel:"Booked", anyBooked:"Any", sortLabel:"Sort", newest:"Newest first", hotelMenuHint:"Pick one hotel or see them all.", stayMenuHint:"Filters on the nights the guest stays.", stayRangeHint:"Bookings with any night in these dates", bookedRangeHint:"Bookings made on these days", showRange:"Show {label}", bookedMenuHint:"Filters on when the agent made the booking.", sortMenuHint:"Changes the order of the rows only.", reference:"REFERENCE", guest:"GUEST", hotelOffer:"HOTEL & ROOM", stay:"STAY", rooms:"ROOMS", rate:"YOUR TOTAL · INCL. VAT", status:"STATUS", decide:"Decide", open:"Open", review:"Review", view:"View", referencePending:"Reference pending", showing:"Showing 1-{shown} of {total} bookings", perPage:"20 per page", waitingFooter:"Both of these hold rooms while they are open. Answer or let them expire - nothing else releases them.", listFooter:"An expired or rejected request cannot be reopened - Hoteliana takes it back to the agent. A confirmed booking cannot be cancelled by you either; use Report an issue and Hoteliana handles it.", showingWaiting:"Showing 1-{shown} of {total} requests waiting for you", back:"All bookings", booking:"BOOKING", booked:"BOOKED", responseDue:"RESPONSE DUE", decisionTitle:"The guest is waiting for your answer", decisionBody:"Check the rooms and rate below. Confirming holds the rooms and tells the agent straight away.", remaining:"23 min remaining", confirm:"Confirm booking", reject:"Cannot take it", summary:"Booking summary", guestStay:"Guest & stay", calendar:"What confirming does to your calendar", calendarBody:"The 2 rooms leave the Standard Room allotment, so Room Only and Bed & Breakfast lose them on those nights too.", night1:"Thu 24", night2:"Fri 25", night3:"Sat 26", left:"left", rateTitle:"Your agreed rate · incl. VAT", total:"Total for 2 rooms · 3 nights", hotelGets:"Hotel receives", supplied:"Sent by the agent", leadGuest:"Lead guest", occupancy:"Occupancy", occupancyValue:"4 adults · 2 rooms", checkIn:"Check-in", checkOut:"Check-out", special:"Special requests", specialBody:"High floor if available. Guests arrive after 22:00.", confirmTitle:"Confirm this booking", confirmIntro:"Standard Room · Half Board · Thu 24 - Sun 27 Sep. The booking becomes Confirmed and Hoteliana tells the agent straight away.", confirmationChoice:"SUPPLIER CONFIRMATION NUMBER · REQUIRED · YOU CAN ADD IT LATER", confirmationChoiceBody:"Hoteliana needs the number the hotel gives you. If the hotel has not issued it yet, confirm anyway - the guest is what matters, the paperwork can follow.", pendingNote:"The booking shows as Confirmed · reference pending. It appears in your tasks, you get one reminder today at 18:00, and Hoteliana sees the same flag so nobody has to chase you.", noteHint:"Only Hoteliana reads this - the agent does not see it", recordedNote:"Recorded with your name and the time.", haveIt:"I have it", haveItHint:"the booking is confirmed with the number stored against it", later:"Not issued yet - confirm now, add it later", laterHint:"the booking is still confirmed and the rooms are held", number:"Confirmation number", ownRef:"Your PMS reference, if you use one", note:"Note to Hoteliana · optional", confirmNow:"Confirm booking", confirmLater:"Confirm without the number", rejectionTitle:"You cannot take this booking", reason:"Why can you not take it? · required", noAvailability:"No availability", rateError:"Rate error", unavailable:"The hotel is not available", operational:"Operational issue", other:"Other reason", stopSale:"Also stop sale on Standard Room for 24 - 26 September", rejectRequest:"Reject the request", result:"RESULT", confirmedAt:"Confirmed at 12:14 today", toldAgent:"Hoteliana has told the agent and the rooms are held.", oneLeft:"ONE THING LEFT", waitingNumber:"Hoteliana is waiting for your confirmation number", reminder:"Add it when the hotel issues it. You get one reminder today at 18:00.", addNumber:"Add the confirmation number", saveNumber:"Save the number", numberTitle:"Add the hotel confirmation number", numberHelp:"The booking is already confirmed. This is the number Hoteliana needs for the file.", savedNumber:"Confirmed · {number} is on the file", everything:"Everything needed to run this stay is now on the booking.", nothing:"Nothing left to do", report:"Report an issue", issueLead:"You cannot cancel or change a confirmed booking yourself. Tell Hoteliana what is wrong and they handle it with the agent.", issueDoesTitle:"What reporting an issue does", issueDoesNote:"Nothing below is automatic - Hoteliana decides the outcome.", issueDoes:[["info","The booking moves to \"Fulfilment issue · under review\". The agent sees that state too."],["info","Hoteliana works the case with you the way you already do it - by phone if that is faster."],["info","The outcome is recorded as relocated, replaced, or cancelled by Hoteliana."],["no","It may affect your supplier performance and your settlement, depending on the outcome."],["yes","You can stop the sale at the same time so the same night is not sold again."]] as const, issueTitle:"Report an issue to Hoteliana", wrong:"WHAT IS WRONG · REQUIRED", describe:"DESCRIBE IT · REQUIRED", alternative:"CAN YOU OFFER ANYTHING INSTEAD? · OPTIONAL · PICK ONE", sameNights:"A different room on the same nights", sameRoom:"The same room on different nights", none:"Nothing - the hotel cannot take them at all", stopSaleIssue:"Also stop sale while Hoteliana checks this", stopSaleIssueNote:"So the same thing does not happen to the next agent.", issueStays:"The booking stays Confirmed until Hoteliana answers. Nothing you do here cancels it - only Hoteliana can, with the agent.", issueSla:"Hoteliana answers issues within 2 hours during working hours (Saudi time).", sameNightsHint:"Deluxe Room City View has 8 free on 24 - 26 Sep", sameRoomHint:"Standard Room has 16 free on 27 - 29 Sep", describePh:"What happened, and what you can offer instead if anything", wrongPh:"Overbooked · room unavailable · guest details wrong · rate or policy wrong · other", send:"Send to Hoteliana", issueSent:"Hoteliana has it", issueRef:"ISS-2026-0184 · SENT 12:41", issueBody:"The issue is with Hoteliana. The booking stays confirmed while the team checks it.", expiredTitle:"This request expired at 14:35 today", expiredBody:"Hoteliana took it back to the agent. You can no longer confirm or reject it.", prevent:"STOP IT HAPPENING AGAIN", untouched:"Your supply is untouched", alerts:"Check who gets the alerts", rejectedTitle:"This request was rejected", cancellationTitle:"The agent asked to cancel this booking", amendmentTitle:"The agent asked to change this booking", approve:"Approve request", decline:"Decline request", requestResolved:"The request has been reviewed and the agent has been told.", close:"Close", SAR:"SAR"
  },
  ar: {
 detail:{
 narrow:"تضييق القائمة", rejectedTitle:"رُفض في {time} اليوم - {reason}",
      rejectedBody:"أعادت هوتيليانا الطلب إلى الوكيل. ولا يمكن إعادة فتحه، لا منك ولا منهم.",
      rejectedNote:"بقيت {rooms} الغرف في حصتك، وطُبّق إيقاف البيع على الغرفة الستاندرد في ٢٤ - ٢٦ سبتمبر كما طلبت - فالغرف موجودة لكن تلك الليالي لا تبيع حتى تعيد فتحها.",
      rejectedOverline:"ماذا حدث لغرفك",
      rejectedHeading:"لم يخرج شيء من حصتك",
      rejectedLead:"الرفض لا يأخذ غرفًا أبدًا. التغيير الوحيد هو إيقاف البيع الذي حددته أثناء الخروج.",
      rejectedNight:"دون تغيير · الآن بإيقاف بيع",
      rejectedRateTitle:"السعر لم يُمس",
      rejectedRateBody:"ما زالت نصف الإقامة في تلك الليالي بـ{now}. إيقاف البيع يحفظ السعر والغرف - وإنما يوقف الحجوزات الجديدة.",
      expiredTitle:"انتهى هذا الطلب في {time} اليوم",
      expiredBody:"مرّت ثلاث ساعات بلا رد، فأغلقه النظام من تلقاء نفسه. ولم يعد بإمكانك تأكيده أو رفضه.",
      expiredNote:"لم تُؤخذ {rooms} غرفك إطلاقًا. ما زالت في الحصة لأيام ٢٤ و٢٥ و٢٦ سبتمبر، والغرفة ما زالت معروضة للبيع.",
      expiredOverline:"ما الذي كلّفه هذا",
      expiredHeading:"كانت الغرف متاحة طوال الوقت",
      expiredLead:"لم يمنع هذا الحجز شيء سوى الوقت. وهذا هو الجزء الذي يستحق الإصلاح.",
      expiredNight:"كانت متاحة طوال الوقت",
      expiredRateTitle:"حجز بقيمة {total} ر.س لم يُجب عليه في الوقت",
      expiredRateBody:"وضعت هوتيليانا الضيف في مكان آخر. كانت الغرف لديك - والرد قبل الموعد يبقي حجوزات كهذه معك.",
      issueChip:"مشكلة مفتوحة · {id} ›",
      rejectOverline:"{id} · {guest} · {rooms} غرف · {nights} ليالٍ",
      rejectTitle:"لا يمكنك قبول هذا الحجز",
      rejectBody:"تعيد هوتيليانا الطلب إلى الوكيل ولا يمكنك إعادة فتحه. تبقى {rooms} الغرف في حصتك وتبقى الغرفة معروضة للبيع.",
      rejectReasonLabel:"لماذا لا يمكنك قبوله؟ · مطلوب",
      rejectReasons:["لا توفر","خطأ في السعر","الفندق غير متاح","الغرفة خارج الخدمة","الفندق تجاوز الحجز","مشكلة تشغيلية","خارج عن إرادتنا","سبب آخر"],
      rejectReasonsNote:"قائمة ثابتة: لا توفر · خطأ في السعر · الفندق غير متاح · الغرفة خارج الخدمة · الفندق تجاوز الحجز · مشكلة تشغيلية · خارج عن إرادتنا · سبب آخر",
      rejectDisagree:"تقويمك لا يتفق معك",
      rejectDisagreeBody:"يقول إن ١٢ و٩ و٧ غرف ستاندرد متاحة في ٢٤ و٢٥ و٢٦ سبتمبر. وإن لم يكن ذلك صحيحًا فسيصطدم الوكيل التالي بالجدار نفسه - أوقف البيع في تلك الليالي أيضًا.",
      rejectStopSale:"أوقف البيع أيضًا على الغرفة الستاندرد في ٢٤ - ٢٦ سبتمبر",
      rejectStopSaleNote:"تُحفظ الأسعار والغرف - ويمكنك فتحها مجددًا في أي وقت.",
      rejectNoteLabel:"ملاحظة لهوتيليانا · اختيارية",
      rejectNotePh:"أي شيء ينبغي إبلاغ الوكيل به",
      rejectRecorded:"يُسجَّل سببك واسمك والوقت على الحجز. ولا يمكن التراجع عن هذا، وتُبلَّغ هوتيليانا فور ضغطك.",
      rejectKeep:"الغرف تبقى لك.",
      rowOpen:"فتح الحجز",
      rowAddNumber:"إضافة رقم التأكيد",
      rowCopy:"نسخ المرجع",
      rowExport:"تصدير هذا الحجز",
      filterHotelTitle:"اختر فندقًا واحدًا أو اعرضها كلها.",
      filterStayTitle:"يصفّي حسب ليالي إقامة الضيف.",
      filterBookedTitle:"يصفّي حسب وقت إنشاء الوكيل للحجز.",
      filterSortTitle:"يغيّر ترتيب الصفوف فقط.",
      bookingsCount:"{count} حجزًا",
      arrivingToday:"الوصول اليوم",
      departingToday:"المغادرة اليوم",
      thisMonth:"هذا الشهر",
      anyTime:"أي وقت",
      today:"اليوم",
      last7:"آخر ٧ أيام",
      last30:"آخر ٣٠ يومًا",
      pickRange:"اختر فترة",
      pickRangeNote:"حدد تواريخك بنفسك",
      sortArriving:"الأقرب وصولًا",
      sortDeadline:"موعد الرد أولًا",
      sortDeadlineNote:"الطلبات التي تنتهي أسرع",
      sortRate:"الأعلى سعرًا أولًا",
      clear:"مسح",
      cancelCta:"إلغاء",
      allFilters:"كل الفلاتر",
      back:"العودة إلى الحجوزات",
      meta:"{id}  ·  {hotel}  ·  حجزه وكيل هوتيليانا اليوم ١١:٣٥",
      slaTitle:"أجب قبل {time} اليوم - تبقّت {left} دقيقة",
      slaBody:"تمنح هوتيليانا {hours} ساعات في هذا الفندق، ووصل الطلب في {arrived}. وإن لم يُجب حتى ذلك الوقت ينتهي من تلقاء نفسه، وبعدها لا يمكنك تأكيده أو رفضه.",
      slaChip:"{hours} ساعات",
      slaChipNote:"تحددها هوتيليانا لا أنت",
      heldNote:"{rooms} غرف محجوزة في ٢٤ و٢٥ و٢٦ سبتمبر ما دام الطلب مفتوحًا. ارفضه أو اتركه ينتهي فتعود للبيع فورًا - ولا يُفقد شيء في الحالتين.",
      beforeOverline:"قبل أن تقرر",
      beforeTitle:"الغرف متوفرة لديك - وهذا الحجز ليس على سعرك الحالي",
      beforeBody:"أمران يستحقان النظر قبل الرد. ولا يقرر أي منهما عنك.",
      roomsLeft:"غرف متبقية من {of}",
      needs:"يحتاج هذا الحجز {rooms}",
      afterBooking:"بعد هذا الحجز",
      rateTitle:"بيع هذا الحجز بـ{sold} في الليلة - ثم رفعت نصف الإقامة إلى {now}",
      rateBody:"حجز الوكيل قبل نشر تعديلك، فـ{sold} هو المستحق لك عليه. وتغيير السعر ليس سببًا لرفض حجز بيع بالفعل.",
      calendarOverline:"ما الذي تغيّر في تقويمك",
      calendarTitle:"خرجت غرفتان في الليلة من الحصة",
      calendarBody2:"كل خطط الوجبات على الغرفة الستاندرد ترى الأرقام نفسها - حصة واحدة مشتركة بينها.",
      keptTitle:"يبقى هذا الحجز على {sold} في الليلة",
      keptGroupTitle:"يحتفظ هذا الحجز بسعر {group}",
      keptBody:"رفعت نصف الإقامة إلى {now} بعد بيعه. ويحتفظ الحجز بالسعر والسياسة اللذين بيع بهما - وهذا لا يتغير أبدًا.",
      detailsOverline:"تفاصيل الحجز",
      detailsTitle:"كل ما يلزم لتشغيل الإقامة",
      statusRow:"الحالة",
      statusPending:"بانتظار التأكيد",
      statusReference:"مؤكد · رقم التأكيد بانتظارك",
      statusConfirmed:"مؤكد",
      guestsOverline:"الضيوف",
      guestsTitle:"أرسلها الوكيل",
      requestsOverline:"طلبات خاصة",
      requestsTitle:"ليست جزءًا من العقد - نفّذ ما تستطيع",
      answerOverline:"ردّك",
      answerTitle:"هل يمكنك قبول هذا الحجز؟",
      answerBody:"التأكيد يخرج {rooms} غرف من حصة الغرفة الستاندرد في ٢٤ و٢٥ و٢٦ سبتمبر. وتفقدها خطط الوجبات الأخرى على تلك الغرفة أيضًا - حصة واحدة مشتركة.",
      ifConfirm:"إن أكّدت",
      ifConfirmBody:"يصبح الحجز مؤكدًا، ويُحفظ رقم تأكيدك عليه وتبلغ هوتيليانا الوكيل. وتخرج {rooms} غرف من حصتك فورًا.",
      ifReject:"إن رفضت",
      ifRejectBody:"تختار سببًا من قائمة ثابتة ويمكنك إضافة ملاحظة. تعيده هوتيليانا إلى الوكيل، وتبقى غرفتك معروضة للبيع ما لم توقفها بنفسك.",
      ifNothing:"إن لم تفعل شيئًا",
      ifNothingBody:"في {time} يصبح الطلب منتهيًا من تلقاء نفسه. وبعدها لا يمكنك تأكيده أو رفضه، وتضع هوتيليانا الضيف في مكان آخر.",
      recorded:"يُسجَّل اختيارك مهما كان باسمك ووقته.",
      rejectCta:"رفض الطلب",
      confirmCta:"تأكيد هذا الحجز",
      confirmedTitle:"تم التأكيد في {time} اليوم - أبلغت هوتيليانا الوكيل",
      confirmedBody:"أكّدت دون رقم الفندق. الضيف مؤكد في الحالتين؛ والرقم إجراء ورقي ما زالت هوتيليانا تحتاجه.",
      confirmedBodyRooms:"أكّدت دون أرقام الفندق. الضيف مؤكد في الحالتين؛ والأرقام إجراء ورقي ما زالت هوتيليانا تحتاجه.",
      addNumber:"أضف رقم التأكيد",
      addNumbers:"أضف أرقام التأكيد",
      leftOverline:"بقي شيء واحد",
      leftTitle:"هوتيليانا تنتظر رقم تأكيدك",
      leftTitleRooms:"هوتيليانا تنتظر أرقام الفندق · {in} من {rooms}",
      leftBody:"اكتب الرقم الذي أعطاك إياه الفندق. وسيصلك تذكير واحد اليوم الساعة ١٨:٠٠ حتى يُضاف.",
      leftBodyRooms:"اكتب الرقم الذي أعطاه الفندق لكل غرفة. ويصلك تذكير واحد اليوم الساعة ١٨:٠٠ حتى يكون لكل غرفة رقمها.",
      leftPoints:[["الضيف بأمان","المؤكد مؤكد. الغرف محجوزة وأُبلغ الوكيل."],["يصلك تذكير واحد","اليوم الساعة ١٨:٠٠، ويبقى في مهامك حتى يُضاف الرقم."],["ترى هوتيليانا العلامة نفسها","لا داعي لأن يطاردك أحد - يرون أن الرقم بالانتظار."]],
      leftPointsRooms:[["الضيف بأمان","المؤكد مؤكد. الغرف محجوزة وأُبلغ الوكيل."],["يصلك تذكير واحد","اليوم الساعة ١٨:٠٠، ويبقى في مهامك حتى يكون لكل غرفة رقمها."],["ترى هوتيليانا العلامة نفسها","لا داعي لأن يطاردك أحد - يرون أن الرقم بالانتظار."]],
      doneTitle:"مؤكد · {number} مسجّل على الملف",
      doneTitleBoth:"مؤكد · لكلّ من الغرفتين رقمها",
      doneTitleEvery:"مؤكد · لكل غرفة رقمها",
      partialChip:"{in} من {numbers} وصل",
      partialTitle:"مؤكد · {in} من {rooms} لها رقم",
      partialBody:"غرفة {done} مسجّلة على الملف. وغرفة {left} ما زالت معلّقة — والتذكير يعمل لتلك الغرفة وحدها.",
      addMissing:"أضف الرقم الناقص",
      numbersOverline:"أرقام تأكيد الفندق · واحد لكل غرفة",
      numbersHeading:"{in} من {rooms} لها رقم",
      numbersHeadingBoth:"لكلّ من الغرفتين رقمها",
      numbersHeadingEvery:"لكل غرفة رقمها",
      roomLine:"الغرفة {n}",
      cancelledChipTitle:"مؤكد · أُلغيت {rooms}",
      cancelledNote:"أُلغيت الغرفة {n} في {on}، فعادت غرفة واحدة في الليلة إلى مخزون الغرفة القياسية في ٢٤ و٢٥ و٢٦ سبتمبر.",
      cancelledNumbersHeading:"{active} غرفة فعّالة · {void} رقم لاغٍ",
      roomCancelledVoid:"أُلغيت الغرفة · الرقم لاغٍ",
      cancelledBandTitle:"أُلغيت الغرفة {n}",
      cancelledBandBody:"ألغى الوكيل الغرفة {n} ({who}) في {on} بموجب سياسة الحجز. ورقمها {number} لاغٍ — لم يعد يظهر على القسيمة ولا في مسار. وعادت غرفة واحدة في الليلة إلى مخزونك.",
      cancelledTag:"أُلغيت",
      rowRoomsCancelled:"{left} من {total} · أُلغيت الغرفة {n}",
      rowOccupancyCancelled:"بالغان · الغرفة {left} وحدها",
      rowTotalCancelled:"{total} ر.س · {rate} × {nights} ليالٍ × غرفة واحدة",
      rowChargeLabel:"رسوم الإلغاء",
      rowCharge:"١٠٠٪ (غير قابل للاسترداد) · {total} ر.س · الغرفة {n} · {rate} × {nights} ليالٍ",
      doneOverline:"لا شيء متبقٍ",
      doneCardTitle:"هذا الحجز مكتمل",
      doneCardBody:"النزيل مؤكّد، وكل غرفة لها رقمها، والغرف خارج مخزونك.",
      doneAgentTitle:"الوكيل لديه الخبر",
      doneAgentBody:"أُزيلت الغرفة {n} من القسيمة ومن مسار.",
      doneCalendarTitle:"تقويمك محدَّث",
      doneCalendarBody:"غرفة {left} خارج مخزون الغرفة القياسية في الليالي الثلاث؛ والغرفة {n} عادت.",
      doneWrongTitle:"إن سار شيء على غير ما يرام",
      doneWrongBody:"لا يمكنك إلغاء حجز مؤكّد — أبلِغ عن مشكلة وتتولّاها هوتيليانا.",
      editNumbers:"عدّل الأرقام",
      numberAdded:"أُضيف الرقم",
      numberPending:"معلّق",
      notAddedYet:"لم يُضف بعد",
      leftTitlePartial:"غرفة {left} ما زالت تحتاج رقمها",
      leftBodyPartial:"اكتب رقم غرفة {left} حين يصدره الفندق. ويصلك تذكير واحد اليوم الساعة ١٨:٠٠ حتى يصل.",
      leftSafeTitle:"النزيل بخير",
      leftSafeBody:"المؤكّد مؤكّد. والغرف محجوزة والوكيل أُبلِغ.",
      leftReminderTitle:"يصلك تذكير واحد",
      leftReminderBody:"اليوم الساعة ١٨:٠٠، لغرفة {left} وحدها، حتى يُضاف رقمها.",
      leftFlagTitle:"هوتيليانا ترى العلامة نفسها",
      leftFlagBody:"لا يحتاج أحد إلى مطالبتك — فهم يرون أن الرقم معلّق.",
      leftFoot:"لا يمكنك إلغاء حجز مؤكّد بنفسك — استخدم «أبلِغ عن مشكلة».",
      doneBody:"كل ما تحتاجه هوتيليانا مكتمل. ولم يعد شيء في هذا الحجز ينتظرك.",
      doneHeading:"هذا الحجز مكتمل",
      doneLead:"الضيف مؤكد، والرقم محفوظ، والغرف خرجت من حصتك.",
      donePoints:[["الوكيل لديه الرقم","مرّرت هوتيليانا رقم تأكيدك."],["تقويمك محدّث","خرجت غرفتان من حصة الغرفة الستاندرد في الليالي الثلاث."],["إن حدث خطأ","لا يمكنك إلغاء حجز مؤكد - أبلغ عن مشكلة وتتولاها هوتيليانا."]],
      cannotCancel:"لا يمكنك إلغاء حجز مؤكد بنفسك - استخدم «الإبلاغ عن مشكلة».",
      reportIssue:"الإبلاغ عن مشكلة",
      addNumberCta:"إضافة الرقم",
      allotmentNote:"خرجت {rooms} من حصة الغرفة الستاندرد في {days}. وفقدتها خطط الغرفة فقط والإفطار على تلك الغرفة أيضًا.",
    },
    overline:"الحجوزات", title:"الحجوزات", needAnswerPill:"{count} بانتظار ردّك", subtitle:"كل ما حجزه الوكلاء على فنادقك، والأمران اللذان ينتظران ردّك.", export:"تصدير", arrivals:"الوصول اليوم · {count}", departures:"المغادرة اليوم · {count}", changes:"طلبات التغيير", needYou:"{count} طلبات تنتظر ردّك", needYouNote:"هذه حجوزات عند الطلب. تمنحك هوتيليانا ٣ ساعات في هذا الفندق - وبعدها ينتهي الطلب من تلقاء نفسه ولا يمكنك قبوله. الأوقات بتوقيت السعودية (UTC+3).", cardRoom:"الغرفة", cardStay:"الإقامة", cardSize:"الحجم", cardTotal:"إجماليك", cardSize2:"{nights} · {rooms}", respondBy:"الرد قبل {time} اليوم  ·  تبقّت {left} دقيقة", arrived:"وصل {time}", openDecide:"افتح وقرّر", onRequest:"عند الطلب", all:"الكل", answer:"تحتاج ردًا", confirmed:"مؤكدة", cancelled:"ملغاة", rejected:"مرفوضة", expired:"منتهية", cancelAsked:"طلبات الإلغاء", amendAsked:"طلبات التعديل", searchLabel:"البحث", search:"ابحث بالضيف أو المرجع أو الفندق", hotelLabel:"الفندق", allHotels:"كل الفنادق ({count})", stayLabel:"تواريخ الإقامة", allStays:"أي", anyStayDate:"أي تاريخ إقامة", bookedLabel:"تاريخ الحجز", anyBooked:"أي", sortLabel:"الترتيب", newest:"الأحدث أولًا", hotelMenuHint:"اختر فندقًا واحدًا أو اعرضها كلها.", stayMenuHint:"يُصفّي على الليالي التي يقيمها الضيف.", stayRangeHint:"الحجوزات التي لها أي ليلة في هذه التواريخ", bookedRangeHint:"الحجوزات المُنشأة في هذه الأيام", showRange:"اعرض {label}", bookedMenuHint:"يُصفّي على وقت إنشاء الوكيل للحجز.", sortMenuHint:"يغيّر ترتيب الصفوف فقط.", reference:"المرجع", guest:"الضيف", hotelOffer:"الفندق والغرفة", stay:"الإقامة", rooms:"الغرف", rate:"إجماليك · شامل الضريبة", status:"الحالة", decide:"اتخذ قرارًا", open:"فتح", review:"مراجعة", view:"عرض", referencePending:"رقم التأكيد بانتظارك", showing:"عرض ١-{shown} من {total} حجزًا", perPage:"٢٠ لكل صفحة", waitingFooter:"كلاهما يحجز غرفًا ما دام مفتوحًا. أجب أو اتركه ينتهي - لا شيء آخر يحررها.", listFooter:"الطلب المنتهي أو المرفوض لا يمكن إعادة فتحه - تعيده هوتيليانا إلى الوكيل. والحجز المؤكد لا يمكنك إلغاؤه أيضًا؛ استخدم «الإبلاغ عن مشكلة» وتتولاها هوتيليانا.", showingWaiting:"عرض ١-{shown} من {total} طلبات تنتظر ردّك", back:"كل الحجوزات", booking:"الحجز", booked:"تم الحجز", responseDue:"موعد الرد", decisionTitle:"الضيف ينتظر ردك", decisionBody:"راجع الغرف والسعر أدناه. التأكيد يحجز الغرف ويبلغ الوكيل فورًا.", remaining:"٢٣ دقيقة متبقية", confirm:"تأكيد الحجز", reject:"لا يمكنني قبوله", summary:"ملخص الحجز", guestStay:"الضيف والإقامة", calendar:"ما يفعله التأكيد بتقويمك", calendarBody:"تخرج الغرفتان من حصة غرفة ستاندرد، فتفقدهما «بدون وجبات» و«الإفطار» في تلك الليالي أيضًا.", night1:"الخميس ٢٤", night2:"الجمعة ٢٥", night3:"السبت ٢٦", left:"متبقية", rateTitle:"السعر المتفق عليه · شامل الضريبة", total:"الإجمالي لغرفتين · ٣ ليالٍ", hotelGets:"يستلم الفندق", supplied:"أرسله الوكيل", leadGuest:"الضيف الرئيسي", occupancy:"الإشغال", occupancyValue:"٤ بالغين · غرفتان", checkIn:"تسجيل الوصول", checkOut:"تسجيل المغادرة", special:"الطلبات الخاصة", specialBody:"طابق مرتفع إن أمكن. يصل الضيوف بعد ٢٢:٠٠.", confirmTitle:"تأكيد هذا الحجز", confirmIntro:"غرفة ستاندرد · نصف إقامة · الخميس ٢٤ - الأحد ٢٧ سبتمبر. يصبح الحجز مؤكدًا وتبلغ هوتيليانا الوكيل فورًا.", confirmationChoice:"رقم تأكيد المورّد · مطلوب · يمكنك إضافته لاحقًا", confirmationChoiceBody:"تحتاج هوتيليانا الرقم الذي يعطيك إياه الفندق. وإن لم يصدره بعد فأكّد على أي حال - الضيف هو المهم، والورق يلحق.", pendingNote:"يظهر الحجز بـ«مؤكد · بانتظار المرجع». ويظهر في مهامك، ويصلك تذكير واحد اليوم الساعة ١٨:٠٠، وترى هوتيليانا العلامة نفسها فلا يحتاج أحد أن يلاحقك.", noteHint:"لا تقرأها إلا هوتيليانا - ولا يراها الوكيل", recordedNote:"يُسجّل باسمك ووقته.", haveIt:"الرقم معي", haveItHint:"يتأكد الحجز مع حفظ الرقم عليه", later:"لم يصدر بعد - أكّد الآن وأضفه لاحقًا", laterHint:"يبقى الحجز مؤكدًا والغرف محجوزة", number:"رقم التأكيد", ownRef:"مرجعك في نظامك، إن كنت تستخدمه", note:"ملاحظة إلى Hoteliana · اختيارية", confirmNow:"تأكيد الحجز", confirmLater:"تأكيد بدون الرقم", rejectionTitle:"لا يمكنك قبول هذا الحجز", reason:"لماذا لا يمكنك قبوله؟ · مطلوب", noAvailability:"لا يوجد توفر", rateError:"خطأ في السعر", unavailable:"الفندق غير متاح", operational:"مشكلة تشغيلية", other:"سبب آخر", stopSale:"أوقف البيع أيضًا على غرفة ستاندرد في ٢٤ - ٢٦ سبتمبر", rejectRequest:"رفض الطلب", result:"النتيجة", confirmedAt:"تم التأكيد اليوم ١٢:١٤", toldAgent:"أبلغت Hoteliana الوكيل وتم حجز الغرف.", oneLeft:"شيء واحد متبقٍ", waitingNumber:"Hoteliana تنتظر رقم تأكيدك", reminder:"أضفه عند صدوره من الفندق. سيصلك تذكير اليوم ١٨:٠٠.", addNumber:"إضافة رقم التأكيد", saveNumber:"حفظ الرقم", numberTitle:"إضافة رقم تأكيد الفندق", numberHelp:"الحجز مؤكد بالفعل. وهذا هو الرقم الذي تحتاجه هوتيليانا للملف.", savedNumber:"مؤكد · الرقم {number} موجود في الملف", everything:"كل ما يلزم لتنفيذ الإقامة موجود الآن في الحجز.", nothing:"لا يوجد شيء متبقٍ", report:"الإبلاغ عن مشكلة", issueLead:"لست أنت من يلغي حجزًا مؤكّدًا. إنما تُبلِّغ أنك لا تستطيع الوفاء به، وتقرر هوتيليانا ما يحدث: نقل أو استبدال أو إلغاء. فالوكيل يحمل رقم تأكيد بالفعل، والإلغاء الصامت يكسر دخول النزيل.", issueDoesTitle:"ما الذي يفعله الإبلاغ عن مشكلة", issueDoesNote:"لا شيء أدناه تلقائي - وهوتيليانا تقرر النتيجة.", issueDoes:[["info","ينتقل الحجز إلى «مشكلة تنفيذ · قيد المراجعة». ويرى الوكيل هذه الحالة أيضًا."],["info","تعمل هوتيليانا على الحالة معك بالطريقة التي تعمل بها أصلاً - بالهاتف إن كان أسرع."],["info","تُسجّل النتيجة نقلاً أو استبدالاً أو إلغاءً من هوتيليانا."],["no","وقد يؤثر في أدائك كمورّد وفي تسويتك، بحسب النتيجة."],["yes","ويمكنك إيقاف البيع في الوقت نفسه لئلا تُباع الليلة نفسها مرة أخرى."]] as const, issueTitle:"الإبلاغ عن مشكلة إلى Hoteliana", wrong:"ما المشكلة · مطلوب", describe:"صف المشكلة · مطلوب", alternative:"هل يمكنك تقديم بديل؟ · اختياري · اختر واحدًا", sameNights:"غرفة مختلفة في الليالي نفسها", sameRoom:"الغرفة نفسها في ليالٍ مختلفة", none:"لا شيء - لا يستطيع الفندق استقبالهم إطلاقًا", stopSaleIssue:"أوقف البيع أيضًا حتى تراجع هوتيليانا المشكلة", stopSaleIssueNote:"حتى لا يحدث الشيء نفسه للوكيل التالي.", issueStays:"يبقى الحجز مؤكدًا حتى ترد هوتيليانا. ولا شيء تفعله هنا يلغيه - ولا يلغيه إلا هوتيليانا مع الوكيل.", issueSla:"ترد هوتيليانا على المشكلات خلال ساعتين في ساعات العمل (بتوقيت السعودية).", sameNightsHint:"ديلوكس إطلالة المدينة فيها ٨ متاحة في ٢٤ - ٢٦ سبتمبر", sameRoomHint:"غرفة ستاندرد فيها ١٦ متاحة في ٢٧ - ٢٩ سبتمبر", describePh:"ما الذي حدث، وما الذي يمكنك تقديمه بديلًا إن وُجد", wrongPh:"حجز زائد · غرفة غير متاحة · بيانات الضيف خاطئة · سعر أو سياسة خاطئة · غير ذلك", send:"إرسال إلى Hoteliana", issueSent:"وصل البلاغ إلى Hoteliana", issueRef:"ISS-2026-0184 · أُرسل ١٢:٤١", issueBody:"المشكلة الآن لدى Hoteliana. يظل الحجز مؤكدًا أثناء المراجعة.", expiredTitle:"انتهى هذا الطلب اليوم ١٤:٣٥", expiredBody:"أعادته Hoteliana إلى الوكيل. لم يعد بإمكانك تأكيده أو رفضه.", prevent:"امنع تكرار ذلك", untouched:"لم يتغير مخزونك", alerts:"تحقق ممن تصله التنبيهات", rejectedTitle:"تم رفض هذا الطلب", cancellationTitle:"طلب الوكيل إلغاء هذا الحجز", amendmentTitle:"طلب الوكيل تعديل هذا الحجز", approve:"الموافقة على الطلب", decline:"رفض الطلب", requestResolved:"تمت مراجعة الطلب وإبلاغ الوكيل.", close:"إغلاق", SAR:"ر.س"
  }
} as const;