export const changeRequestCopy = {
  en: {
    outCancelled:"Cancelled", outCharged:"{amount} SAR charged", outChargePending:"Charge pending",
    outWaivedPill:"Waived · {reason}", outAutoPill:"Auto-applied · policy",
    outCancelMeta:"{id}  ·  {hotel}  ·  cancelled today at 10:12 by you",
    outAutoMeta:"{id}  ·  {hotel}  ·  cancelled on 11 Sep at 09:40 · automatically",
    outCancelTitle:"This booking is cancelled",
    outCancelBody:"Hoteliana has been told and is settling the {amount} with the agent. Your name and the time are on the booking, and nothing here can be edited.",
    outWaiveBody:"Hoteliana has been told. No money moves - the charge was waived for {reason}. Your name and the time are on the booking.",
    outAutoTitle:"No answer in 24 h - the policy was applied",
    outAutoBody:"The request reached its deadline without an answer, so the full policy charge was applied for you. Hoteliana is settling the {amount} with the agent.",
    outAmountNote:"recorded against the booking",
    outWaivedNote:"waived · {reason}",
    backOverline:"WHAT CAME BACK TO YOU",
    backTitle:"Both nights are on sale again - the 12th is no longer sold out",
    backNights:[["SAT 12 SEP","0","1","rooms free","was sold out · open again"],["SUN 13 SEP","8","9","rooms free","open again"]],
    backNote:"Both nights were still open, so the rooms are sellable again immediately. On a night that is on stop sale the room would come back and the night would stay closed - inventory and sellability are two different questions.",
    moneyOverline:"THE MONEY",
    moneyFullTitle:"You charged the full {amount} SAR",
    moneyFullBody:"Everything the policy allowed. The policy that decided this amount was the one locked onto the booking on 2 September.",
    moneyWaiveTitle:"You waived the {amount} SAR",
    moneyWaiveBody:"The policy allowed {amount} SAR. You chose to charge nothing - reason: {reason}. It is counted as goodwill in your reports.",
    moneyAutoTitle:"The full {amount} SAR was applied",
    moneyAutoBody:"Nobody answered within 24 h, so the system applied everything the policy allowed - the fairest default for you.",
    bookingStatusLabel:"Booking status",
    financialStatusLabel:"Financial status",
    financialPending:"Charge pending → Hoteliana settles with the agent",
    financialWaived:"No charge · waived",
    amendedPill:"Amended", amendedConfirmed:"Confirmed · 27 - 29 Sep", amendedNoCost:"No cost change",
    amendedMeta:"{id}  ·  {hotel}  ·  change approved today at 08:41 by you",
    amendedTitle:"The lead guest is now {name}",
    amendedBody:"Nothing else moved. Your rooms, your rate and the cancellation policy are exactly as they were sold.",
    amendedAmountNote:"what you are owed · unchanged",
    movedOverline:"WHAT MOVED",
    movedTitle:"Only the name moved - no room and no money moved",
    movedNote:"The cancellation policy is unchanged - a name change never renews or shortens the free window.",
    declinedPill:"Amendment declined", unchangedPill:"Booking unchanged",
    declinedMeta:"{id}  ·  {hotel}  ·  declined today at 08:41 by you",
    declinedTitle:"The change was declined - the name stays exactly as it was sold",
    declinedBody:"The booking keeps {name}. Hoteliana tells the agent.",
    expiredPill:"Amendment expired",
    expiredMeta:"{id}  ·  {hotel}  ·  expired on 11 Sep at 17:20 · no answer",
    expiredTitle:"The change expired - nobody answered within 48 h, so the name stays exactly as it was.",
    expiredBody:"No answer in 48 h - the request expired. The booking keeps {name}. Hoteliana tells the agent.",
    movedNothingTitle:"Nothing - and that is the point",
    movedNothingNote:"Declining an amendment never touches the original booking. The guest still arrives on 22 September under the same rate and the same policy.",
    unchangedNote:"unchanged",
    moneyStatusOverline:"MONEY & STATUS",
    moneyStatusTitle:"Booking status and financial status are two different things",
    adjustmentLabel:"Financial adjustment", adjustmentNone:"None",
    settlementLabel:"Settlement status", settlementNone:"Nothing to settle - the change costs nothing",
    requestStatusLabel:"Request status",
    waiveOverline:"{id} · {guest} · CEILING {amount} SAR",
    waiveTitle:"Charge nothing at all?",
    waiveBody:"The cancellation goes through with no money attached, recorded as goodwill.",
    waivePolicyAllowed:"Policy allowed", waiveYouCharge:"You charge", waiveYouChargeValue:"0 SAR · waived",
    waiveRecordedAs:"Recorded as", waiveGoodwill:"Goodwill · with your name and the time",
    waiveRecordedPicked:"Waived · {reason} · with your name and the time",
    waiveReasonLabel:"WHY ARE YOU WAIVING IT? · REQUIRED",
    waiveReasonPh:"Pick a reason",
    waiveReasons:["Guest emergency","Hotel’s own error","Keeping the agent relationship","Room was re-sold","Other"],
    waiveReasonNote:"A fixed list, so waived amounts can be counted by reason in reports.",
    waiveNoteLabel:"NOTE · OPTIONAL",
    waiveNotePh:"e.g. repeat agent, guest will rebook in October",
    waiveFooter:"Waiving is visible to Hoteliana and stays on the booking. It does not change the policy on the contract and it does not apply to any other booking.",
    waiveCta:"Waive the charge and cancel",
    declineOverline:"{id} · {guest} · {request}",
    declineTitle:"Decline this amendment",
    declineBody:"Nothing on the booking moves. The name stays {name}, exactly as it was sold.",
    declineReasonLabel:"REASON · REQUIRED",
    declineReasons:["The ID on file does not match the new name","Policy","Operational","Other"],
    declineReasonNote:"Fixed list: ID mismatch · policy · operational · other",
    declineNoteLabel:"NOTE TO HOTELIANA · OPTIONAL",
    declineNotePh:"Anything the agent should be told",
    declineNoteHint:"Optional - the reason above is what Hoteliana counts in reports.",
    declinePoints:[["The booking stays","27 - 29 Sep · 2 nights · 1,120 SAR · v1"],["Your inventory","Untouched - no room moves either way"],["What the agent is told","Hoteliana passes your reason on to the agent"],["Can it come back?","The agent can ask again, and you can answer differently"]],
    declineFooter:"Declining an amendment is not declining the booking. The original stay is untouched.",
    rowMenuMeta:"Cancellation asked today 09:40",
    rowItems:[["Review the request","answer it - this is the one action that clears it"],["Open the booking","the confirmed booking behind the request"],["See the policy that applies","the window, the ceiling, and where it came from"],["Copy the reference","{id}"],["Report an issue to Hoteliana","when the request itself looks wrong"]],
    rowMenuNote:"The row menu never answers the request - it only takes you to the place where you can.",
 cancelAskedPill:"Cancellation asked", stillConfirmed:"Booking is still confirmed", noChargeYet:"No charge yet",
    policyOverline:"THE POLICY LOCKED ONTO THIS BOOKING",
    policyTitle:"The free window closed at midnight, so a full stay charge is yours to take",
    policyBody:"Free cancellation until 2 days before arrival, then a full stay charge. This is the policy as it was on 2 September - anything you changed in the rate contract since then does not reach it.",
    decisionOverline:"YOUR DECISION",
    decisionTitle:"How much of the {amount} do you take?",
    decisionBody:"The policy is a ceiling, not an order. Charging less is your call and Hoteliana passes on whatever you decide.",
    chargeFullNote:"everything the policy allows",
    chargeLessNote:"you set the amount - the rest is written off",
    waiveNote:"goodwill, recorded on the booking",
    statusBooking:"BOOKING STATUS",
    statusBookingValue:"Confirmed · cancellation requested",
    statusFinancial:"FINANCIAL STATUS",
    statusFinancialValue:"No charge yet → Charge pending",
    statusSettles:"WHO SETTLES IT",
    statusSettlesValue:"Hoteliana, with the agent",
    reportInstead:"Report an issue instead",
    confirmingOverline:"WHAT CONFIRMING DOES",
    confirmingTitle:"Two things happen, and only one of them is money",
    confirmingPoints:[["The rooms come back","12 September goes from 0 left to 1, and 13 September from 8 to 9. Both nights are still open, so both are sellable again the moment you confirm."],["The money goes to Hoteliana","Your 1,420 is recorded against the booking with status Charge pending. Hoteliana settles it with the agent - you do not invoice anyone."],["You cannot refuse, but you can flag","If the cancellation itself looks wrong - the wrong booking, a date that already passed - use Report an issue instead of confirming."]],
    confirmingNote:"A returned room is not automatically on sale. If one of those nights is on stop sale, the room comes back but the night stays closed until you reopen it.",
    detailsOverline:"BOOKING DETAILS",
    detailsTitle:"Everything needed to run the stay",
    guestsOverline:"GUESTS & REASON",
    guestsTitle:"Guest data stays visible while the cancellation is open",
    amendPills:["Amendment asked","Non-commercial","No cost change","Booking unchanged"],
    movesOverline:"EXACTLY WHAT MOVES",
    movesTitle:"Only the name on the booking moves",
    movesNote:"A non-commercial amendment runs no availability, rate or restriction check - there is nothing to re-evaluate. The booking keeps its rate, its policy and its snapshot.",
    amendAnswerOverline:"YOUR ANSWER",
    amendAnswerTitle:"Approve the new name, or decline",
    amendAnswerBody:"Approving writes v2 with the new name. No room moves, no money moves, and the guest still arrives on 27 September.",
    amendPoints:[["If you approve","The name on the booking changes and Hoteliana tells the agent. Your allotment and your settlement are untouched."],["If the ID looks wrong","Report an issue instead of approving - a wrong ID at check-in is the hotel’s problem, not the agent’s."],["If you decline","The booking keeps the original name. Hoteliana tells the agent, and the guest at the desk has to match the booking."]],
    idCheck:"I checked that the new ID number 1081 4460 matches Faisal Al-Harbi. A wrong ID at check-in is the hotel’s problem, not the agent’s.",
    declineChange:"Decline the change",
    versionsOverline:"VERSIONS",
    versionsTitle:"Approving writes a new version - it never overwrites the old one",
    versionRows:[["Booking v1","Live","27 - 29 Sep · Bader Al-Harbi","sold 9 Sep · contract v1.3"],["AMD-001","Pending","Lead guest name · no cost change","asked yesterday 17:20"],["Booking v2","Not yet","27 - 29 Sep · Faisal Al-Harbi","exists only if you approve"]],
    versionsNote:"v1 is never deleted. Settlement and any dispute later read the version that was live at the time, with its own rate, policy and snapshot.",
    amendDetailsOverline:"BOOKING & GUESTS",
    amendDetailsTitle:"The dates do not change - only the lead guest name",
    statusLabel:"Status",
    statusCancel:"Confirmed · cancellation requested",
    statusAmend:"Confirmed · name change requested",
    overline:"BOOKINGS · CHANGE REQUESTS", title:"Change requests", waiting:"{count} waiting on you", subtitle:"What agents want changed on bookings that are already confirmed. Hoteliana forwards every request — the agent never contacts you directly.", allBookings:"All bookings", export:"Export", urgentTitle:"{count} requests are waiting on you", urgentBody:"A cancellation is settled by the policy locked onto that booking — you decide how much of what it allows you actually charge. An amendment is a non-commercial change, such as the lead guest name: approve it or decline it.", all:"All", cancellations:"Cancellations", amendments:"Amendments", agent:"Waiting on the agent", handled:"Handled", search:"Search guest or reference", allHotels:"All 3 hotels", allTypes:"All types", anyTime:"Any time", oldest:"Oldest first", reference:"REFERENCE", guest:"GUEST", ask:"WHAT THEY ASK", stay:"STAY", meaning:"WHAT IT MEANS FOR YOU", asked:"RESPOND BY", searchLabel:"SEARCH", hotelLabel:"HOTEL", typeLabel:"TYPE", respondLabel:"RESPOND BY", sortLabel:"SORT", perPage:"20 per page", agentEmptyTitle:"Nothing is waiting on the agent", agentEmptyBody:"When you answer a request and the agent still has to act, it shows up here.", showingAmendments:"Showing 1-{shown} of {total} amendment", showingAgent:"Showing {shown} of {total} waiting on the agent", showingHandled:"Showing 1-{shown} of {total} handled request", review:"Review", quote:"Quote", view:"View", room:"ROOM", value:"BOOKING VALUE", cancelledPart:"CANCELLED PART", showing:"Showing 1-{shown} of {total} requests", load:"Load 9 more", footer:"Hoteliana settles the money with the agent once you answer. A cancellation cannot be refused — only priced. An amendment costs nothing either way; you approve the new name or decline it. A longer stay is a new booking, never an amendment.", filter:"Filter the change requests", apply:"Apply · {count} results", clear:"Clear all", searchTitle:"Search the change requests", matches:"MATCHES", exportTitle:"Export the change requests", inView:"The requests in view", openOnly:"Every request still waiting on someone", everything:"Everything, handled included", format:"FORMAT", columns:"COLUMNS", exportRows:"Export {count} rows", back:"Back to change requests", report:"Report an issue", policy:"THE POLICY LOCKED ONTO THIS BOOKING", decision:"YOUR DECISION", full:"Charge the full {amount} SAR", less:"Charge less", waive:"Waive it - charge nothing", confirmCancellation:"Confirm the cancellation", chargeTitle:"How much do you take?", amount:"AMOUNT YOU CHARGE", note:"NOTE · OPTIONAL", confirmAt:"Confirm at {amount} SAR", cancelledTitle:"This booking is cancelled", whatBack:"WHAT CAME BACK TO YOU", money:"THE MONEY", happened:"WHAT HAPPENED", closed:"Nothing left to do", exactly:"EXACTLY WHAT MOVES", engine:"THE BOOKING ENGINE RAN AGAIN ON THE NEW NIGHT", price:"THE PRICE", answer:"YOUR ANSWER", approve:"Approve at the system price", different:"Propose a different rate", decline:"Decline the change", quoteRate:"Quote {amount} SAR", waitingAgent:"Your rate is with the agent — nothing has moved yet", approved:"The change is approved", declined:"The change was declined — the stay is exactly as it was sold", versions:"VERSIONS", bookingGuests:"BOOKING & GUESTS", approveName:"Approve the new name", bookingDetails:"BOOKING DETAILS", status:"STATUS", result:"RESULT", pass:"Pass", cancel:"Cancel", reason:"REASON · REQUIRED", send:"Send to the agent", withdraw:"Withdraw offer", rowReview:"Review the request", openBooking:"Open the booking", seePolicy:"See the policy that applies", copyRef:"Copy the reference", noResults:"No change requests match these filters.", SAR:"SAR"
  },
  ar: {
    outCancelled:"ملغى", outCharged:"حُصّل {amount} ر.س", outChargePending:"رسوم معلّقة",
    outWaivedPill:"مُعفى · {reason}", outAutoPill:"طُبّق تلقائيًا · السياسة",
    outCancelMeta:"{id}  ·  {hotel}  ·  أُلغي اليوم ١٠:١٢ بواسطتك",
    outAutoMeta:"{id}  ·  {hotel}  ·  أُلغي في ١١ سبتمبر ٠٩:٤٠ · تلقائيًا",
    outCancelTitle:"هذا الحجز ملغى",
    outCancelBody:"أُبلغت هوتيليانا وتسوّي الـ{amount} مع الوكيل. واسمك والوقت على الحجز، ولا يمكن تعديل شيء هنا.",
    outWaiveBody:"أُبلغت هوتيليانا. لا مال يتحرك - أُعفيت الرسوم بسبب {reason}. واسمك والوقت على الحجز.",
    outAutoTitle:"لا رد خلال ٢٤ ساعة - طُبّقت السياسة",
    outAutoBody:"بلغ الطلب موعده النهائي بلا رد، فطُبّقت رسوم السياسة الكاملة نيابةً عنك. وتسوّي هوتيليانا الـ{amount} مع الوكيل.",
    outAmountNote:"مسجّل على الحجز",
    outWaivedNote:"مُعفى · {reason}",
    backOverline:"ما الذي عاد إليك",
    backTitle:"الليلتان معروضتان للبيع مجددًا - ولم يعد الثاني عشر نافدًا",
    backNights:[["السبت ١٢ سبتمبر","0","1","غرف متاحة","كانت نافدة · مفتوحة مجددًا"],["الأحد ١٣ سبتمبر","8","9","غرف متاحة","مفتوحة مجددًا"]],
    backNote:"كانت الليلتان مفتوحتين، فأصبحت الغرف قابلة للبيع فورًا. وفي ليلة بإيقاف بيع تعود الغرفة وتبقى الليلة مغلقة - فالمخزون وقابلية البيع سؤالان مختلفان.",
    moneyOverline:"المال",
    moneyFullTitle:"حصّلت الـ{amount} ر.س كاملة",
    moneyFullBody:"كل ما سمحت به السياسة. والسياسة التي حددت هذا المبلغ هي المثبتة على الحجز في ٢ سبتمبر.",
    moneyWaiveTitle:"أعفيت الـ{amount} ر.س",
    moneyWaiveBody:"سمحت السياسة بـ{amount} ر.س. واخترت ألا تحصّل شيئًا - السبب: {reason}. ويُحتسب حسن نية في تقاريرك.",
    moneyAutoTitle:"طُبّقت الـ{amount} ر.س كاملة",
    moneyAutoBody:"لم يجب أحد خلال ٢٤ ساعة، فطبّق النظام كل ما سمحت به السياسة - وهو الافتراض الأعدل لك.",
    bookingStatusLabel:"حالة الحجز",
    financialStatusLabel:"الحالة المالية",
    financialPending:"رسوم معلّقة ← تسوّيها هوتيليانا مع الوكيل",
    financialWaived:"بلا رسوم · مُعفى",
    amendedPill:"مُعدَّل", amendedConfirmed:"مؤكد · ٢٧ - ٢٩ سبتمبر", amendedNoCost:"بلا تغيير في التكلفة",
    amendedMeta:"{id}  ·  {hotel}  ·  قُبل التغيير اليوم ٠٨:٤١ بواسطتك",
    amendedTitle:"الضيف الرئيسي الآن {name}",
    amendedBody:"لم يتحرك شيء آخر. غرفك وسعرك وسياسة الإلغاء كما بيعت تمامًا.",
    amendedAmountNote:"المستحق لك · دون تغيير",
    movedOverline:"ما الذي تحرّك",
    movedTitle:"الاسم وحده تحرّك - لا غرفة ولا مال",
    movedNote:"سياسة الإلغاء دون تغيير - وتغيير الاسم لا يجدد نافذة الإلغاء المجاني ولا يقصّرها.",
    declinedPill:"رُفض التعديل", unchangedPill:"الحجز دون تغيير",
    declinedMeta:"{id}  ·  {hotel}  ·  رُفض اليوم ٠٨:٤١ بواسطتك",
    declinedTitle:"رُفض التغيير - ويبقى الاسم كما بيع تمامًا",
    declinedBody:"يحتفظ الحجز بـ{name}. وتبلغ هوتيليانا الوكيل.",
    expiredPill:"انتهى التعديل",
    expiredMeta:"{id}  ·  {hotel}  ·  انتهى في ١١ سبتمبر ١٧:٢٠ · بلا رد",
    expiredTitle:"انتهى التغيير - لم يجب أحد خلال ٤٨ ساعة، فيبقى الاسم كما هو.",
    expiredBody:"لا رد خلال ٤٨ ساعة - انتهى الطلب. ويحتفظ الحجز بـ{name}. وتبلغ هوتيليانا الوكيل.",
    movedNothingTitle:"لا شيء - وهذا هو المقصود",
    movedNothingNote:"رفض التعديل لا يمس الحجز الأصلي أبدًا. ويصل الضيف في ٢٢ سبتمبر بالسعر نفسه والسياسة نفسها.",
    unchangedNote:"دون تغيير",
    moneyStatusOverline:"المال والحالة",
    moneyStatusTitle:"حالة الحجز والحالة المالية أمران مختلفان",
    adjustmentLabel:"تسوية مالية", adjustmentNone:"لا يوجد",
    settlementLabel:"حالة التسوية", settlementNone:"لا شيء للتسوية - التغيير لا يكلّف شيئًا",
    requestStatusLabel:"حالة الطلب",
    waiveOverline:"{id} · {guest} · السقف {amount} ر.س",
    waiveTitle:"ألا تحصّل شيئًا إطلاقًا؟",
    waiveBody:"يمضي الإلغاء بلا مال، ويُسجَّل حسن نية.",
    waivePolicyAllowed:"سمحت به السياسة", waiveYouCharge:"ستحصّل", waiveYouChargeValue:"٠ ر.س · مُعفى",
    waiveRecordedAs:"يُسجَّل كـ", waiveGoodwill:"حسن نية · باسمك والوقت",
    waiveRecordedPicked:"مُعفى · {reason} · باسمك والوقت",
    waiveReasonLabel:"لماذا تعفيها؟ · مطلوب",
    waiveReasonPh:"اختر سببًا",
    waiveReasons:["ظرف طارئ للضيف","خطأ من الفندق","الحفاظ على العلاقة مع الوكيل","أُعيد بيع الغرفة","آخر"],
    waiveReasonNote:"قائمة ثابتة، حتى يمكن عدّ المبالغ المُعفاة حسب السبب في التقارير.",
    waiveNoteLabel:"ملاحظة · اختيارية",
    waiveNotePh:"مثال: وكيل متكرر، سيحجز الضيف مجددًا في أكتوبر",
    waiveFooter:"الإعفاء ظاهر لهوتيليانا ويبقى على الحجز. ولا يغيّر السياسة على العقد ولا ينطبق على أي حجز آخر.",
    waiveCta:"إعفاء الرسوم والإلغاء",
    declineOverline:"{id} · {guest} · {request}",
    declineTitle:"رفض هذا التعديل",
    declineBody:"لا يتحرك شيء في الحجز. ويبقى الاسم {name} كما بيع تمامًا.",
    declineReasonLabel:"السبب · مطلوب",
    declineReasons:["الهوية المسجّلة لا تطابق الاسم الجديد","السياسة","تشغيلي","آخر"],
    declineReasonNote:"قائمة ثابتة: عدم تطابق الهوية · السياسة · تشغيلي · آخر",
    declineNoteLabel:"ملاحظة لهوتيليانا · اختيارية",
    declineNotePh:"أي شيء ينبغي إبلاغ الوكيل به",
    declineNoteHint:"اختيارية - السبب أعلاه هو ما تعدّه هوتيليانا في التقارير.",
    declinePoints:[["يبقى الحجز","٢٧ - ٢٩ سبتمبر · ليلتان · ١٬١٢٠ ر.س · v1"],["مخزونك","دون مساس - لا تتحرك غرفة في الحالتين"],["ما يُبلَّغ به الوكيل","تنقل هوتيليانا سببك إلى الوكيل"],["هل يمكن أن يعود؟","يمكن للوكيل أن يطلب مجددًا، ويمكنك أن تجيب بشكل مختلف"]],
    declineFooter:"رفض التعديل ليس رفضًا للحجز. والإقامة الأصلية دون مساس.",
    rowMenuMeta:"طُلب الإلغاء اليوم ٠٩:٤٠",
    rowItems:[["مراجعة الطلب","أجب عليه - هذا الإجراء الوحيد الذي يغلقه"],["فتح الحجز","الحجز المؤكد خلف الطلب"],["عرض السياسة المنطبقة","النافذة والسقف ومن أين أتيا"],["نسخ المرجع","{id}"],["الإبلاغ عن مشكلة لهوتيليانا","عندما يبدو الطلب نفسه خاطئًا"]],
    rowMenuNote:"قائمة الصف لا تجيب على الطلب أبدًا - إنما تأخذك إلى المكان الذي تجيب فيه.",
 cancelAskedPill:"طُلب الإلغاء", stillConfirmed:"الحجز ما زال مؤكدًا", noChargeYet:"لا رسوم بعد",
    policyOverline:"السياسة المثبتة على هذا الحجز",
    policyTitle:"أُغلقت نافذة الإلغاء المجاني منتصف الليل، فرسوم الإقامة كاملة من حقك",
    policyBody:"إلغاء مجاني حتى يومين قبل الوصول، ثم رسوم الإقامة كاملة. هذه السياسة كما كانت في ٢ سبتمبر - وأي تعديل أجريته في عقد الأسعار بعدها لا يصلها.",
    decisionOverline:"قرارك",
    decisionTitle:"كم ستأخذ من الـ{amount}؟",
    decisionBody:"السياسة سقف لا أمر. وتحصيل مبلغ أقل قرارك، وتنقل هوتيليانا ما تقرره.",
    chargeFullNote:"كل ما تسمح به السياسة",
    chargeLessNote:"تحدد المبلغ - والباقي يُشطب",
    waiveNote:"حسن نية، ويُسجَّل على الحجز",
    statusBooking:"حالة الحجز",
    statusBookingValue:"مؤكد · طُلب الإلغاء",
    statusFinancial:"الحالة المالية",
    statusFinancialValue:"لا رسوم بعد ← رسوم معلّقة",
    statusSettles:"من يسوّيها",
    statusSettlesValue:"هوتيليانا، مع الوكيل",
    reportInstead:"الإبلاغ عن مشكلة بدلًا من ذلك",
    confirmingOverline:"ماذا يفعل التأكيد",
    confirmingTitle:"يحدث أمران، وواحد منهما فقط يتعلق بالمال",
    confirmingPoints:[["تعود الغرف","١٢ سبتمبر تنتقل من ٠ متبقية إلى ١، و١٣ سبتمبر من ٨ إلى ٩. وكلتا الليلتين ما زالتا مفتوحتين، فتصبحان قابلتين للبيع لحظة تأكيدك."],["يذهب المال إلى هوتيليانا","تُسجَّل ١٬٤٢٠ على الحجز بحالة «رسوم معلّقة». وتسوّيها هوتيليانا مع الوكيل - ولا تُصدر أنت فاتورة لأحد."],["لا يمكنك الرفض، لكن يمكنك التنبيه","إن بدا الإلغاء نفسه خاطئًا - حجز خاطئ أو تاريخ مضى - استخدم «الإبلاغ عن مشكلة» بدلًا من التأكيد."]],
    confirmingNote:"الغرفة العائدة ليست معروضة للبيع تلقائيًا. فإن كانت إحدى تلك الليالي بإيقاف بيع تعود الغرفة وتبقى الليلة مغلقة حتى تعيد فتحها.",
    detailsOverline:"تفاصيل الحجز",
    detailsTitle:"كل ما يلزم لتشغيل الإقامة",
    guestsOverline:"الضيوف والسبب",
    guestsTitle:"تبقى بيانات الضيف ظاهرة ما دام الإلغاء مفتوحًا",
    amendPills:["طُلب تعديل","غير تجاري","بلا تغيير في التكلفة","الحجز دون تغيير"],
    movesOverline:"ما الذي يتغيّر بالضبط",
    movesTitle:"الاسم على الحجز وحده هو ما يتغيّر",
    movesNote:"التعديل غير التجاري لا يُجري أي فحص للإتاحة أو السعر أو القيود - فلا شيء لإعادة تقييمه. ويحتفظ الحجز بسعره وسياسته ولقطته.",
    amendAnswerOverline:"ردّك",
    amendAnswerTitle:"اقبل الاسم الجديد أو ارفضه",
    amendAnswerBody:"القبول يكتب الإصدار v2 بالاسم الجديد. لا تتحرك غرفة ولا مال، ويصل الضيف في ٢٧ سبتمبر كما هو.",
    amendPoints:[["إن قبلت","يتغيّر الاسم على الحجز وتبلغ هوتيليانا الوكيل. ولا تُمس حصتك ولا تسويتك."],["إن بدت الهوية خاطئة","أبلغ عن مشكلة بدلًا من القبول - الهوية الخاطئة عند الوصول مشكلة الفندق لا الوكيل."],["إن رفضت","يحتفظ الحجز بالاسم الأصلي. وتبلغ هوتيليانا الوكيل، وعلى الضيف عند المكتب أن يطابق الحجز."]],
    idCheck:"تحققت من أن رقم الهوية الجديد 1081 4460 يطابق فيصل الحربي. والهوية الخاطئة عند الوصول مشكلة الفندق لا الوكيل.",
    declineChange:"رفض التغيير",
    versionsOverline:"الإصدارات",
    versionsTitle:"القبول يكتب إصدارًا جديدًا - ولا يستبدل القديم أبدًا",
    versionRows:[["إصدار الحجز v1","ساري","٢٧ - ٢٩ سبتمبر · بدر الحربي","بيع ٩ سبتمبر · العقد v1.3"],["AMD-001","معلّق","اسم الضيف الرئيسي · بلا تغيير في التكلفة","طُلب أمس ١٧:٢٠"],["إصدار الحجز v2","ليس بعد","٢٧ - ٢٩ سبتمبر · فيصل الحربي","لا يوجد إلا إن قبلت"]],
    versionsNote:"لا يُحذف v1 أبدًا. وتقرأ التسوية وأي نزاع لاحق الإصدار الذي كان ساريًا وقتها، بسعره وسياسته ولقطته.",
    amendDetailsOverline:"الحجز والضيوف",
    amendDetailsTitle:"التواريخ لا تتغير - الاسم الرئيسي وحده",
    statusLabel:"الحالة",
    statusCancel:"مؤكد · طُلب الإلغاء",
    statusAmend:"مؤكد · طُلب تغيير الاسم",
    overline:"الحجوزات · طلبات التغيير", title:"طلبات التغيير", waiting:"{count} بانتظار ردّك", subtitle:"التغييرات التي يطلبها الوكلاء على حجوزات مؤكدة. تنقل Hoteliana كل طلب — ولا يتواصل الوكيل معك مباشرة.", allBookings:"كل الحجوزات", export:"تصدير", urgentTitle:"{count} طلبات بانتظار ردّك", urgentBody:"يُحسم الإلغاء وفق السياسة المثبتة على الحجز — وتحدد ما ستُحصّله من الحد المسموح. أما التعديل فتغيير غير تجاري، كاسم الضيف الرئيسي: تقبله أو ترفضه.", all:"الكل", cancellations:"الإلغاءات", amendments:"التعديلات", agent:"بانتظار الوكيل", handled:"تمت المعالجة", search:"ابحث بالضيف أو المرجع", allHotels:"كل الفنادق الثلاثة", allTypes:"كل الأنواع", anyTime:"أي وقت", oldest:"الأقدم أولًا", reference:"المرجع", guest:"الضيف", ask:"المطلوب", stay:"الإقامة", meaning:"ما يعنيه لك", asked:"الرد قبل", searchLabel:"البحث", hotelLabel:"الفندق", typeLabel:"النوع", respondLabel:"الرد قبل", sortLabel:"الترتيب", perPage:"٢٠ لكل صفحة", agentEmptyTitle:"لا شيء بانتظار الوكيل", agentEmptyBody:"عندما ترد على طلب ويبقى على الوكيل أن يتصرف، يظهر هنا.", showingAmendments:"عرض ١-{shown} من {total} تعديلًا", showingAgent:"عرض {shown} من {total} بانتظار الوكيل", showingHandled:"عرض ١-{shown} من {total} طلبًا مُعالجًا", review:"مراجعة", quote:"تقديم سعر", view:"عرض", room:"الغرفة", value:"قيمة الحجز", cancelledPart:"الجزء الملغى", showing:"عرض ١-{shown} من {total} طلبًا", load:"تحميل ٩ أخرى", footer:"تتولى Hoteliana التسوية مع الوكيل بعد ردك. لا يمكن رفض الإلغاء بل تسعيره فقط، والتعديل لا يكلّف شيئًا في الحالتين؛ تقبل الاسم الجديد أو ترفضه. والإقامة الأطول حجز جديد لا تعديل.", filter:"تصفية طلبات التغيير", apply:"تطبيق · {count} نتائج", clear:"مسح الكل", searchTitle:"البحث في طلبات التغيير", matches:"النتائج", exportTitle:"تصدير طلبات التغيير", inView:"الطلبات الظاهرة", openOnly:"كل طلب ما زال ينتظر ردًا", everything:"كل الطلبات بما فيها المعالجة", format:"الصيغة", columns:"الأعمدة", exportRows:"تصدير {count} صفوف", back:"العودة لطلبات التغيير", report:"الإبلاغ عن مشكلة", policy:"السياسة المثبتة على هذا الحجز", decision:"قرارك", full:"تحصيل كامل {amount} ر.س", less:"تحصيل مبلغ أقل", waive:"الإعفاء — دون تحصيل", confirmCancellation:"تأكيد الإلغاء", chargeTitle:"كم تريد تحصيله؟", amount:"المبلغ الذي تحصله", note:"ملاحظة · اختيارية", confirmAt:"تأكيد مبلغ {amount} ر.س", cancelledTitle:"تم إلغاء هذا الحجز", whatBack:"ما عاد إليك", money:"الأموال", happened:"ما حدث", closed:"لا يوجد إجراء آخر", exactly:"ما الذي سيتغير بالضبط", engine:"أعاد محرك الحجز الفحص على الليلة الجديدة", price:"السعر", answer:"ردك", approve:"قبول بسعر النظام", different:"اقتراح سعر مختلف", decline:"رفض التغيير", quoteRate:"عرض {amount} ر.س", waitingAgent:"عرضك لدى الوكيل — لم يتغير شيء بعد", approved:"تم اعتماد التغيير", declined:"رُفض التغيير — الإقامة كما بيعت تمامًا", versions:"الإصدارات", bookingGuests:"الحجز والضيوف", approveName:"اعتماد الاسم الجديد", bookingDetails:"تفاصيل الحجز", status:"الحالة", result:"النتيجة", pass:"ناجح", cancel:"إلغاء", reason:"السبب · مطلوب", send:"إرسال للوكيل", withdraw:"سحب العرض", rowReview:"مراجعة الطلب", openBooking:"فتح الحجز", seePolicy:"عرض السياسة المطبقة", copyRef:"نسخ المرجع", noResults:"لا توجد طلبات تغيير تطابق هذه الفلاتر.", SAR:"ر.س"
  }
} as const;
export function crFill(value:string, vars:Record<string,string|number>){return Object.entries(vars).reduce((out,[key,item])=>out.replace(`{${key}}`,String(item)),value)}
