/**
 * Copy for the linked hotel profile / room catalogue flow
 * (Figma: UI 02.2L, OV 02.R1, OV 02.R2, OV 02.R3).
 */
export const hotelEn = {
  hotelProfile: {
    overline: "MY HOTELS · HOTEL PROFILE",
    // meta: "{district}, {city}, {country} · {stars} stars · Hoteliana ID {id}",
    meta: "{city}, {country} · {stars} stars",
    badgeLinked: "Linked",
    badgeSelling: "Selling",
    createContract: "Create supply contract",
    imagesCounter: "{at} / {images}",
    galleryGroup: "Hotel photographs",
    galleryPrevious: "Previous photograph",
    galleryNext: "Next photograph",
    galleryAlt: "{name} · photograph {at}",
    detailsOverline: "OFFICIAL HOTELIANA PROFILE · READ ONLY",
    detailsTitle: "Hotel details",
    nameEn: "Hotel name (EN)",
    nameAr: "Hotel name (AR)",
    country: "Country",
    city: "City",
    area: "Area",
    address: "Address",
    starRating: "Star rating",
    starsValue: "{stars} stars · Official (Ministry of Tourism)",
    /* Flow 12 · Row B — Hoteliana owns the licence; the supplier reads it. */
    tourismLicence: "Tourism licence",
    licenceExpiry: "Licence expiry",
    descEn: "Description (EN)",
    descAr: "Description (AR)",
    distance: "Distance to Haram",
    amenitiesOverline: "AMENITIES",
    amenitiesTitle: "Hotel amenities",
    roomsOverline: "OFFICIAL CATALOGUE · {rooms} ROOMS · {pending} PENDING",
    roomsTitle: "Room catalogue",
    roomsSubtitle:
      "The view is part of the room. Meal plans and prices are set in your supply contract.",
    addMissingRoom: "Add missing room",
    table: {
      room: "ROOM",
      occupancy: "OCCUPANCY",
      guests: "GUESTS",
      childAge: "CHILD AGE",
      bed: "BED",
      size: "SIZE",
      view: "VIEW",
      images: "IMAGES",
      status: "STATUS",
    },
    guests: "{adults} adults · {children} children",
    guestsOneChild: "{adults} adults · 1 child",
    guestsNoChild: "{adults} adults",
    upTo: "Up to {age}",
    statusAvailable: "Official",
    statusPending: "Waiting for Hoteliana",
    footnote:
      "Official hotel and room data is maintained by Hoteliana. Changes go through a request and stay pending until approved. A pending room cannot be priced in a supply contract yet.",
  },
  roomDrawer: {
    overline: "{hotel} · ROOM CATALOGUE",
    title: "Add a missing room",
    subtitle:
      "Enter the room exactly as the hotel sells it. Each view is its own room - Deluxe City View and Deluxe Haram View are two rooms.",
    name: "Room name",
    namePh: "e.g. Family Suite",
    dupHint: "Duplicate check runs against {hotel} as you type the room name.",
    dupTitle: "A similar room already exists in this hotel",
    dupUse: "Open the existing room",
    dupSummary:
      "{guests} guests · {adults} adults + {children} children · {bed} · {size} · {match}",
    matchName: "name match 100%",
    matchOccupancy: "occupancy match",
    dupNote:
      "Continue only if the room is genuinely different. Hoteliana runs the same check again and rejects a duplicate at approval.",
    occupancy: "Max occupancy",
    occupancyPh: "Guests",
    adults: "Adults",
    adultsPh: "Adults",
    children: "Children",
    childrenPh: "Children",
    childAge: "Max child age",
    childAgePh: "Years",
    bed: "Bed type",
    bedPh: "Bed type",
    size: "Room size",
    sizePh: "m²",
    view: "View",
    viewPh: "Choose the view",
    images: "Room images · minimum 2",
    dropTitle: "Drop room images here or browse",
    dropHint: "JPG or PNG · up to 10 MB each · first image is the cover",
    cover: "COVER",
    info: "The room is sent to Hoteliana for verification. It will not appear in the official catalogue or in any supply contract until approved.",
    submit: "Submit for Hoteliana review",
    /** OV 02.R2 — the same button, once a near-match was passed. */
    submitDifferent: "Send as a different room",
    rights:
      "I confirm we own or hold the rights to these images and allow Hoteliana to display them on the platform and partner channels.",
    guestsSuffix: "{count} guests",
    yearsSuffix: "{count} years",
    sentOverline: "ROOM SUBMITTED",
    sentTitle: "Room sent for Hoteliana review",
    sentBody: "It stays out of the catalogue and out of every supply contract until approved.",
    sentRefMeta: "{room} · {hotel} · submitted just now",
    nextOverline: "WHAT HAPPENS NEXT",
    next1: "Sent now - {count} images attached",
    next2: "Hoteliana verifies the room against the hotel (usually 2 working days)",
    next3:
      "Approved → “Added to official catalogue”, visible and in every supply contract room list",
    meanwhile: "Meanwhile the room shows in the catalogue as “Pending Hoteliana”.",
    backToHotel: "Back to hotel",
    viewRequests: "View requests",
    amenityList: [
      "Wi-Fi",
      "Parking",
      "Restaurant",
      "24h desk",
      "Airport transfer",
      "Family rooms",
      "Lift",
      "Accessible",
    ],
  },
};

export const hotelAr: typeof hotelEn = {
  hotelProfile: {
    overline: "فنادقي · ملف الفندق",
    meta: "{city}، {country} · {stars} نجوم",
    badgeLinked: "مرتبط",
    badgeSelling: "يُباع",
    createContract: "إنشاء عقد توريد",
    imagesCounter: "{at} / {images}",
    galleryGroup: "صور الفندق",
    galleryPrevious: "الصورة السابقة",
    galleryNext: "الصورة التالية",
    galleryAlt: "{name} · الصورة {at}",
    detailsOverline: "الملف الرسمي في هوتيليانا · للقراءة فقط",
    detailsTitle: "بيانات الفندق",
    nameEn: "اسم الفندق (إنجليزي)",
    nameAr: "اسم الفندق (عربي)",
    country: "الدولة",
    city: "المدينة",
    area: "الحي",
    address: "العنوان",
    starRating: "التصنيف",
    starsValue: "{stars} نجوم · رسمي (وزارة السياحة)",
    tourismLicence: "رخصة السياحة",
    licenceExpiry: "انتهاء الرخصة",
    descEn: "الوصف (إنجليزي)",
    descAr: "الوصف (عربي)",
    distance: "المسافة إلى الحرم",
    amenitiesOverline: "المرافق",
    amenitiesTitle: "مرافق الفندق",
    roomsOverline: "الكتالوج الرسمي · {rooms} غرف · {pending} قيد المراجعة",
    roomsTitle: "كتالوج الغرف",
    roomsSubtitle:
      "كل غرفة لها إطلالة واحدة. خطط الوجبات والأسعار تُحدَّد في عقد الأسعار وليس هنا.",
    addMissingRoom: "إضافة غرفة ناقصة",
    table: {
      room: "الغرفة",
      occupancy: "الإشغال",
      guests: "الضيوف",
      childAge: "عمر الطفل",
      bed: "السرير",
      size: "المساحة",
      view: "الإطلالة",
      images: "الصور",
      status: "الحالة",
    },
    guests: "{adults} بالغين · {children} أطفال",
    guestsOneChild: "{adults} بالغين · طفل واحد",
    guestsNoChild: "{adults} بالغين",
    upTo: "حتى {age}",
    statusAvailable: "رسمية",
    statusPending: "بانتظار هوتيليانا",
    footnote:
      "بيانات الفندق والغرف الرسمية تديرها هوتيليانا. أي تعديل يمر بطلب ويبقى قيد المراجعة حتى الموافقة، والغرفة قيد المراجعة لا يمكن تسعيرها في عقد الأسعار.",
  },
  roomDrawer: {
    overline: "{hotel} · كتالوج الغرف",
    title: "إضافة غرفة ناقصة",
    subtitle:
      "أدخل الغرفة كما يبيعها الفندق تمامًا. نوع الغرفة الواحد له إطلالة واحدة؛ والغرفة التي تُباع بإطلالتين تُعد نوعين.",
    name: "اسم الغرفة",
    namePh: "مثال: الجناح العائلي",
    dupHint: "يتم فحص التكرار مقابل {hotel} أثناء كتابة اسم الغرفة.",
    dupTitle: "توجد غرفة مشابهة في هذا الفندق",
    dupUse: "استخدم هذه الغرفة",
    dupSummary: "{guests} ضيوف · {adults} بالغين + {children} أطفال · {bed} · {size} · {match}",
    matchName: "تطابق الاسم ١٠٠٪",
    matchOccupancy: "تطابق الإشغال",
    dupNote:
      "تابع فقط إذا كانت الغرفة مختلفة فعلًا. هوتيليانا تُجري الفحص نفسه وترفض المكرر عند الموافقة.",
    occupancy: "أقصى إشغال",
    occupancyPh: "عدد الضيوف",
    adults: "البالغون",
    adultsPh: "البالغون",
    children: "الأطفال",
    childrenPh: "الأطفال",
    childAge: "أقصى عمر للطفل",
    childAgePh: "سنة",
    bed: "نوع السرير",
    bedPh: "نوع السرير",
    size: "مساحة الغرفة",
    sizePh: "م²",
    view: "الإطلالة",
    viewPh: "اختر الإطلالة",
    images: "صور الغرفة · صورتان على الأقل",
    dropTitle: "أفلت صور الغرفة هنا أو تصفّح",
    dropHint: "JPG أو PNG · حتى ١٠ ميجابايت للصورة · الصورة الأولى هي الغلاف",
    cover: "الغلاف",
    info: "تُرسل الغرفة إلى هوتيليانا للتحقق، ولن تظهر في الكتالوج الرسمي ولا في أي عقد توريد حتى الموافقة.",
    submit: "إرسال لمراجعة هوتيليانا",
    submitDifferent: "أرسلها كغرفة مختلفة",
    rights:
      "أقرّ بأننا نملك حقوق هذه الصور أو نحوزها، ونسمح لهوتيليانا بعرضها على المنصة وقنوات الشركاء.",
    guestsSuffix: "{count} ضيوف",
    yearsSuffix: "{count} سنة",
    sentOverline: "تم إرسال الغرفة",
    sentTitle: "أُرسلت الغرفة لمراجعة هوتيليانا",
    sentBody: "تبقى خارج الدليل وخارج كل عقود التوريد حتى الموافقة.",
    sentRefMeta: "{room} · {hotel} · أُرسلت الآن",
    nextOverline: "ما يحدث بعد ذلك",
    next1: "أُرسلت الآن — {count} صور مرفقة",
    next2: "تتحقق هوتيليانا من الغرفة مقابل الفندق (عادة يومي عمل)",
    next3: "بعد الموافقة → تظهر في الكتالوج وفي قائمة غرف كل عقد أسعار",
    meanwhile: "في هذه الأثناء تظهر الغرفة في الكتالوج بحالة «بانتظار هوتيليانا».",
    backToHotel: "العودة إلى الفندق",
    viewRequests: "عرض الطلبات",
    amenityList: [
      "واي فاي",
      "مواقف",
      "مطعم",
      "استقبال ٢٤ ساعة",
      "نقل المطار",
      "غرف عائلية",
      "مصعد",
      "مهيأ لذوي الاحتياجات",
    ],
  },
};
