/** Copy for the screens added after the first pass (decisions, requests, add hotel/room, overlays). */
export const extraEn = {
  decision: {
    approvedOverline: "REQUEST APPROVED",
    approvedTitle: "Your company record has been updated",
    approvedBody:
      "Hoteliana approved the requested changes. The new values are now the active supplier record.",
    approvedStatus: "Approved",
    rejectedOverline: "REQUEST REJECTED",
    rejectedTitle: "The requested changes were not approved",
    rejectedBody:
      "Your existing approved company data remains active. Review the reason below, correct the details, and resubmit.",
    rejectedStatus: "Rejected",
    partlyOverline: "PARTLY APPROVED",
    partlyTitle: "Two changes approved, one rejected",
    partlyBody:
      "Hoteliana approved the phone number and the commercial registration. The bank IBAN was rejected, so your current IBAN stays active.",
    partlyStatus: "2 OF 3 APPROVED",
    decided: "Decision completed",
    reference: "Request reference CHG-00042",
    appliedOverline: "CHANGE REQUEST · 3 DETAILS",
    partlyAppliedOverline: "CHANGE REQUEST · 3 DETAILS · 1 REJECTED",
    appliedTitle: "Approved information",
    rejectedListTitle: "Requested information",
    partlyListTitle: "Decision by detail",
    reasonOverline: "REASON FROM HOTELIANA",
    reasonTitle: "Why it was rejected",
    approvedNoteFooter:
      "The approved values are now visible on the Agreement page.",
    rejectedNoteFooter:
      "Rejection reason: the submitted document does not match the registered legal company record.",
    partlyNoteFooter:
      "Phone number and commercial registration are live now. The bank IBAN was rejected - the letter does not match the registered legal company name.",
    applied: "Approved",
    notApplied: "Rejected",
    timelineOverline: "STATUS",
    timelineTitle: "Review timeline",
    submitted: "Submitted",
    submittedNote: "Complete · 12 Sep",
    review: "Hoteliana review",
    reviewNote: "Complete · 13 Sep",
    decision: "Decision per detail",
    approvedNote: "Approved",
    rejectedNote: "Rejected",
    partlyNote: "Partly approved",
    notified: "Supplier notified",
    notifiedNote: "Complete",
    viewRecord: "View updated company record",
    continueLibrary: "Continue to Hotel Library",
    returnAgreement: "Return to Company & agreement",
    editResubmit: "Edit and resubmit",
    resubmitRejected: "Resubmit the rejected detail",
    newRequest: "Send a new request",
  },
  requests: {
    overline: "PROPERTY · REQUESTS",
    title: "Requests",
    subtitle:
      "Everything you sent to Hoteliana - hotel access, new hotels, new rooms and company changes. Rows that need you come first.",
    tab: "Requests",
    browseLibrary: "Browse Hotel Library",
    statWaiting: "WAITING FOR HOTELIANA",
    statWaitingNote: "usually 1 working day",
    statNeedsYou: "NEEDS YOU",
    statNeedsYouNote: "answer to keep them moving",
    statApproved: "APPROVED",
    statApprovedNote: "linked or added",
    statRejected: "REJECTED",
    statRejectedNote: "reason in detail",
    statDecided: "DECIDED",
    statDecidedNote: "in the last 30 days",
    filterAll: "All",
    filterAccess: "Hotel access",
    filterHotels: "New hotels",
    filterRooms: "New rooms",
    filterCompany: "Company changes",
    colRequest: "REQUEST",
    colType: "TYPE",
    colWhat: "WHAT",
    colSent: "SENT",
    colStatus: "STATUS",
    colUpdate: "LATEST UPDATE",
    colAction: "ACTION",
    showing: "Showing {shown} of {total} requests · sorted by: needs you first, then oldest waiting",
    footer:
      "One list for everything you sent to Hoteliana. A decision never changes your current data until it is approved.",
    emptyFooter:
      "Nothing to do right now. You will get a notification when Hoteliana decides or needs something from you.",
    listOverline: "ALL REQUESTS",
    listTitle: "{count} requests",
    /* OV 02.5B - what the two buttons say once they have done it. */
    withdrawn: "Request withdrawn",
    withdrawnNote: "The review is cancelled. You can ask for it again whenever you like.",
    caseOpened: "Your case is open with Hoteliana",
    kindAccess: "Hotel access",
    kindCompany: "Company change",
    kindHotel: "New hotel",
    kindRoom: "New room",
    open: "Open",
    empty: "No requests yet.",
    statePending: "Waiting",
    stateNeedsYou: "Needs you",
    stateApproved: "Approved",
    stateLinked: "Linked",
    stateNotApproved: "Rejected",
    sent: "sent {date}",
    decided: "decided {date}",
    drawerTimeline: "TIMELINE",
    drawerDetails: "WHAT YOU SENT",
    drawerNeeds: "WHAT HOTELIANA NEEDS",
    drawerDecision: "DECISION",
    finalNote: "This decision is final for 90 days.",
    respond: "Send the missing document",
    goToHotel: "Open the hotel",
    step1: "Request sent",
    step2: "Hoteliana review",
    step3: "Decision",
    step4: "You were notified",
    waiting: "Waiting",
    inProgress: "In progress",
    complete: "Complete",
  },
  addHotel: {
    overline: "HOTEL LIBRARY · ADD A MISSING HOTEL",
    title: "Add a missing hotel",
    subtitle:
      "Enter the hotel exactly as licensed. We check the library for duplicates as you type the name and place the pin.",
    open: "Add missing hotel",
    stepDetails: "Hotel details",
    stepMedia: "Photos & amenities",
    stepReview: "Review",
    identityOverline: "HOTEL IDENTITY",
    identityTitle: "Name and category",
    locationOverline: "LOCATION",
    locationTitle: "Address and map",
    name: "Hotel name (English) *",
    namePh: "e.g. Makkah Gate Hotel",
    nameAr: "Hotel name (Arabic) *",
    nameArPh: "مثال: فندق بوابة مكة",
    licence: "Tourism licence number · optional",
    licenceHint: "The strongest way to catch a duplicate",
    stars: "Star rating *",
    starsPh: "e.g. 4 stars · Official (Ministry of Tourism)",
    descEn: "Description (English) · optional",
    descEnPh: "Short hotel description",
    descAr: "Description (Arabic) · optional",
    descArPh: "وصف مختصر للفندق",
    country: "Country *",
    city: "City *",
    area: "Area · optional",
    areaPh: "Select area",
    address: "Address *",
    addressPh: "Street, district and building details",
    map: "Map location *",
    mapPh: "Paste a Google Maps link",
    mapHint: "Or click the map to drop the pin yourself.",
    pinConfirmed: "Pin confirmed · Al Mursalat, Makkah",
    required: "Fields marked * are required · {count} left",
    next: "Continue to photos",
    nextMedia: "Continue to review",
    continueAnyway: "It is a different hotel - continue",
    back: "Back",
    backDetails: "Back to hotel details",
    backMedia: "Back to photos & amenities",
    /* Arabic agrees the verb with the count as well as the noun, so
       the whole sentence is chosen rather than a number slotted in. */
    duplicateTitleOne:
      "1 hotel in the library looks like the one you are adding",
    duplicateTitleTwo:
      "2 hotels in the library look like the one you are adding",
    duplicateTitleFew:
      "{n} hotels in the library look like the one you are adding",
    duplicateTitleMany:
      "{n} hotels in the library look like the one you are adding",
    duplicateBody:
      "Creating a duplicate splits the same hotel across two records.",
    duplicateNote:
      "Continue only if this is a genuinely different property. Hoteliana runs the same check again before approval, and a duplicate is rejected at that point.",
    matchNote: "Map pin {distance} from yours · name match {match}",
    requestInstead: "Request access instead",
    view: "View",
    mediaOverline: "HOTEL IMAGES · {count} UPLOADED",
    mediaTitle: "Hotel photos",
    mediaSubtitle:
      "Upload clear hotel images and select every amenity guests can use.",
    dropzone: "Drop images here or choose files",
    dropzoneHint:
      "At least 3 images · JPG or PNG · up to 10 MB each · the first is the cover",
    mediaNote:
      "Avoid logos, screenshots and duplicate angles. Images stay pending until Hoteliana approves the hotel.",
    browse: "Choose files",
    addMore: "Add more photos",
    added: "✓  {count} more photos added · {size}",
    remove: "Remove",
    tryAgain: "Try again",
    cancelUpload: "Cancel",
    uploadSummary: "{count} files · {detail}",
    uploaded: "Uploaded",
    uploading: "Uploading · {percent}%",
    queued: "Waiting to upload",
    cover: "COVER",
    rights:
      "I confirm we own or hold the rights to these images and allow Hoteliana to display them on the platform and partner channels.",
    amenitiesOverline: "HOTEL AMENITIES · {count} SELECTED",
    amenitiesTitle: "Available amenities",
    amenitiesNote:
      "Only select amenities currently available to guests. Hoteliana may ask for proof of any amenity.",
    amenities: "Amenities",
    reviewTitle: "Review the submission",
    reviewSubtitle:
      "Check every detail before sending the hotel to Hoteliana for approval.",
    reviewStep1: "STEP 1 · HOTEL DETAILS",
    reviewStep2: "STEP 2 · PHOTOS & AMENITIES",
    reviewMedia: "{images} images · {amenities} amenities",
    edit: "Edit",
    fieldStars: "Star rating",
    starsSource: "Official (Ministry of Tourism)",
    fieldLicence: "Tourism licence",
    fieldCountry: "Country · Area",
    fieldAddress: "Address",
    fieldMap: "Map location",
    fieldDuplicate: "Duplicate check",
    fieldDescEn: "Description (EN)",
    fieldDescAr: "Description (AR)",
    duplicateSummary:
      "You continued past {count} similar hotels - Makkah Gate Towers (91%) and Bab Makkah (82%)",
    reviewLegal:
      "I confirm these details are accurate under the active Supplier Agreement.",
    submit: "Submit for approval",
    sentOverline: "SENT TO HOTELIANA",
    sentTitle: "The hotel is with Hoteliana",
    sentBody:
      "You can follow the decision in Requests. Once approved, the hotel appears in My Hotels and you can build a supply contract.",
    reference: "Request HOT-10391 · sent today",
    /** OV 02.8C — the line under the reference. */
    submittedJustNow: "submitted just now",
    reviewHotel: "Makkah Gate Hotel",
    viewRequests: "Open Requests",
    backToLibrary: "Back to Hotel Library",
    amenityList: [
      "Wi-Fi",
      "Parking",
      "Restaurant",
      "Room service",
      "Swimming pool",
      "Gym",
      "Airport shuttle",
      "Family rooms",
      "Accessibility",
      "24-hour reception",
      "Prayer room",
      "Laundry",
    ],
  },
  addRoom: {
    open: "Create room",
    title: "Create a new room",
    subtitle:
      "The room is sent to Hoteliana for verification. It will not appear in the official catalogue or in any supply contract until approved.",
    name: "Room name",
    namePh: "Family Suite",
    base: "Base occupancy",
    occupancy: "Maximum occupancy",
    occupancyPh: "6",
    adults: "Adults",
    adultsPh: "4",
    children: "Children",
    childrenPh: "2",
    childAge: "Maximum child age",
    childAgePh: "12",
    beds: "Bed type",
    bedsPh: "2 king · 1 sofa",
    size: "Room size",
    sizePh: "62 m²",
    view: "View",
    viewPh: "Haram",
    units: "Units in the hotel",
    unitsPh: "4",
    images: "Room images",
    imagesHint:
      "Drop room images here or browse. JPG or PNG · up to 10 MB each · the first image is the cover.",
    similarTitle: "A similar room already exists",
    similarBody:
      "“Family Suite” is already registered with 62 m² and the same bedding. Continue only if this is a different room.",
    similarContinue: "It is a different room",
    submit: "Submit for Hoteliana review",
    sentTitle: "Room sent for verification",
    sentBody: "You can follow the decision in Requests.",
    pending: "Pending verification",
  },

  libraryOverlay: {
    quickView: "Quick view",
    quickOverline: "HOTEL IN THE LIBRARY",
    /** OV 02.2 — the frame names the official id beside the hotel. */
    hotelianaId: "Hoteliana ID",
    quickRooms: "Registered rooms",
    quickAmenities: "Amenities",
    quickNote:
      "This hotel is owned and verified by Hoteliana. Request access to sell it under your agreement.",
    requestOne: "Request access",
    confirmTitle: "Request access to {count} hotels",
    confirmBody:
      "Hoteliana reviews the relationship between your company and each hotel before granting access.",
    confirmNext: "WHAT HAPPENS NEXT",
    confirmStep1: "Sent now — logged with the acting user and timestamp",
    confirmStep2: "Hoteliana reviews the relationship (usually 2 working days)",
    confirmStep3: "Approved hotels appear in My Hotels, ready for a supply contract",
    confirmSubmit: "Send the request",
    sentTitle: "Request sent",
    sentBody:
      "{count} hotels are now with Hoteliana. Follow the decision in Requests.",
    openRequests: "Open Requests",
    keepBrowsing: "Keep browsing",
    bookingType: "Booking confirmation type",
    bookingTypeHint:
      "Choose how bookings for this hotel are confirmed. Hoteliana applies it once access is granted.",
    instant: "Instant",
    instantHint: "Bookings are confirmed immediately from your allotment.",
    onRequest: "On Request",
    onRequestHint: "Each booking waits for your confirmation before it is final.",
    bookingTypeRequired: "Select a booking confirmation type to continue.",

  },
  docViewer: {
    overline: "VERIFIED COMPANY DOCUMENT",
    body: "Summary of the registered file. Request replacement to send Hoteliana a newer one.",
    issueDate: "ISSUE DATE",
    expiryDate: "EXPIRY DATE",
    statusLabel: "STATUS",
    valid: "Valid",
    expiring: "Expiring soon",
    currentFile: "Current file",
    viewOnly:
      "View-only document. Any replacement requires a change request and Hoteliana approval.",
    expiryNote:
      "Expiry reminders are sent 90 \u00b7 30 \u00b7 7 days before the date. Renew via a change request before {date} to keep your account active.",
    requestReplacement: "Request replacement",
  },
  select: {
    placeholder: "Select",
    multiPlaceholder: "Select one or more",
    tagsPlaceholder: "Type and press Enter",
    search: "Search",
    noResults: "No matches",
    selectedCount: "{count} selected",
    clear: "Clear",
    remove: "Remove",
    addTag: 'Add "{value}"',
    typeToSearch: "Type at least {count} characters",
    loading: "Loading…",
  },
  toast: {
    accessRequested: "Access request sent",
    accessRequestedDesc: "{hotels} now with Hoteliana for review.",
    changesSubmitted: "Change request submitted",
    changesSubmittedDesc: "You will get a decision within 2 working days.",
    hotelSubmitted: "Hotel sent for approval",
    hotelSubmittedDesc: "We will confirm once the hotel is added to the library.",
    roomSubmitted: "Room sent for approval",
    roomSubmittedDesc: "The room will appear once Hoteliana approves it.",
    signedIn: "Signed in",
    codeSent: "Verification code accepted",
    resetSent: "Reset link sent",
    passwordUpdated: "Password updated",
    photosAdded: "Photos uploaded",
    working: "Saving…",
    failed: "Something went wrong. Please try again.",
  },

  contracts: {
    tab: "Hotel supply contracts",
    overline: "PROPERTY · SUPPLY CONTRACTS",
    title: "Supply contracts",
    subtitle:
      "Every supply contract across your linked hotels, with its selling state.",
    empty: "No supply contracts yet. Link a hotel first, then create a contract.",
    create: "Create supply contract",
    continueDraft: "Continue draft",
    open: "Open contract",
    hotel: "Hotel",
    period: "Period",
    model: "Model",
    state: "State",
    count: "{count} contracts",
    allotment: "Allotment",
    onRequest: "On request",
  },
};



export const extraAr: typeof extraEn = {
  decision: {
    approvedOverline: "تم قبول الطلب",
    approvedTitle: "تم تحديث سجل شركتك",
    approvedBody:
      "وافقت هوتيليانا على التعديلات المطلوبة. القيم الجديدة أصبحت سجل المورّد الفعّال.",
    approvedStatus: "مقبول",
    rejectedOverline: "تم رفض الطلب",
    rejectedTitle: "لم تُقبل التعديلات المطلوبة",
    rejectedBody:
      "تبقى بيانات شركتك المعتمدة الحالية فعّالة. راجع السبب بالأسفل وصحّح التفاصيل ثم أعد الإرسال.",
    rejectedStatus: "مرفوض",
    partlyOverline: "مقبول جزئيًا",
    partlyTitle: "قُبل تعديلان ورُفض واحد",
    partlyBody:
      "وافقت هوتيليانا على رقم الهاتف والسجل التجاري. ورُفض الآيبان، لذا يبقى آيبانك الحالي فعّالًا.",
    partlyStatus: "٢ من ٣ مقبولة",
    decided: "اكتمل القرار",
    reference: "مرجع الطلب CHG-00042",
    appliedOverline: "طلب تعديل · ٣ تفاصيل",
    partlyAppliedOverline: "طلب تعديل · ٣ تفاصيل · ١ مرفوض",
    appliedTitle: "المعلومات المقبولة",
    rejectedListTitle: "المعلومات المطلوبة",
    partlyListTitle: "القرار لكل تفصيل",
    reasonOverline: "سبب هوتيليانا",
    reasonTitle: "سبب الرفض",
    approvedNoteFooter: "القيم المقبولة ظاهرة الآن في صفحة الاتفاقية.",
    rejectedNoteFooter:
      "سبب الرفض: المستند المُرسل لا يطابق السجل القانوني المسجّل للشركة.",
    partlyNoteFooter:
      "رقم الهاتف والسجل التجاري فعّالان الآن. ورُفض الآيبان - الخطاب لا يطابق الاسم القانوني المسجّل للشركة.",
    applied: "مقبول",
    notApplied: "مرفوض",
    timelineOverline: "الحالة",
    timelineTitle: "مسار المراجعة",
    submitted: "أُرسل",
    submittedNote: "مكتمل · ١٢ سبتمبر",
    review: "مراجعة هوتيليانا",
    reviewNote: "مكتمل · ١٣ سبتمبر",
    decision: "القرار لكل تفصيل",
    approvedNote: "مقبول",
    rejectedNote: "مرفوض",
    partlyNote: "مقبول جزئيًا",
    notified: "تم إبلاغ المورّد",
    notifiedNote: "مكتمل",
    viewRecord: "عرض سجل الشركة المحدّث",
    continueLibrary: "المتابعة إلى مكتبة الفنادق",
    returnAgreement: "العودة إلى الشركة والاتفاقية",
    editResubmit: "تعديل وإعادة إرسال",
    resubmitRejected: "أعد إرسال التفصيل المرفوض",
    newRequest: "إرسال طلب جديد",
  },
  requests: {
    overline: "المنشأة · الطلبات",
    title: "الطلبات",
    subtitle:
      "كل ما أرسلته إلى هوتيليانا - الوصول إلى الفنادق والفنادق الجديدة والغرف الجديدة وتعديلات الشركة. الصفوف التي تحتاج ردّك تظهر أولًا.",
    tab: "الطلبات",
    browseLibrary: "تصفّح مكتبة الفنادق",
    statWaiting: "بانتظار هوتيليانا",
    statWaitingNote: "عادةً يوم عمل واحد",
    statNeedsYou: "يحتاج ردّك",
    statNeedsYouNote: "أجب لإكمال المسار",
    statApproved: "مقبولة",
    statApprovedNote: "مرتبطة أو مُضافة",
    statRejected: "مرفوضة",
    statRejectedNote: "السبب في التفاصيل",
    statDecided: "صدر قرارها",
    statDecidedNote: "خلال ٣٠ يومًا",
    filterAll: "الكل",
    filterAccess: "الوصول إلى الفنادق",
    filterHotels: "فنادق جديدة",
    filterRooms: "غرف جديدة",
    filterCompany: "تعديلات الشركة",
    colRequest: "الطلب",
    colType: "النوع",
    colWhat: "المحتوى",
    colSent: "أُرسل",
    colStatus: "الحالة",
    colUpdate: "آخر تحديث",
    colAction: "الإجراء",
    showing: "عرض {shown} من {total} طلبات · الترتيب: ما يحتاج ردّك أولًا ثم الأقدم انتظارًا",
    footer:
      "قائمة واحدة لكل ما أرسلته إلى هوتيليانا. ولا يغيّر أي قرار بياناتك الحالية حتى يُعتمد.",
    emptyFooter:
      "لا شيء عليك الآن. سيصلك إشعار عندما تقرر هوتيليانا أو تحتاج شيئًا منك.",
    listOverline: "كل الطلبات",
    listTitle: "{count} طلبات",
    withdrawn: "سُحب الطلب",
    withdrawnNote: "أُلغيت المراجعة. ويمكنك طلبه من جديد متى شئت.",
    caseOpened: "فُتحت حالتك لدى هوتيليانا",
    kindAccess: "وصول إلى فندق",
    kindCompany: "تعديل بيانات الشركة",
    kindHotel: "فندق جديد",
    kindRoom: "غرفة جديدة",
    open: "فتح",
    empty: "لا توجد طلبات بعد.",
    statePending: "بالانتظار",
    stateNeedsYou: "يحتاج ردّك",
    stateApproved: "مقبول",
    stateLinked: "مرتبطة",
    stateNotApproved: "مرفوض",
    sent: "أُرسل {date}",
    decided: "صدر القرار {date}",
    drawerTimeline: "المسار",
    drawerDetails: "ما أرسلته",
    drawerNeeds: "ما تحتاجه هوتيليانا",
    drawerDecision: "القرار",
    finalNote: "هذا القرار نهائي لمدة ٩٠ يومًا.",
    respond: "إرسال المستند الناقص",
    goToHotel: "فتح الفندق",
    step1: "إرسال الطلب",
    step2: "مراجعة هوتيليانا",
    step3: "القرار",
    step4: "تم إبلاغك",
    waiting: "بالانتظار",
    inProgress: "جارية",
    complete: "مكتمل",
  },
  addHotel: {
    overline: "مكتبة الفنادق · إضافة فندق غير موجود",
    title: "إضافة فندق غير موجود",
    subtitle:
      "أدخل بيانات الفندق كما هي في الترخيص. نفحص المكتبة بحثًا عن التكرار أثناء كتابتك للاسم وتحديدك للموقع.",
    open: "إضافة فندق غير موجود",
    stepDetails: "بيانات الفندق",
    stepMedia: "الصور والمرافق",
    stepReview: "المراجعة",
    identityOverline: "هوية الفندق",
    identityTitle: "الاسم والفئة",
    locationOverline: "الموقع",
    locationTitle: "العنوان والخريطة",
    name: "اسم الفندق (إنجليزي) *",
    namePh: "مثال: Makkah Gate Hotel",
    nameAr: "اسم الفندق (عربي) *",
    nameArPh: "مثال: فندق بوابة مكة",
    licence: "رقم رخصة السياحة · اختياري",
    licenceHint: "أقوى وسيلة لاكتشاف التكرار",
    stars: "التصنيف بالنجوم *",
    starsPh: "مثال: ٤ نجوم · رسمي (وزارة السياحة)",
    descEn: "الوصف (إنجليزي) · اختياري",
    descEnPh: "وصف مختصر للفندق",
    descAr: "الوصف (عربي) · اختياري",
    descArPh: "وصف مختصر للفندق",
    country: "الدولة *",
    city: "المدينة *",
    area: "المنطقة · اختياري",
    areaPh: "اختر المنطقة",
    address: "العنوان *",
    addressPh: "الشارع والحي وتفاصيل المبنى",
    map: "الموقع على الخريطة *",
    mapPh: "الصق رابط خرائط Google",
    mapHint: "أو اضغط على الخريطة لتحديد الموقع بنفسك.",
    pinConfirmed: "تم تأكيد الموقع · المرسلات، مكة",
    required: "الحقول المعلّمة بـ * مطلوبة · تبقّى {count}",
    next: "المتابعة إلى الصور",
    nextMedia: "المتابعة إلى المراجعة",
    continueAnyway: "إنه فندق مختلف - تابع",
    back: "رجوع",
    backDetails: "العودة إلى بيانات الفندق",
    backMedia: "العودة إلى الصور والمرافق",
    duplicateTitleOne: "فندق واحد في المكتبة يشبه الفندق الذي تضيفه",
    duplicateTitleTwo: "فندقان في المكتبة يشبهان الفندق الذي تضيفه",
    duplicateTitleFew: "{n} فنادق في المكتبة تشبه الفندق الذي تضيفه",
    duplicateTitleMany: "{n} فندقًا في المكتبة يشبه الفندق الذي تضيفه",
    duplicateBody: "إنشاء نسخة مكررة يقسّم الفندق نفسه على سجلّين.",
    duplicateNote:
      "تابع فقط إن كان فندقًا مختلفًا فعلًا. تُجري هوتيليانا الفحص نفسه قبل الاعتماد، ويُرفض المكرر عندها.",
    matchNote: "الموقع يبعد {distance} عن موقعك · تطابق الاسم {match}",
    requestInstead: "اطلب الوصول إليه بدلًا من ذلك",
    view: "عرض",
    mediaOverline: "صور الفندق · {count} مرفوعة",
    mediaTitle: "صور الفندق",
    mediaSubtitle: "ارفع صورًا واضحة للفندق واختر كل مرفق متاح للنزلاء.",
    dropzone: "أفلت الصور هنا أو اختر الملفات",
    dropzoneHint:
      "٣ صور على الأقل · JPG أو PNG · حتى ١٠ ميجابايت لكل صورة · الأولى هي صورة الغلاف",
    mediaNote:
      "تجنّب الشعارات ولقطات الشاشة والزوايا المكررة. تبقى الصور قيد المراجعة حتى تعتمد هوتيليانا الفندق.",
    browse: "اختيار الملفات",
    addMore: "إضافة صور أخرى",
    added: "✓  أُضيفت {count} صور أخرى · {size}",
    remove: "إزالة",
    tryAgain: "أعد المحاولة",
    cancelUpload: "إلغاء",
    uploadSummary: "{count} ملفات · {detail}",
    uploaded: "تم الرفع",
    uploading: "جارٍ الرفع · {percent}٪",
    queued: "بانتظار الرفع",
    cover: "الغلاف",
    rights:
      "أؤكد أننا نملك حقوق هذه الصور أو نحوزها، ونسمح لهوتيليانا بعرضها على المنصة وقنوات الشركاء.",
    amenitiesOverline: "مرافق الفندق · {count} مختارة",
    amenitiesTitle: "المرافق المتاحة",
    amenitiesNote:
      "اختر المرافق المتاحة فعليًا للنزلاء فقط. قد تطلب هوتيليانا إثباتًا لأي مرفق.",
    amenities: "المرافق",
    reviewTitle: "مراجعة الطلب",
    reviewSubtitle: "راجع كل التفاصيل قبل إرسال الفندق إلى هوتيليانا للاعتماد.",
    reviewStep1: "الخطوة ١ · بيانات الفندق",
    reviewStep2: "الخطوة ٢ · الصور والمرافق",
    reviewMedia: "{images} صور · {amenities} مرافق",
    edit: "تعديل",
    fieldStars: "التصنيف بالنجوم",
    starsSource: "رسمي (وزارة السياحة)",
    fieldLicence: "رخصة السياحة",
    fieldCountry: "الدولة · المنطقة",
    fieldAddress: "العنوان",
    fieldMap: "الموقع على الخريطة",
    fieldDuplicate: "فحص التكرار",
    fieldDescEn: "الوصف (إنجليزي)",
    fieldDescAr: "الوصف (عربي)",
    duplicateSummary:
      "تابعت رغم وجود {count} فنادق مشابهة - Makkah Gate Towers (٩١٪) وBab Makkah (٨٢٪)",
    reviewLegal: "أؤكد أن هذه البيانات دقيقة بموجب اتفاقية المورّد السارية.",
    submit: "إرسال للاعتماد",
    sentOverline: "أُرسل إلى هوتيليانا",
    sentTitle: "الفندق لدى هوتيليانا",
    sentBody:
      "يمكنك متابعة القرار في صفحة الطلبات. وبمجرد الاعتماد يظهر الفندق في فنادقي ويمكنك إنشاء عقد توريد.",
    reference: "الطلب HOT-10391 · أُرسل اليوم",
    submittedJustNow: "أُرسل الآن",
    reviewHotel: "فندق بوابة مكة",
    viewRequests: "فتح الطلبات",
    backToLibrary: "العودة إلى مكتبة الفنادق",
    amenityList: [
      "واي فاي",
      "مواقف",
      "مطعم",
      "خدمة الغرف",
      "مسبح",
      "صالة رياضية",
      "نقل المطار",
      "غرف عائلية",
      "تسهيلات ذوي الإعاقة",
      "استقبال ٢٤ ساعة",
      "مصلى",
      "مغسلة",
    ],
  },
  addRoom: {
    open: "إنشاء غرفة",
    title: "إنشاء غرفة جديدة",
    subtitle:
      "تُرسل الغرفة إلى هوتيليانا للتحقق. لن تظهر في الدليل الرسمي ولا في أي عقد توريد قبل القبول.",
    name: "اسم الغرفة",
    namePh: "جناح عائلي",
    base: "الإشغال الأساسي",
    occupancy: "أقصى إشغال",
    occupancyPh: "٦",
    adults: "البالغون",
    adultsPh: "٤",
    children: "الأطفال",
    childrenPh: "٢",
    childAge: "أقصى عمر للطفل",
    childAgePh: "١٢",
    beds: "نوع السرير",
    bedsPh: "سريران كينج · كنبة",
    size: "مساحة الغرفة",
    sizePh: "٦٢ م²",
    view: "الإطلالة",
    viewPh: "الحرم",
    units: "عدد الوحدات في الفندق",
    unitsPh: "٤",

    images: "صور الغرفة",
    imagesHint:
      "أفلت صور الغرفة هنا أو اختر من جهازك. JPG أو PNG · حتى ١٠ ميجابايت للصورة · أول صورة هي الغلاف.",
    similarTitle: "توجد غرفة مشابهة بالفعل",
    similarBody:
      "«جناح عائلي» مسجّلة بمساحة ٦٢ م² وبنفس الأسرّة. تابع فقط إن كانت غرفة مختلفة.",
    similarContinue: "إنها غرفة مختلفة",
    submit: "إرسال لمراجعة هوتيليانا",
    sentTitle: "أُرسلت الغرفة للتحقق",
    sentBody: "يمكنك متابعة القرار من صفحة الطلبات.",
    pending: "بانتظار التحقق",
  },
  libraryOverlay: {
    quickView: "عرض سريع",
    quickOverline: "فندق في المكتبة",
    hotelianaId: "معرّف هوتيليانا",
    quickRooms: "الغرف المسجّلة",
    quickAmenities: "الخدمات",
    quickNote:
      "هذا الفندق مملوك وموثّق من هوتيليانا. اطلب الوصول لبيعه تحت اتفاقيتك.",
    requestOne: "طلب الوصول",
    confirmTitle: "طلب الوصول إلى {count} فنادق",
    confirmBody:
      "تراجع هوتيليانا العلاقة بين شركتك وكل فندق قبل منح الوصول.",
    confirmNext: "ما سيحدث بعد ذلك",
    confirmStep1: "يُرسل الآن — ويُسجّل باسم المستخدم ووقت الإرسال",
    confirmStep2: "تراجع هوتيليانا العلاقة (عادةً يومَي عمل)",
    confirmStep3: "تظهر الفنادق المقبولة في فنادقي جاهزة لعقد توريد",
    confirmSubmit: "إرسال الطلب",
    sentTitle: "تم إرسال الطلب",
    sentBody: "{count} فنادق الآن عند هوتيليانا. تابع القرار من صفحة الطلبات.",
    openRequests: "فتح الطلبات",
    keepBrowsing: "متابعة التصفح",
    bookingType: "نوع تأكيد الحجز",
    bookingTypeHint:
      "اختر طريقة تأكيد الحجوزات لهذا الفندق. تطبّقها هوتيليانا بعد منح الوصول.",
    instant: "تأكيد فوري",
    instantHint: "تُأكَّد الحجوزات فورًا من الأماكن المتاحة لك.",
    onRequest: "عند الطلب",
    onRequestHint: "كل حجز ينتظر تأكيدك قبل أن يصبح نهائيًا.",
    bookingTypeRequired: "اختر نوع تأكيد الحجز للمتابعة.",

  },
  docViewer: {
    overline: "مستند شركة موثّق",
    body: "\u0645\u0644\u062e\u0635 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u0645\u0633\u062c\u0651\u0644. \u0627\u0637\u0644\u0628 \u0627\u0633\u062a\u0628\u062f\u0627\u0644\u0627\u064b \u0644\u0625\u0631\u0633\u0627\u0644 \u0646\u0633\u062e\u0629 \u0623\u062d\u062f\u062b \u0625\u0644\u0649 \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627.",
    issueDate: "\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0625\u0635\u062f\u0627\u0631",
    expiryDate: "\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0627\u0646\u062a\u0647\u0627\u0621",
    statusLabel: "\u0627\u0644\u062d\u0627\u0644\u0629",
    valid: "\u0633\u0627\u0631\u064d",
    expiring: "\u0639\u0644\u0649 \u0648\u0634\u0643 \u0627\u0644\u0627\u0646\u062a\u0647\u0627\u0621",
    currentFile: "\u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u062d\u0627\u0644\u064a",
    viewOnly:
      "\u0645\u0633\u062a\u0646\u062f \u0644\u0644\u0639\u0631\u0636 \u0641\u0642\u0637. \u0648\u0623\u064a \u0627\u0633\u062a\u0628\u062f\u0627\u0644 \u064a\u062d\u062a\u0627\u062c \u0637\u0644\u0628 \u062a\u063a\u064a\u064a\u0631 \u0648\u0645\u0648\u0627\u0641\u0642\u0629 \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627.",
    expiryNote:
      "\u062a\u064f\u0631\u0633\u0644 \u062a\u0630\u0643\u064a\u0631\u0627\u062a \u0627\u0644\u0627\u0646\u062a\u0647\u0627\u0621 \u0642\u0628\u0644 \u0669\u0660 \u00b7 \u0663\u0660 \u00b7 \u0667 \u064a\u0648\u0645\u064b\u0627 \u0645\u0646 \u0627\u0644\u062a\u0627\u0631\u064a\u062e. \u062c\u062f\u0651\u062f\u0647 \u0628\u0637\u0644\u0628 \u062a\u063a\u064a\u064a\u0631 \u0642\u0628\u0644 {date} \u0644\u064a\u0628\u0642\u0649 \u062d\u0633\u0627\u0628\u0643 \u0641\u0639\u0651\u0627\u0644\u0627\u064b.",
    requestReplacement: "\u0637\u0644\u0628 \u0627\u0633\u062a\u0628\u062f\u0627\u0644",
  },
  select: {
    placeholder: "اختر",
    multiPlaceholder: "اختر واحدًا أو أكثر",
    tagsPlaceholder: "اكتب ثم اضغط Enter",
    search: "بحث",
    noResults: "لا نتائج مطابقة",
    selectedCount: "{count} محدّد",
    clear: "مسح",
    remove: "إزالة",
    addTag: 'إضافة "{value}"',
    typeToSearch: "اكتب {count} أحرف على الأقل",
    loading: "جارٍ التحميل…",
  },
  toast: {
    accessRequested: "تم إرسال طلب الوصول",
    accessRequestedDesc: "{hotels} الآن قيد المراجعة لدى هوتيليانا.",
    changesSubmitted: "تم إرسال طلب التعديل",
    changesSubmittedDesc: "سيصلك القرار خلال يومي عمل.",
    hotelSubmitted: "تم إرسال الفندق للموافقة",
    hotelSubmittedDesc: "سنؤكد لك بعد إضافة الفندق إلى المكتبة.",
    roomSubmitted: "تم إرسال الغرفة للموافقة",
    roomSubmittedDesc: "ستظهر الغرفة بعد موافقة هوتيليانا.",
    signedIn: "تم تسجيل الدخول",
    codeSent: "تم قبول رمز التحقق",
    resetSent: "تم إرسال رابط الاستعادة",
    passwordUpdated: "تم تحديث كلمة المرور",
    photosAdded: "تم رفع الصور",
    working: "جارٍ الحفظ…",
    failed: "حدث خطأ ما، حاول مرة أخرى.",
  },

  contracts: {
    tab: "عقود توريد الفنادق",
    overline: "المنشأة · عقود التوريد",
    title: "عقود التوريد",
    subtitle: "كل عقود التوريد في فنادقك المرتبطة، مع حالة البيع لكل عقد.",
    empty: "لا توجد عقود أسعار بعد. اربط فندقًا أولًا ثم أنشئ عقدًا.",
    create: "إنشاء عقد توريد",
    continueDraft: "متابعة المسودة",
    open: "فتح العقد",
    hotel: "الفندق",
    period: "الفترة",
    model: "النموذج",
    state: "الحالة",
    count: "{count} عقود",
    allotment: "حجز مضمون",
    onRequest: "عند الطلب",
  },
};


