import { extraAr, extraEn } from "./dict-extra";
import { hotelAr, hotelEn } from "./dict-hotel";
import { contractAr, contractEn } from "./dict-contract";

export type Language = "en" | "ar";

const en = {
  common: {
    super_admin: "Super Admin",
    admin: "Admin",
    somethingWentWrong: "Something went wrong. Please try again.",
    brand: "Hoteliana",
    supplierPortal: "SUPPLIER PORTAL",
    supplierName: "Jewar Al-Safwah for Travel & Tourism",
    supplierShort: "Jewar Al-Safwah",
    langLabel: "العربية",
    signOut: "Sign out",
    cancel: "Cancel",
    close: "Close",
    done: "Done",
    readOnly: "Read only",
    backToAgreement: "Back to Company & agreement",
    backToEditRequest: "Back to edit request",
    backToMyHotels: "Back to My Hotels",
    continueToLibrary: "Continue to Hotel Library",
    reveal: "Reveal",
    hide: "Hide",
    preview: "Preview",
    downloadPdf: "Download PDF",
    notProvided: "Not provided · optional",
    needHelp: "Need help accessing your supplier account?",
    contactSupport: "Contact Hoteliana support",
    backToSignIn: "Back to sign in",
    nameEnLabel: "Name in English",
    nameEnPlaceholder: "Enter name in English",
    nameArLabel: "Name in Arabic",
    nameArPlaceholder: "Enter name in Arabic",
    arabicLettersNotAllowed: "Arabic letters are not allowed",
    englishLettersNotAllowed: "English letters are not allowed",
    usernameLabel: "Username",
    usernamePlaceholder: "Enter username",
    emailLabel: "Email",
    emailPlaceholder: "Enter email address",
    phoneNumberLabel: "Phone Number",
    phoneNumberPlaceholder: "Enter phone number",
    fieldRequired: "This field is required",
    invalidEmail: "Please enter a valid email address",
    confirmSelection: "Confirm Selection",
    noRolesSelected: "No roles selected",
  },
  nav: {
    gettingStarted: "Getting started",
    agreement: "Company & agreement",
    hotelLibrary: "Hotel Library",
    myHotels: "My Hotels",
    dashboard: "Dashboard",
    bookings: "Bookings",
    rateCalendar: "Rates & Availability",
    property: "Property",
    finance: "Finance",
    teamAccess: "Team & Access",
    showLabels: "Show labels",
    hideLabels: "Hide labels",
    search: "Search",
    language: "Language",
    notifications: "Notifications",
    comingSoon: "Available later in the rollout",
    profileName: "Abdullrahman",
  },
  account: {
    menu: "Account",
    profile: "Personal details",
    profileHint: "Name, job title, phone",
    password: "Change password",
    passwordHint: "Update your sign-in password",
    language: "Language",
    signOut: "Sign out",
    ownerLine: "Jewar Al-Safwah · Owner",
    ownerValue: "Registered company owner",
    companyMenu: "Company & agreement",
    companyHint: "legal profile, documents, v1.4 accepted",
    gettingStarted: "Getting started",
    gettingStartedHint: "4 steps · 1 done",
    cases: "Your cases",
    casesHint: "1 waiting on you · 1 in review",
    hotels: "My hotels",
    hotelsHint: "3 linked · 1 needs attention",
    signOutHint: "ends the session on this device",
    languageOverline: "LANGUAGE",
    languageEnglish: "English",
    languageEnglishHint: "in use now",
    languageArabic: "العربية",
    languageArabicHint: "right-to-left · coming soon",
    languageNote:
      "Switching the language flips the whole layout, not only the words. Numbers, dates and money keep the same format either way.",
    rowsPerPage: "Rows per page",
    overline: "ACCOUNT",
    profileTitle: "Personal details",
    profileSubtitle:
      "These details appear to your Hoteliana account manager and to selling agents when they contact you.",
    fullName: "Full name",
    jobTitle: "Job title",
    email: "Work email",
    emailNote: "Your work email is managed by Hoteliana and cannot be changed here.",
    phone: "Mobile number",
    save: "Save changes",
    saved: "Personal details saved.",
    languageTitle: "Interface language",
    languageSubtitle: "Applies to every screen of the portal on this device.",
    passwordTitle: "Change password",
    passwordSubtitle:
      "Use at least 8 characters. You will stay signed in on this device after the change.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    updatePassword: "Update password",
    passwordUpdated: "Password updated.",
    passwordShort: "The new password must be at least 8 characters.",
    passwordMismatch: "The new password and its confirmation are different.",
    passwordMissingCurrent: "Enter your current password.",
  },
  brandPanels: {
    signIn: {
      headline: "Your supply.\nOne clear operating view.",
      body: "Manage hotels, availability, booking decisions and settlements with Hoteliana - in one place, with every change visible to the agents who sell you.",
      proof: "Secure supplier access",
    },
    activation: {
      headline: "Welcome to\nHoteliana.",
      body: "Your account is ready. One password and you are in.",
      proof: "Invitation verified by Hoteliana   ·   Supplier: Jewar Al-Safwah",
    },
    activationExpired: {
      headline: "Welcome to\nHoteliana.",
      body: "This link is no longer valid. One request and you are back.",
      proof: "Invitation expired   \u00b7   Supplier: Jewar Al-Safwah",
    },
    activationRequested: {
      headline: "Welcome to\nHoteliana.",
      body: "We have asked Hoteliana for a fresh link.",
      proof: "Waiting on Hoteliana   \u00b7   Supplier: Jewar Al-Safwah",
    },
    activationActive: {
      headline: "Welcome to\nHoteliana.",
      body: "Your account is ready. Sign in and carry on.",
      proof: "Account active   \u00b7   Supplier: Jewar Al-Safwah",
    },
    recovery: {
      headline: "Back in\ntwo steps.",
      body: "We email you a link, you choose a new password. Links only go to the email Hoteliana has on file.",
      proof: "Secure supplier access   ·   Support: help@hoteliana.com",
    },
  },
  passwordRules: {
    length: "At least 8 characters",
    uppercase: "At least one uppercase letter",
    lowercase: "At least one lowercase letter",
    number: "At least one number",
    special: "At least one special character",
  },
  activate: {
    overline: "ACCOUNT ACTIVATION",
    title: "Create your password",
    subtitle:
      "Your supplier account was created by Hoteliana. Set a password to finish activating it.",
    email: "Work email",
    emailHint: "Set by Hoteliana - it cannot be changed here.",
    newPassword: "New password",
    newPasswordPh: "At least 8 characters",
    confirm: "Confirm password",
    confirmPh: "Repeat the password",
    submit: "Activate account",
    footerNote: "This invitation expires in 7 days.",
    footerLink: "Need a new one? Contact Hoteliana support",
    errorTitle: "Passwords don’t match",
    errorBody:
      "The new password meets the requirements, but the confirmation is different. Retype both.",
    expired: {
      overline: "INVITATION EXPIRED",
      title: "This invitation has expired",
      subtitle:
        "Invitations stay valid for 7 days. Your account is still waiting - ask Hoteliana to send a new link.",
      emailHint: "The new invitation goes to this address.",
      submit: "Request a new invitation",
      footerNote: "Hoteliana usually sends a new invitation within one working day.",
    },
    requested: {
      overline: "REQUEST SENT",
      title: "New invitation requested",
      subtitle:
        "Hoteliana was asked to send a new invitation to {email}. It usually arrives within one working day.",
      submit: "Back to sign in",
      footerNote: "Nothing arrived? Check your spam folder before asking again.",
    },
    already: {
      overline: "ALREADY ACTIVATED",
      title: "This account is already active",
      subtitle:
        "This invitation link was used on 12 September 2026. Sign in with the password you set then.",
      emailHint: "You sign in with this address.",
      submit: "Sign in",
      footerNote: "Forgot your password? Reset it from the sign-in screen.",
    },
  },
  login: {
    overline: "SECURE SUPPLIER SIGN IN",
    title: "Welcome back",
    email: "Work email",
    emailPh: "name@company.com",
    password: "Password",
    passwordPh: "Enter your password",
    forgot: "Forgot password?",
    submit: "Sign in",
    errorTitle: "Incorrect email or password",
    errorBody:
      "Check both and try again. {left} attempts left before sign-in locks for 15 minutes.",
    locked: {
      title: "Account temporarily locked",
      bannerTitle: "Sign-in is paused for 15 minutes",
      bannerBody:
        "There were 5 incorrect attempts. Try again after {time} - or reset your password now and sign in straight away.",
      reset: "Reset password",
    },
  },
  activateAccount: {
    confirmPassword: "Confirm Password",
    confirmPasswordPh: "Repeat the password",
    overline: "Account",
    title: "Activate Account",
    subtitle: "Set your password to activate your Hoteliana supplier portal account.",
    submit: "Activate Account",
  },
  twoFactor: {
    overline: "ONE MORE STEP",
    title: "Check your email",
    subtitle: "We sent a 6-digit code to {email}. It works for 10 minutes.",
    maskedEmail: "o•••••••@jewaralsafwah.com",
    label: "Verification code",
    helper: "Paste the whole code or type it - it checks itself once all 6 digits are in.",
    trust: "Trust this device for 30 days - skip the code here next time",
    submit: "Verify and sign in",
    tryAgain: "Try again",
    timer: "You can request a new code in {time}",
    resend: "Resend code",
    resendAfterError: "Resend a new code",
    errorTitle: "That code didn’t work",
    errorBody:
      "It may have expired or been mistyped. You have {left} more tries on this code - after that, request a new one below.",
    sentTitle: "New code sent",
    sentBody: "Check {email}. The earlier code no longer works.",
    hint: "Demo code: 123456",
  },
  forgot: {
    overline: "PASSWORD RECOVERY",
    title: "Reset your password",
    subtitle:
      "Enter the work email on your supplier account. We will send a link that works for 30 minutes.",
    email: "Work email",
    emailPh: "name@company.com",
    submit: "Send reset link",
    sent: {
      overline: "CHECK YOUR EMAIL",
      title: "Reset link sent",
      subtitle:
        "If {email} has a supplier account, a link is on its way. It works once, for 30 minutes - check the spam folder too.",
      again: "Didn’t get it? Send another link",
      open: "Open the reset screen",
      verifyAndReset: "Verify your email and reset password",
    },
    expired: {
      overline: "RESET LINK EXPIRED",
      title: "This reset link no longer works",
      subtitle:
        "Password reset links work once and only for 30 minutes. Your account is fine - ask for a new link, it takes a few seconds.",
      submit: "Send a new link",
    },
  },
  reset: {
    overline: "PASSWORD RECOVERY",
    title: "Choose a new password",
    subtitle: "For {email}.",
    newPassword: "New password",
    newPasswordPh: "At least 8 characters",
    confirm: "Confirm password",
    confirmPh: "Repeat the password",
    sessions: "Saving signs you out on every other device.",
    submit: "Save password",
    footerNote: "This link works once.",
    mismatch: "Passwords don’t match - retype the password in both fields.",
    errorTitle: "Passwords don’t match",
    errorBody:
      "The new password meets the requirements, but the confirmation is different. Retype both.",
  },
  notMe: {
    sent: {
      overline: "SECURE YOUR ACCOUNT",
      title: "Take the account back",
      subtitle:
        "Someone else changed your password. We sent a reset link to {email} - open it on a device you trust. The new password replaces theirs, and nothing on your account changes until you choose it.",
      submit: "Open the link from the email",
      again: "Didn’t get it? Send another link",
    },
    choose: {
      overline: "SECURE YOUR ACCOUNT",
      title: "Choose a new password",
      info: "Next you see every device that was signed in, and you remove the ones that are not yours.",
    },
    devices: {
      overline: "NEW PASSWORD SAVED",
      title: "Where your account is signed in",
      subtitle:
        "Three devices had this account open. Remove the ones that are not yours - they are signed out at once and cannot come back without the new password.",
      submit: "Sign out the other {count} devices",
      footerNote: "The sign-out and the password change are both in the activity log.",
      thisDevice: "This device",
      notYou: "Not you",
      unknown: "Unknown",
      signedOut: "Signed out",
      list: [
        {
          name: "Chrome on Windows · Riyadh",
          meta: "Where you are now · 10:18",
        },
        {
          name: "Safari on iPhone · Jeddah",
          meta: "Changed the password · today 10:12",
        },
        { name: "Edge on Windows · Cairo", meta: "Last active 3 days ago" },
      ],
    },
    secured: {
      overline: "ACCOUNT SECURED",
      title: "Only this device is signed in",
      subtitle:
        "The iPhone in Jeddah and the laptop in Cairo were signed out and cannot come back without the new password.",
      submit: "Continue to the portal",
    },
  },
  gettingStarted: {
    overline: "GETTING STARTED",
    title: "Welcome, Jewar Al-Safwah",
    subtitle:
      "Your account is active. Eight steps take you from activation to your first live hotel - in this order.",
    stats: {
      account: {
        label: "ACCOUNT",
        value: "Active",
        note: "Access verified · 2FA on",
      },
      agreement: {
        label: "SUPPLIER AGREEMENT",
        value: "v1.3",
        note: "Waiting for your acceptance",
      },
      hotels: {
        label: "HOTELS",
        value: "0 linked",
        note: "Select hotels to begin",
      },
    },
    cardOverline: "FIRST SETUP · 8 STEPS",
    cardTitle: "Getting started",
    progress: "{done} of {total} complete",
    owner: "You",
    steps: {
      one: {
        title: "Account activated",
        body: "Password set and email verification enabled.",
        owner: "You",
        badge: "Complete",
      },
      two: {
        title: "Review company profile",
        body: "Check the legal profile Hoteliana registered. It is read only - corrections go through a change request.",
        owner: "You",
        badge: "Next action",
      },
      three: {
        title: "Review & accept the Supplier Agreement",
        body: "Version 1.3 · accepted once, by someone authorised to sign for the company.",
        owner: "You · authorised signer",
        badge: "Up next",
      },
      four: {
        title: "Check compliance documents",
        body: "Hoteliana registers your commercial registration, tax certificate and tourism licence. Request a change if anything is wrong.",
        owner: "Hoteliana registers · you check",
        badge: "Up next",
      },
      five: {
        title: "Select / request hotels",
        body: "Choose hotels from the library and ask to supply them. Hoteliana decides, usually within 2 working days.",
        owner: "You request · Hoteliana approves",
        badge: "Up next",
      },
      six: {
        title: "Create your first supply contract",
        body: "Unlocks once a hotel is approved.",
        owner: "You",
        badge: "Locked",
      },
      seven: {
        title: "Set rates & availability",
        body: "Seasons, prices, allotment and restrictions live inside the contract.",
        owner: "You",
        badge: "Locked",
      },
      eight: {
        title: "Go live",
        body: "Publish the contract - agents can book.",
        owner: "You",
        badge: "Locked",
      },
    },
    footnote: "Steps 6-8 unlock once at least one hotel is approved.",
    next: {
      overline: "NEXT BEST ACTION",
      title: "Review your company profile",
      body: "Confirm the legal profile and compliance documents Hoteliana registered, then accept the Supplier Agreement.",
      cta: "Review company profile",
      note: "Read only · takes about 2 minutes",
    },
  },
  agreement: {
    overline: "PROPERTY · COMPANY & AGREEMENT",
    title: "Company & agreement",
    subtitle:
      "Your legal profile, compliance documents and your commercial agreement with Hoteliana. Hoteliana keeps these; you request changes.",
    changePending: "Change pending",
    newVersion: {
      title: "A new agreement version is waiting for your acceptance",
      body: "Version 1.4 · published by Hoteliana 15 Sep 2026 · changes: settlement terms and cancellation clause. Accept by 30 Sep - after that, publishing contracts is paused until it is accepted. Version 1.3 stays in force until then.",
      cta: "Review & accept",
      ctaOwnerOnly: "Review & send to the Owner",
    },
    acceptedBanner:
      "Version 1.4 accepted · your acceptance record is stored below and a signed copy was sent to your registered email.",
    pending: {
      title: "One change request is with Hoteliana",
      body: "CHG-00042 · phone number, bank IBAN and commercial registration · sent 12 Sep. Those three details are locked until a decision; everything else can still be requested · usually decided within 2 working days.",
      cta: "See in Requests",
    },
    company: {
      overline: "SUPPLIER LEGAL PROFILE",
      title: "Registered legal information",
      legalName: "Legal company name",
      country: "Country",
      city: "City",
      countryCity: "Saudi Arabia · Makkah",
      phone: "Phone number",
      email: "Email address",
      cr: "Commercial registration",
      tax: "Tax certificate",
      license: "Tourism license",
      guarantee: "Bank guarantee letter",
      owner: "Company owner",
      ownerContact: "Owner phone · email",
    },
    supplier: {
      overline: "OWNER, BANKING & CONTRACT",
      title: "Authorized supplier records",
      iban: "Bank IBAN",
      ownerName: "Company owner name",
      ownerPhone: "Owner phone number",
      ownerEmail: "Owner email",
      ownerId: "Company owner ID",
      contract: "Supplier contract",
      contractEnd: "Contract end date",
      guarantee: "Bank guarantee letter",
      guaranteeValue: "Not provided · optional - add it with a change request",
    },
    documents: {
      overline: "COMPLIANCE DOCUMENTS",
      title: "Licences and certificates",
      document: "DOCUMENT",
      issued: "ISSUED",
      expires: "EXPIRES",
      status: "STATUS",
      more: "",
      available: "AVAILABLE",
      /** UI 01.6 — a document reads as valid, or as running out. */
      valid: "Valid",
      expiring: "Expiring soon",
      view: "View",
      note: "You are notified 90, 30 and 7 days before a document expires. An expired document pauses new supply contracts until a replacement is approved.",
    },
    contract: {
      overline: "HOTELIANA SUPPLIER AGREEMENT · COMMERCIAL",
      title: "Version {version} · in force",
      history: "Version history",
      term: "Term",
      model: "Inventory model",
      settlement: "Settlement terms",
      currency: "Currency",
      file: "Agreement file",
      acceptedBy: "Accepted by",
      acceptedAt: "Accepted at",
      record: "Acceptance record",
      recordValue: "Recorded by Hoteliana · IP and device kept per policy",
      previous: "Previous version",
      note: "The agreement is owned by Hoteliana. A new version is never applied silently - it is published, you review it, and you accept it. Bookings keep the version in force when they were confirmed.",
    },
    accept: {
      overline: "HOTELIANA SUPPLIER AGREEMENT · VERSION 1.4",
      title: "Review and accept the new version",
      titleOwnerOnly: "Only the Owner can accept this version",
      titleSent: "Sent to the Owner",
      meta: "Published 15 Sep 2026 · replaces v1.3 for new bookings only · accept by 30 Sep - after that, publishing contracts is paused.",
      changedOverline: "WHAT CHANGED SINCE V1.3",
      changes: [
        "Settlement terms: monthly statement · net 30 → net 21 days (you are paid 9 days sooner)",
        "Cancellation clause 7.2: no-show charge clarified as 100% of first night",
        "Annex B: supported inventory models updated · term renews 15 Sep 2026 - 14 Sep 2027",
      ],
      file: "Hoteliana_Supplier_Agreement_v1.4.pdf",
      pages: "6 pages",
      pagesHash: "6 pages · SHA-256 2b7c…e910",
      pagesOpened: "6 pages · ✓ Opened 15 Sep 10:14",
      read: "Read full document",
      declaration:
        "I am an authorized representative of Jewar Al-Safwah for Travel & Tourism and I accept version 1.4 of the Hoteliana Supplier Agreement on its behalf. Signing as Abdullrahman Najeh · Owner. This acceptance is recorded with my name, role, date, time and device.",
      ownerOnly:
        "You are signed in as Ahmed Saleh · Revenue manager. Accepting the agreement binds the company, so only the account Owner - Abdullrahman Najeh - can do it. Send it to him: he gets an email and a notification with a direct link.",
      sent: "Abdullrahman Najeh was emailed and notified just now. Nothing changes until he accepts. If v1.4 is not accepted by 30 Sep, publishing contracts pauses - you will see his acceptance in Version history.",
      gate: "Open the full document first - acceptance unlocks after you have seen it.",
      later: "Decide later",
      submit: "Accept version 1.4",
      sendToOwner: "Send to Abdullrahman (Owner)",
      done: "Done",
      accepted: "Version 1.4 accepted",
      sentToast: "Sent to the Owner",
    },
    strip: {
      title: "Need to update a registered detail or document?",
      body: "Submit a change request. Current records remain active until Hoteliana approves it.",
      view: "View requests",
      request: "Request changes",
    },
    history: {
      overline: "HOTELIANA SUPPLIER AGREEMENT",
      title: "Version history",
      body: "Every version Hoteliana published and who accepted it. Bookings keep the version in force at confirmation.",
      waiting: "Waiting",
      active: "Active",
      superseded: "Superseded",
    },
    download: {
      overline: "DOWNLOAD",
      title: "Contract download started",
      body: "Supplier_Agreement_v1.3.pdf is being saved to your device. The agreement stays read-only in the portal.",
      fileLabel: "File",
      fileValue: "Supplier_Agreement_v1.3.pdf",
      sizeLabel: "Size",
      sizeValue: "1.8 MB · PDF",
      statusLabel: "Status",
      statusValue: "Saved to your Downloads folder",
      done: "Done",
    },
    contractModal: {
      overline: "AGREEMENT SUMMARY · READ ONLY",
      file: "Supplier_Agreement_v1.3.pdf",
      meta: "Uploaded by Hoteliana on 1 September 2026 · 2-page summary",
      download: "Download PDF",
      party: "Hoteliana  ·  Jewar Al-Safwah for Travel & Tourism",
      summaryOverline: "HOTELIANA SUPPLIER AGREEMENT",
      clausesOverline: "CLAUSES 7 - 9 · SUMMARY",
      reference: "Contract reference",
      referenceValue: "HSA-2026-0142",
      term: "Term",
      termValue: "1 September 2026 - 31 August 2027",
      model: "Inventory model",
      modelValue: "Allotment",
      currency: "Currency",
      currencyValue: "SAR",
      settlement: "Settlement",
      settlementValue: "Monthly statement · net 30 days",
      noShow: "7.2 No-show",
      noShowValue: "100% of the first night",
      parity: "8.1 Rate parity",
      parityValue: "Not required",
      stopSell: "8.4 Stop sale",
      stopSellValue: "Allowed at any time, no notice",
      disputes: "9.1 Disputes",
      disputesValue: "Raised within 30 days of the statement",
      law: "9.3 Governing law",
      lawValue: "Kingdom of Saudi Arabia",
      note: "The remaining clauses are shown in the file. Hoteliana owns this document - nothing in it can be edited from the portal.",
      pager: "Page {page} of {total}",
      prevPage: "Previous page",
      nextPage: "Next page",
    },
  },
  changes: {
    overline: "COMPANY & AGREEMENT · CHANGE REQUEST",
    title: "Request company changes",
    subtitle:
      "Select only the details you need to change. One open request per detail - a detail already under review stays locked until Hoteliana decides.",
    lockedTitle: "{count} details are locked by request {id}",
    lockedBody:
      "Phone number, commercial registration and bank IBAN are with Hoteliana. Withdraw that request from Requests if you need to change them now. Everything else can be requested immediately.",
    lockedPill: "Pending · {id}",
    optional: "(optional)",
    step1Overline: "STEP 1 · CHOOSE DETAILS",
    step1Title: "What needs to change?",
    groups: {
      company: "COMPANY",
      documents: "DOCUMENTS",
      owner: "OWNER & BANKING",
    },
    note: {
      title: "The commercial agreement is not a data correction",
      body: "Term, settlement and inventory model belong to the Hoteliana Supplier Agreement - a new version, not a change request.",
    },
    step2Overline: "STEP 2 · NEW VALUES",
    step2OverlineSelected: "STEP 2 · {count} SELECTED DETAILS",
    step2Title: "Enter the replacement information",
    step2Body: "Only the selected details are sent to Hoteliana for review.",
    emptyTitle: "Nothing selected yet",
    emptyBody:
      "Tick a detail on the left. Its current value and a field for the new value appear here.",
    current: "Current",
    newValue: "New value",
    remove: "Remove",
    evidenceTitle: "A bank letter is required for an IBAN change",
    evidenceBody:
      "It must show the account holder name exactly as the registered legal company name.",
    uploadLetter: "Upload bank letter",
    uploadFile: "Upload replacement file",
    uploaded: "Ready to send",
    evidenceRule:
      "Document changes accept PDF, JPG or PNG up to 10 MB and need issue and expiry dates. The current approved file stays active until Hoteliana approves the replacement.",
    letter: {
      overline: "BANK IBAN · EVIDENCE",
      title: "Upload the bank letter",
      body: "Hoteliana needs a stamped letter from the bank to change the IBAN. A person checks it, so the details below must match - usually within 2 working days.",
      dropTitle: "Drop the letter here or browse",
      dropMeta: "PDF or JPG · up to 10 MB",
      choose: "Choose file",
      replace: "Replace file",
      sample: "bank-letter-sep-2026.pdf · 240 KB",
      remove: "Remove",
      rulesLabel: "THE LETTER MUST SHOW",
      rule1: "Account holder name exactly as the registered legal company name",
      rule2: "The full IBAN being registered",
      rule3: "Bank stamp and an issue date within the last 30 days",
      attach: "Attach letter",
    },
    reviewDisabled: "Review changes",
    review: "Review {count} changes",
  },
  review: {
    overline: "SUPPLIER AGREEMENT · CHANGE REQUEST · STEP 3",
    title: "Review requested changes",
    subtitle:
      "Check every new value before sending it to Hoteliana. Nothing changes until it is approved.",
    cardOverline: "{count} CHANGES",
    cardTitle: "Before and after",
    field: "FIELD",
    currentRecord: "CURRENT RECORD",
    requested: "REQUESTED VALUE",
    evidence: "EVIDENCE",
    notRequired: "Not required",
    note: "All unselected records remain unchanged. Phone number, commercial registration and bank IBAN stay locked under CHG-00042.",
    nextOverline: "APPROVAL PROCESS",
    nextTitle: "What happens next",
    steps: {
      one: {
        title: "Request submitted",
        body: "Hoteliana receives exactly the fields shown on this page.",
      },
      two: {
        title: "Review",
        body: "The operations team validates the data and documents.",
      },
      three: {
        title: "Decision",
        body: "Approved values replace the current record. Rejected changes do not.",
      },
      four: {
        title: "Notification",
        body: "You receive the decision and the rejection reason when applicable.",
      },
    },
    backToEdit: "Back to edit",
    submit: "Submit request",
  },
  submitted: {
    overline: "REQUEST SUBMITTED",
    title: "Your changes are under review",
    subtitle:
      "Hoteliana will approve or reject each detail. Your currently approved data stays active until a decision is made. Other details can still be requested separately.",
    statusLabel: "PENDING REVIEW",
    statusNote: "Submitted just now",
    cardOverline: "CHANGE REQUEST CHG-00043 · {count} DETAILS",
    cardTitle: "Submitted information",
    pending: "Pending",
    reference:
      "Request reference CHG-00043 · one open request per detail: these two are now locked until decided",
    timelineOverline: "STATUS",
    timelineTitle: "Review timeline",
    timeline: {
      submitted: "Submitted",
      submittedNote: "Complete · just now",
      review: "Hoteliana review",
      reviewNote: "In progress",
      decision: "Decision per detail",
      decisionNote: "Waiting",
      notified: "Supplier notified",
      notifiedNote: "Waiting",
    },
    note: "If rejected, the current approved record stays unchanged and the rejection reason is shown here.",
    withdrawModal: {
      overline: "WITHDRAW REQUEST",
      title: "Withdraw change request CHG-00043?",
      body: "Hoteliana stops reviewing it. {details} become editable again and your current approved values stay active. The confirmation link sent to finance@jewaralsafwah.com stops working. You can send the same files again later.",
      listLabel: "WHAT IS WITHDRAWN",
      valueItem: "{field} · new value",
      fileItem: "{field} · replacement file",
      keep: "Keep the request",
    },
    withdraw: "Withdraw request",
    returnToAgreement: "Return to Company & agreement",
  },
  library: {
    overline: "PROPERTY · HOTEL LIBRARY",
    title: "Hotel Library",
    subtitle:
      "Select an existing Hoteliana hotel and request access, or add a missing hotel for approval.",
    count: "{count} hotels",
    addMissing: "Add missing hotel",
    search: "Search hotels",
    searchPh: "Search by hotel name",
    country: "Country",
    city: "City",
    category: "Category",
    allStars: "All stars",
    allCities: "All cities",
    /** OV 02.9 — the panel that narrows the library. */
    filter: "Filter",
    relationship: "My status",
    allStatuses: "Any status",
    stars: "{count} stars",
    selectionHint: "{names} - nothing is sent until you confirm",
    clear: "Clear selection",
    requestAccess: "Request access",
    pendingTitle: "{requests} with Hoteliana",
    pendingBody: "Usually decided within 2 working days - you will get a notification either way.",
    viewRequests: "View requests",
    notFound: "Hotel not found? Add it and Hoteliana reviews it before it becomes available.",
    linkedNote: "Linked hotels are managed from My Hotels.",
    openInMyHotels: "Open in My Hotels",
    sentAgo: "Sent {days} days ago",
    sentJustNow: "Sent just now",
    viewRequest: "View request",
    rejectedReason: "Reason: Hoteliana could not confirm your contract with this hotel.",
    requestAgain: "Request again from 10 Dec",
    seeDecision: "See decision",
    contractsPaused: "All contracts paused",
    seeWhy: "See why",
    empty: "No hotels match these filters.",
    status: {
      available: "Available",
      requested: "Requested",
      linked: "Linked",
      notApproved: "Rejected",
      suspended: "Suspended",
    },
  },
  myHotels: {
    overline: "PROPERTY · MY HOTELS",
    title: "My Hotels",
    subtitle:
      "Approved hotels appear here. A hotel becomes bookable only through a published supply contract.",
    browseLibrary: "Browse Hotel Library",
    empty: "No linked hotels yet. Request access from the Hotel Library.",
    createContract: "Create supply contract",
    continueDraft: "Continue draft",
    openContract: "Open contract",
    reviewExpiring: "Review expiring contract",
    rateContracts: "Supply contracts",
    openProfile: "Open hotel profile",
    search: "Search",
    searchPh: "Search linked hotels",
    city: "City",
    allCities: "All cities",
    allCountries: "All Countries",
    contractState: "Contract state",
    anyState: "Any state",
    statNoContract: "NO SUPPLY CONTRACT",
    statNoContractNote: "Hotel with no contract yet",
    statDraft: "DRAFT CONTRACT",
    statDraftNote: "Not published yet",
    statSelling: "SELLING",
    statSellingNote: "{count} need attention",
    note: "A hotel starts selling once one of its supply contracts is published.",
    status: {
      selling: "Selling",
      draft: "Draft contract",
      needsAttention: "Needs attention",
      noContract: "No contract yet",
    },
  },
  profile: {
    overline: "MY HOTELS · HOTEL PROFILE",
    badge: "Approved & linked",
    detailsOverline: "OFFICIAL HOTELIANA PROFILE · READ ONLY",
    detailsTitle: "Hotel details",
    nameEn: "Hotel name (EN)",
    nameAr: "Hotel name (AR)",
    country: "Country",
    city: "City",
    district: "District",
    category: "Category",
    hoteliaId: "Hoteliana ID",
    checkIn: "Check-in",
    checkOut: "Check-out",
    distance: "Distance to Haram",
    roomsOverline: "ROOM CATALOGUE · READ ONLY",
    roomsTitle: "Rooms registered by Hoteliana",
    table: {
      room: "ROOM NAME",
      capacity: "BASE",
      occupancy: "MAX OCCUPANCY",
      adults: "ADULTS",
      children: "CHILDREN",
      childAge: "MAX CHILD AGE",
      extra: "EXTRA BEDS",
      beds: "BED TYPE",
      size: "ROOM SIZE",
      view: "VIEW",
      units: "UNITS",
      images: "IMAGES",
      status: "STATUS",
    },

    imagesCounter: "{count} images",
    note: "The hotel profile and room catalogue are owned by Hoteliana. Prices, seasons and inventory are set inside a supply contract.",
  },
};

const ar: typeof en = {
  common: {
    super_admin: "مدير النظام الأعلى",
    admin: "مدير",
    somethingWentWrong: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    brand: "هوتيليانا",
    supplierPortal: "بوابة المورّد",
    supplierName: "جوار الصفوة للسفر والسياحة",
    supplierShort: "جوار الصفوة",
    langLabel: "English",
    signOut: "تسجيل الخروج",
    cancel: "إلغاء",
    close: "إغلاق",
    done: "تم",
    readOnly: "للقراءة فقط",
    backToAgreement: "رجوع إلى الاتفاقية",
    backToEditRequest: "رجوع لتعديل الطلب",
    backToMyHotels: "رجوع إلى فنادقي",
    continueToLibrary: "المتابعة إلى مكتبة الفنادق",
    reveal: "إظهار",
    hide: "إخفاء",
    preview: "معاينة",
    downloadPdf: "تنزيل PDF",
    notProvided: "غير مُقدَّم · اختياري",
    needHelp: "تحتاج مساعدة للوصول إلى حساب المورّد؟",
    contactSupport: "تواصل مع دعم هوتيليانا",
    backToSignIn: "العودة لتسجيل الدخول",
    nameEnLabel: "الاسم بالإنجليزية",
    nameEnPlaceholder: "أدخل الاسم بالإنجليزية",
    nameArLabel: "الاسم بالعربية",
    nameArPlaceholder: "أدخل الاسم بالعربية",
    arabicLettersNotAllowed: "غير مسموح باستخدام الحروف العربية",
    englishLettersNotAllowed: "غير مسموح باستخدام الحروف الإنجليزية",
    usernameLabel: "اسم المستخدم",
    usernamePlaceholder: "أدخل اسم المستخدم",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "أدخل البريد الإلكتروني",
    phoneNumberLabel: "رقم الهاتف",
    phoneNumberPlaceholder: "أدخل رقم الهاتف",
    fieldRequired: "هذا الحقل مطلوب",
    invalidEmail: "يرجى إدخال بريد إلكتروني صالح",
    confirmSelection: "تأكيد الاختيار",
    noRolesSelected: "لم يتم اختيار أي أدوار",
  },
  nav: {
    gettingStarted: "البداية",
    agreement: "الشركة والاتفاقية",
    hotelLibrary: "مكتبة الفنادق",
    myHotels: "فنادقي",
    dashboard: "الرئيسية",
    bookings: "الحجوزات",
    rateCalendar: "الأسعار والإتاحة",
    property: "المنشأة",
    finance: "المالية",
    teamAccess: "الفريق والصلاحيات",
    showLabels: "إظهار الأسماء",
    hideLabels: "إخفاء الأسماء",
    search: "بحث",
    language: "اللغة",
    notifications: "التنبيهات",
    comingSoon: "سيتوفر في مرحلة لاحقة",
    profileName: "عبدالرحمن",
  },
  account: {
    menu: "الحساب",
    profile: "البيانات الشخصية",
    profileHint: "الاسم والمسمى الوظيفي والجوال",
    password: "تغيير كلمة المرور",
    passwordHint: "تحديث كلمة مرور الدخول",
    language: "اللغة",
    signOut: "تسجيل الخروج",
    ownerLine: "جوار الصفوة · المالك",
    ownerValue: "مالك الشركة المسجّل",
    companyMenu: "الشركة والاتفاقية",
    companyHint: "الملف النظامي والمستندات · قُبلت v1.4",
    gettingStarted: "البداية",
    gettingStartedHint: "٤ خطوات · واحدة تمت",
    cases: "حالاتك",
    casesHint: "واحدة بانتظارك · وواحدة قيد المراجعة",
    hotels: "فنادقي",
    hotelsHint: "٣ مرتبطة · وواحد يحتاج انتباهك",
    signOutHint: "تُنهي الجلسة على هذا الجهاز",
    languageOverline: "اللغة",
    languageEnglish: "English",
    languageEnglishHint: "المستخدمة الآن",
    languageArabic: "العربية",
    languageArabicHint: "من اليمين إلى اليسار · قريبًا",
    languageNote:
      "تبديل اللغة يقلب التخطيط كله لا الكلمات وحدها. وتبقى الأرقام والتواريخ والمبالغ بالصيغة نفسها في الحالتين.",
    rowsPerPage: "الصفوف في الصفحة",
    overline: "الحساب",
    profileTitle: "البيانات الشخصية",
    profileSubtitle: "تظهر هذه البيانات لمدير حسابك في هوتيليانا ولوكلاء البيع عند التواصل معك.",
    fullName: "الاسم الكامل",
    jobTitle: "المسمى الوظيفي",
    email: "بريد العمل",
    emailNote: "بريد العمل تديره هوتيليانا ولا يمكن تغييره من هنا.",
    phone: "رقم الجوال",
    save: "حفظ التغييرات",
    saved: "تم حفظ البيانات الشخصية.",
    languageTitle: "لغة الواجهة",
    languageSubtitle: "تُطبَّق على جميع شاشات البوابة على هذا الجهاز.",
    passwordTitle: "تغيير كلمة المرور",
    passwordSubtitle: "استخدم ٨ أحرف على الأقل. ستبقى مسجّل الدخول على هذا الجهاز بعد التغيير.",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    updatePassword: "تحديث كلمة المرور",
    passwordUpdated: "تم تحديث كلمة المرور.",
    passwordShort: "يجب أن تكون كلمة المرور الجديدة ٨ أحرف على الأقل.",
    passwordMismatch: "كلمة المرور الجديدة وتأكيدها غير متطابقين.",
    passwordMissingCurrent: "أدخل كلمة المرور الحالية.",
  },
  brandPanels: {
    signIn: {
      headline: "عروضك.\nفي مشهد تشغيلي واحد واضح.",
      body: "أدر الفنادق والإتاحة وقرارات الحجز والتسويات مع هوتيليانا — في مكان واحد، وكل تغيير ظاهر لوكلاء البيع.",
      proof: "وصول آمن للمورّد",
    },
    activation: {
      headline: "أهلًا بك في\nهوتيليانا.",
      body: "حسابك جاهز. كلمة مرور واحدة وتدخل.",
      proof: "دعوة موثّقة من هوتيليانا   ·   المورّد: جوار الصفوة",
    },
    activationExpired: {
      headline:
        "\u0623\u0647\u0644\u0627\u064b \u0628\u0643 \u0641\u064a\n\u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627.",
      body: "\u0644\u0645 \u064a\u0639\u062f \u0647\u0630\u0627 \u0627\u0644\u0631\u0627\u0628\u0637 \u0635\u0627\u0644\u062d\u064b\u0627. \u0637\u0644\u0628 \u0648\u0627\u062d\u062f \u0648\u062a\u0639\u0648\u062f.",
      proof:
        "\u0627\u0646\u062a\u0647\u062a \u0627\u0644\u062f\u0639\u0648\u0629   \u00b7   \u0627\u0644\u0645\u0648\u0631\u0651\u062f: \u062c\u0648\u0627\u0631 \u0627\u0644\u0635\u0641\u0648\u0629",
    },
    activationRequested: {
      headline:
        "\u0623\u0647\u0644\u0627\u064b \u0628\u0643 \u0641\u064a\n\u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627.",
      body: "\u0637\u0644\u0628\u0646\u0627 \u0645\u0646 \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627 \u0631\u0627\u0628\u0637\u064b\u0627 \u062c\u062f\u064a\u062f\u064b\u0627.",
      proof:
        "\u0628\u0627\u0646\u062a\u0638\u0627\u0631 \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627   \u00b7   \u0627\u0644\u0645\u0648\u0631\u0651\u062f: \u062c\u0648\u0627\u0631 \u0627\u0644\u0635\u0641\u0648\u0629",
    },
    activationActive: {
      headline:
        "\u0623\u0647\u0644\u0627\u064b \u0628\u0643 \u0641\u064a\n\u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627.",
      body: "\u062d\u0633\u0627\u0628\u0643 \u062c\u0627\u0647\u0632. \u0633\u062c\u0651\u0644 \u0627\u0644\u062f\u062e\u0648\u0644 \u0648\u062a\u0627\u0628\u0639.",
      proof:
        "\u0627\u0644\u062d\u0633\u0627\u0628 \u0641\u0639\u0651\u0627\u0644   \u00b7   \u0627\u0644\u0645\u0648\u0631\u0651\u062f: \u062c\u0648\u0627\u0631 \u0627\u0644\u0635\u0641\u0648\u0629",
    },
    recovery: {
      headline: "ارجع\nفي خطوتين.",
      body: "نرسل لك رابطًا، وتختار كلمة مرور جديدة. الروابط تُرسل فقط إلى البريد المسجّل لدى هوتيليانا.",
      proof: "وصول آمن للمورّد   ·   الدعم: help@hoteliana.com",
    },
  },
  passwordRules: {
    length: "8 أحرف على الأقل",
    uppercase: "حرف كبير واحد على الأقل",
    lowercase: "حرف صغير واحد على الأقل",
    number: "رقم واحد على الأقل",
    special: "رمز خاص واحد على الأقل",
  },
  activate: {
    overline: "تفعيل الحساب",
    title: "أنشئ كلمة مرورك",
    subtitle: "أنشأت هوتيليانا حساب المورّد الخاص بك. اضبط كلمة مرور لإتمام التفعيل.",
    email: "بريد العمل",
    emailHint: "مضبوط من هوتيليانا - لا يمكن تغييره هنا.",
    newPassword: "كلمة المرور الجديدة",
    newPasswordPh: "٨ أحرف على الأقل",
    confirm: "تأكيد كلمة المرور",
    confirmPh: "أعد كتابة كلمة المرور",
    submit: "تفعيل الحساب",
    footerNote: "تنتهي هذه الدعوة خلال ٧ أيام.",
    footerLink: "تحتاج دعوة جديدة؟ تواصل مع دعم هوتيليانا",
    errorTitle: "كلمتا المرور غير متطابقتين",
    errorBody: "كلمة المرور الجديدة مطابقة للشروط، لكن التأكيد مختلف. أعد كتابتهما.",
    expired: {
      overline: "انتهت صلاحية الدعوة",
      title: "انتهت صلاحية هذه الدعوة",
      subtitle:
        "تبقى الدعوة صالحة ٧ أيام. حسابك ما زال في الانتظار - اطلب من هوتيليانا إرسال رابط جديد.",
      emailHint: "ستصل الدعوة الجديدة إلى هذا العنوان.",
      submit: "اطلب دعوة جديدة",
      footerNote: "ترسل هوتيليانا الدعوة الجديدة عادةً خلال يوم عمل واحد.",
    },
    requested: {
      overline: "تم إرسال الطلب",
      title: "طُلبت دعوة جديدة",
      subtitle: "طُلب من هوتيليانا إرسال دعوة جديدة إلى {email}. تصل عادةً خلال يوم عمل واحد.",
      submit: "العودة لتسجيل الدخول",
      footerNote: "لم يصلك شيء؟ راجع مجلد البريد غير المرغوب قبل الطلب مجددًا.",
    },
    already: {
      overline: "الحساب مفعّل بالفعل",
      title: "هذا الحساب نشط بالفعل",
      subtitle:
        "استُخدم رابط الدعوة هذا في ١٢ سبتمبر ٢٠٢٦. سجّل الدخول بكلمة المرور التي ضبطتها وقتها.",
      emailHint: "تسجّل الدخول بهذا العنوان.",
      submit: "تسجيل الدخول",
      footerNote: "نسيت كلمة المرور؟ أعد ضبطها من شاشة تسجيل الدخول.",
    },
  },
  login: {
    overline: "دخول آمن للمورّد",
    title: "مرحبًا بعودتك",
    email: "بريد العمل",
    emailPh: "name@company.com",
    password: "كلمة المرور",
    passwordPh: "أدخل كلمة المرور",
    forgot: "نسيت كلمة المرور؟",
    submit: "تسجيل الدخول",
    errorTitle: "البريد أو كلمة المرور غير صحيحة",
    errorBody: "تحقّق من الاثنين وحاول مرة أخرى. تبقّت {left} محاولات قبل إقفال الدخول ١٥ دقيقة.",
    locked: {
      title: "الحساب مقفل مؤقتًا",
      bannerTitle: "تسجيل الدخول متوقف ١٥ دقيقة",
      bannerBody:
        "حدثت ٥ محاولات خاطئة. حاول بعد {time} - أو أعد ضبط كلمة المرور الآن وسجّل الدخول مباشرة.",
      reset: "إعادة ضبط كلمة المرور",
    },
  },
  activateAccount: {
    confirmPassword: "تأكيد كلمة المرور",
    confirmPasswordPh: "أعد إدخال كلمة المرور",
    overline: "الحساب",
    title: "تفعيل الحساب",
    subtitle: "قم بتعيين كلمة المرور لتفعيل حسابك في بوابة موردي Hoteliana.",
    submit: "تفعيل الحساب",
  },
  twoFactor: {
    overline: "خطوة أخيرة",
    title: "راجع بريدك",
    subtitle: "أرسلنا رمزًا من ٦ أرقام إلى {email}. صالح لمدة ١٠ دقائق.",
    maskedEmail: "o•••••••@jewaralsafwah.com",
    label: "رمز التحقق",
    helper: "الصق الرمز كاملًا أو اكتبه - يتحقق تلقائيًا بمجرد اكتمال الأرقام الستة.",
    trust: "الوثوق بهذا الجهاز ٣٠ يومًا - تخطَّ الرمز هنا في المرة القادمة",
    submit: "تحقّق وسجّل الدخول",
    tryAgain: "حاول مرة أخرى",
    timer: "يمكنك طلب رمز جديد بعد {time}",
    resend: "إرسال رمز جديد",
    resendAfterError: "أرسل رمزًا جديدًا",
    errorTitle: "الرمز غير مقبول",
    errorBody:
      "قد يكون منتهيًا أو مكتوبًا بشكل خطأ. لديك {left} محاولتان أخريان على هذا الرمز - بعدها اطلب رمزًا جديدًا بالأسفل.",
    sentTitle: "أُرسل رمز جديد",
    sentBody: "راجع {email}. الرمز السابق لم يعد صالحًا.",
    hint: "رمز التجربة: 123456",
  },
  forgot: {
    overline: "استعادة كلمة المرور",
    title: "أعد ضبط كلمة المرور",
    subtitle: "أدخل بريد العمل المسجّل على حساب المورّد. سنرسل رابطًا صالحًا لمدة ٣٠ دقيقة.",
    email: "بريد العمل",
    emailPh: "name@company.com",
    submit: "إرسال رابط الاستعادة",
    sent: {
      overline: "راجع بريدك",
      title: "تم إرسال رابط الاستعادة",
      subtitle:
        "إذا كان لدى {email} حساب مورّد، فالرابط في طريقه. يعمل مرة واحدة لمدة ٣٠ دقيقة - راجع مجلد البريد غير المرغوب أيضًا.",
      again: "لم يصلك؟ أرسل رابطًا آخر",
      open: "فتح شاشة كلمة المرور الجديدة",
      verifyAndReset: "تحقق من بريدك الإلكتروني وأعد تعيين كلمة المرور",
    },
    expired: {
      overline: "انتهت صلاحية الرابط",
      title: "رابط الاستعادة هذا لم يعد يعمل",
      subtitle:
        "تعمل روابط استعادة كلمة المرور مرة واحدة ولمدة ٣٠ دقيقة فقط. حسابك بخير - اطلب رابطًا جديدًا، الأمر يستغرق ثوانٍ.",
      submit: "أرسل رابطًا جديدًا",
    },
  },
  reset: {
    overline: "استعادة كلمة المرور",
    title: "اختر كلمة مرور جديدة",
    subtitle: "لحساب {email}.",
    newPassword: "كلمة المرور الجديدة",
    newPasswordPh: "٨ أحرف على الأقل",
    confirm: "تأكيد كلمة المرور",
    confirmPh: "أعد كتابة كلمة المرور",
    sessions: "الحفظ يسجّل خروجك من كل الأجهزة الأخرى.",
    submit: "حفظ كلمة المرور",
    footerNote: "يعمل هذا الرابط مرة واحدة.",
    mismatch: "كلمتا المرور غير متطابقتين - أعد كتابة كلمة المرور في الحقلين.",
    errorTitle: "كلمتا المرور غير متطابقتين",
    errorBody: "كلمة المرور الجديدة مطابقة للشروط، لكن التأكيد مختلف. أعد كتابتهما.",
  },
  notMe: {
    sent: {
      overline: "أمّن حسابك",
      title: "استعد حسابك",
      subtitle:
        "غيّر شخص آخر كلمة مرورك. أرسلنا رابط استعادة إلى {email} - افتحه من جهاز تثق به. كلمة المرور الجديدة تحل محل كلمته، ولا يتغيّر شيء في حسابك حتى تختارها.",
      submit: "افتح الرابط من البريد",
      again: "لم يصلك؟ أرسل رابطًا آخر",
    },
    choose: {
      overline: "أمّن حسابك",
      title: "اختر كلمة مرور جديدة",
      info: "بعدها ترى كل جهاز كان مسجّلًا للدخول، وتزيل الأجهزة التي ليست لك.",
    },
    devices: {
      overline: "حُفظت كلمة المرور الجديدة",
      title: "أين سُجّل الدخول إلى حسابك",
      subtitle:
        "ثلاثة أجهزة كان الحساب مفتوحًا عليها. أزل ما ليس لك - تُسجَّل خارجًا فورًا ولا يمكنها العودة دون كلمة المرور الجديدة.",
      submit: "تسجيل خروج الجهازين الآخرين ({count})",
      footerNote: "تسجيل الخروج وتغيير كلمة المرور كلاهما في سجل النشاط.",
      thisDevice: "هذا الجهاز",
      notYou: "ليس أنت",
      unknown: "غير معروف",
      signedOut: "سُجّل الخروج",
      list: [
        { name: "Chrome على Windows · الرياض", meta: "مكانك الآن · ١٠:١٨" },
        {
          name: "Safari على iPhone · جدة",
          meta: "غيّر كلمة المرور · اليوم ١٠:١٢",
        },
        { name: "Edge على Windows · القاهرة", meta: "آخر نشاط قبل ٣ أيام" },
      ],
    },
    secured: {
      overline: "الحساب مؤمّن",
      title: "هذا الجهاز وحده مسجّل الدخول",
      subtitle:
        "سُجّل خروج iPhone في جدة والحاسوب في القاهرة، ولا يمكنهما العودة دون كلمة المرور الجديدة.",
      submit: "المتابعة إلى البوابة",
    },
  },
  gettingStarted: {
    overline: "البداية",
    title: "أهلًا بك، جوار الصفوة",
    subtitle: "حسابك نشط. ثماني خطوات تنقلك من التفعيل إلى أول فندق يبيع - بهذا الترتيب.",
    stats: {
      account: {
        label: "الحساب",
        value: "نشط",
        note: "الوصول موثّق · التحقق بخطوتين مفعّل",
      },
      agreement: {
        label: "اتفاقية المورّد",
        value: "الإصدار 1.3",
        note: "بانتظار قبولك",
      },
      hotels: {
        label: "الفنادق",
        value: "لا فنادق مرتبطة",
        note: "اختر فنادق للبدء",
      },
    },
    cardOverline: "الإعداد الأول · ٨ خطوات",
    cardTitle: "البداية",
    progress: "{done} من {total} مكتملة",
    owner: "أنت",
    steps: {
      one: {
        title: "تم تفعيل الحساب",
        body: "ضُبطت كلمة المرور وفُعّل التحقق عبر البريد.",
        owner: "أنت",
        badge: "مكتملة",
      },
      two: {
        title: "راجع ملف الشركة",
        body: "تحقّق من الملف القانوني الذي سجّلته هوتيليانا. للقراءة فقط - التصحيحات تتم عبر طلب تعديل.",
        owner: "أنت",
        badge: "الخطوة التالية",
      },
      three: {
        title: "راجع واقبل اتفاقية المورّد",
        body: "الإصدار 1.3 · تُقبل مرة واحدة، من شخص مخوّل بالتوقيع باسم الشركة.",
        owner: "أنت · الموقّع المخوّل",
        badge: "قادمة",
      },
      four: {
        title: "تحقّق من مستندات الامتثال",
        body: "تسجّل هوتيليانا السجل التجاري والشهادة الضريبية ورخصة السياحة. اطلب تعديلًا إن كان هناك خطأ.",
        owner: "هوتيليانا تسجّل · وأنت تتحقّق",
        badge: "قادمة",
      },
      five: {
        title: "اختر الفنادق واطلبها",
        body: "اختر فنادق من المكتبة واطلب توريدها. تقرر هوتيليانا عادةً خلال يومي عمل.",
        owner: "أنت تطلب · هوتيليانا توافق",
        badge: "قادمة",
      },
      six: {
        title: "أنشئ أول عقد توريد",
        body: "يُفتح بمجرد اعتماد فندق واحد.",
        owner: "أنت",
        badge: "مقفلة",
      },
      seven: {
        title: "اضبط الأسعار والإتاحة",
        body: "المواسم والأسعار والحصص والقيود كلها داخل العقد.",
        owner: "أنت",
        badge: "مقفلة",
      },
      eight: {
        title: "ابدأ البيع",
        body: "انشر العقد - يصبح بإمكان الوكلاء الحجز.",
        owner: "أنت",
        badge: "مقفلة",
      },
    },
    footnote: "تُفتح الخطوات ٦-٨ بمجرد اعتماد فندق واحد على الأقل.",
    next: {
      overline: "أفضل خطوة تالية",
      title: "راجع ملف شركتك",
      body: "أكّد الملف القانوني ومستندات الامتثال التي سجّلتها هوتيليانا، ثم اقبل اتفاقية المورّد.",
      cta: "مراجعة ملف الشركة",
      note: "للقراءة فقط · يستغرق دقيقتين تقريبًا",
    },
  },
  agreement: {
    overline: "الممتلكات · الشركة والاتفاقية",
    title: "الشركة والاتفاقية",
    subtitle:
      "ملفك القانوني ومستندات الامتثال واتفاقيتك التجارية مع هوتيليانا. هوتيليانا تحتفظ بها، وأنت تطلب التعديل.",
    changePending: "تعديل قيد المراجعة",
    newVersion: {
      title: "هناك إصدار جديد من الاتفاقية بانتظار قبولك",
      body: "الإصدار 1.4 · نشرته هوتيليانا في ١٥ سبتمبر ٢٠٢٦ · التغييرات: شروط التسوية وبند الإلغاء. اقبله قبل ٣٠ سبتمبر - بعدها يتوقف نشر العقود حتى يُقبل. يبقى الإصدار 1.3 ساريًا حتى ذلك الحين.",
      cta: "المراجعة والقبول",
      ctaOwnerOnly: "المراجعة والإرسال إلى المالك",
    },
    acceptedBanner:
      "تم قبول الإصدار 1.4 · سجل قبولك محفوظ بالأسفل وأُرسلت نسخة موقّعة إلى بريدك المسجّل.",
    pending: {
      title: "هناك طلب تعديل واحد لدى هوتيليانا",
      body: "CHG-00042 · رقم الهاتف والآيبان والسجل التجاري · أُرسل في ١٢ سبتمبر. هذه التفاصيل الثلاثة مقفلة حتى صدور القرار، وما عداها يمكن طلبه الآن · يُبتّ عادةً خلال يومي عمل.",
      cta: "عرضه في الطلبات",
    },
    company: {
      overline: "الملف القانوني للمورّد",
      title: "المعلومات القانونية المسجّلة",
      legalName: "الاسم القانوني للشركة",
      country: "الدولة",
      city: "المدينة",
      countryCity: "السعودية · مكة",
      phone: "رقم الهاتف",
      email: "البريد الإلكتروني",
      cr: "السجل التجاري",
      tax: "الشهادة الضريبية",
      license: "رخصة السياحة",
      guarantee: "خطاب الضمان البنكي",
      owner: "مالك الشركة",
      ownerContact: "هاتف المالك · بريده",
    },
    supplier: {
      overline: "المالك والبيانات البنكية والعقد",
      title: "سجلات المورّد المعتمدة",
      iban: "الآيبان",
      ownerName: "اسم مالك الشركة",
      ownerPhone: "رقم هاتف المالك",
      ownerEmail: "بريد المالك",
      ownerId: "هوية مالك الشركة",
      contract: "عقد المورّد",
      contractEnd: "تاريخ انتهاء العقد",
      guarantee: "خطاب الضمان البنكي",
      guaranteeValue: "غير مُقدَّم · اختياري - أضفه عبر طلب تعديل",
    },
    documents: {
      overline: "مستندات الامتثال",
      title: "التراخيص والشهادات",
      document: "المستند",
      issued: "تاريخ الإصدار",
      expires: "تاريخ الانتهاء",
      status: "الحالة",
      more: "",
      valid: "سارٍ",
      expiring: "على وشك الانتهاء",
      view: "عرض",
      available: "متاح",
      note: "نُنبّهك قبل ٩٠ و٣٠ و٧ أيام من انتهاء أي مستند. المستند المنتهي يوقف عقود التوريد الجديدة حتى اعتماد بديل له.",
    },
    contract: {
      overline: "اتفاقية مورّد هوتيليانا · تجاري",
      title: "الإصدار {version} · ساري",
      history: "سجل الإصدارات",
      term: "المدة",
      model: "نموذج المخزون",
      settlement: "شروط التسوية",
      currency: "العملة",
      file: "ملف الاتفاقية",
      acceptedBy: "قبلها",
      acceptedAt: "وقت القبول",
      record: "سجل القبول",
      recordValue: "مسجّل لدى هوتيليانا · يُحفظ عنوان IP والجهاز وفق السياسة",
      previous: "الإصدار السابق",
      note: "الاتفاقية مملوكة لهوتيليانا. لا يُطبَّق أي إصدار جديد بصمت - يُنشر، وتراجعه، وتقبله. وتحتفظ الحجوزات بالإصدار الساري وقت تأكيدها.",
    },
    accept: {
      overline: "اتفاقية مورّد هوتيليانا · الإصدار 1.4",
      title: "راجع الإصدار الجديد واقبله",
      titleOwnerOnly: "المالك وحده يمكنه قبول هذا الإصدار",
      titleSent: "أُرسل إلى المالك",
      meta: "نُشر في ١٥ سبتمبر ٢٠٢٦ · يحل محل 1.3 للحجوزات الجديدة فقط · اقبله قبل ٣٠ سبتمبر - بعدها يتوقف نشر العقود.",
      changedOverline: "ما الذي تغيّر منذ الإصدار 1.3",
      changes: [
        "شروط التسوية: كشف شهري · من صافي ٣٠ إلى صافي ٢١ يومًا (تُدفع لك المبالغ أسرع بـ٩ أيام)",
        "بند الإلغاء 7.2: توضيح رسوم عدم الحضور بنسبة ١٠٠٪ من الليلة الأولى",
        "الملحق ب: تحديث نماذج المخزون المدعومة · تتجدد المدة ١٥ سبتمبر ٢٠٢٦ - ١٤ سبتمبر ٢٠٢٧",
      ],
      file: "Hoteliana_Supplier_Agreement_v1.4.pdf",
      pages: "٦ صفحات",
      pagesHash: "٦ صفحات · SHA-256 2b7c…e910",
      pagesOpened: "٦ صفحات · ✓ فُتح ١٥ سبتمبر ١٠:١٤",
      read: "قراءة المستند كاملًا",
      declaration:
        "أنا ممثل مخوّل عن جوار الصفوة للسفر والسياحة وأقبل الإصدار 1.4 من اتفاقية مورّد هوتيليانا نيابةً عنها. أوقّع بصفتي عبدالرحمن ناجح · المالك. يُسجَّل هذا القبول باسمي ودوري والتاريخ والوقت والجهاز.",
      ownerOnly:
        "أنت مسجّل الدخول باسم أحمد صالح · مدير الإيرادات. قبول الاتفاقية يُلزم الشركة، لذا لا يقبلها إلا مالك الحساب - عبدالرحمن ناجح. أرسلها إليه: سيصله بريد وإشعار برابط مباشر.",
      sent: "أُرسل بريد وإشعار إلى عبدالرحمن ناجح للتو. لا يتغيّر شيء حتى يقبل. وإن لم يُقبل الإصدار 1.4 قبل ٣٠ سبتمبر يتوقف نشر العقود - وسترى قبوله في سجل الإصدارات.",
      gate: "افتح المستند كاملًا أولًا - يُفتح القبول بعد اطلاعك عليه.",
      later: "أقرر لاحقًا",
      submit: "قبول الإصدار 1.4",
      sendToOwner: "إرسال إلى عبدالرحمن (المالك)",
      done: "تم",
      accepted: "تم قبول الإصدار 1.4",
      sentToast: "أُرسل إلى المالك",
    },
    strip: {
      title: "تحتاج تحديث بيان مسجّل أو مستند؟",
      body: "أرسل طلب تعديل. تبقى السجلات الحالية نشطة حتى توافق هوتيليانا عليه.",
      view: "عرض الطلبات",
      request: "طلب تعديل",
    },
    history: {
      overline:
        "\u0627\u062a\u0641\u0627\u0642\u064a\u0629 \u0645\u0648\u0631\u0651\u062f\u064a \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627",
      title: "\u0633\u062c\u0644 \u0627\u0644\u0625\u0635\u062f\u0627\u0631\u0627\u062a",
      body: "\u0643\u0644 \u0625\u0635\u062f\u0627\u0631 \u0646\u0634\u0631\u062a\u0647 \u0647\u0648\u062a\u064a\u0644\u064a\u0627\u0646\u0627 \u0648\u0645\u0646 \u0642\u0628\u0644\u0647. \u0648\u062a\u062d\u062a\u0641\u0638 \u0627\u0644\u062d\u062c\u0648\u0632\u0627\u062a \u0628\u0627\u0644\u0625\u0635\u062f\u0627\u0631 \u0627\u0644\u0633\u0627\u0631\u064a \u0639\u0646\u062f \u062a\u0623\u0643\u064a\u062f\u0647\u0627.",
      waiting: "\u0628\u0627\u0646\u062a\u0638\u0627\u0631",
      active: "\u0633\u0627\u0631\u064d",
      superseded: "\u0645\u0633\u062a\u0628\u062f\u0644",
    },
    download: {
      overline: "التنزيل",
      title: "بدأ تنزيل العقد",
      body: "يُحفظ ملف Supplier_Agreement_v1.3.pdf إلى جهازك. وتبقى الاتفاقية للقراءة فقط داخل البوابة.",
      fileLabel: "الملف",
      fileValue: "Supplier_Agreement_v1.3.pdf",
      sizeLabel: "الحجم",
      sizeValue: "١٫٨ م.ب · PDF",
      statusLabel: "الحالة",
      statusValue: "حُفظ في مجلد التنزيلات",
      done: "تم",
    },
    contractModal: {
      overline: "ملخّص الاتفاقية · للقراءة فقط",
      file: "Supplier_Agreement_v1.3.pdf",
      meta: "رفعتها هوتيليانا في ١ سبتمبر ٢٠٢٦ · ملخّص من صفحتين",
      download: "تنزيل PDF",
      party: "هوتيليانا  ·  جوار الصفوة للسفر والسياحة",
      summaryOverline: "اتفاقية مورّدي هوتيليانا",
      clausesOverline: "البنود ٧ - ٩ · ملخّص",
      reference: "مرجع العقد",
      referenceValue: "HSA-2026-0142",
      term: "المدة",
      termValue: "١ سبتمبر ٢٠٢٦ - ٣١ أغسطس ٢٠٢٧",
      model: "نموذج المخزون",
      modelValue: "حجز مضمون",
      currency: "العملة",
      currencyValue: "SAR",
      settlement: "التسوية",
      settlementValue: "كشف شهري · صافي ٣٠ يومًا",
      noShow: "٧.٢ عدم الحضور",
      noShowValue: "١٠٠٪ من الليلة الأولى",
      parity: "٨.١ تكافؤ الأسعار",
      parityValue: "غير مطلوب",
      stopSell: "٨.٤ إيقاف البيع",
      stopSellValue: "مسموح في أي وقت، دون إشعار",
      disputes: "٩.١ الاعتراضات",
      disputesValue: "تُرفع خلال ٣٠ يومًا من الكشف",
      law: "٩.٣ القانون الحاكم",
      lawValue: "المملكة العربية السعودية",
      note: "بقية البنود موجودة في الملف. هوتيليانا تملك هذا المستند - لا يمكن تعديل أي شيء فيه من البوابة.",
      pager: "صفحة {page} من {total}",
      prevPage: "الصفحة السابقة",
      nextPage: "الصفحة التالية",
    },
  },
  changes: {
    overline: "الشركة والاتفاقية · طلب تعديل",
    title: "طلب تعديل بيانات الشركة",
    subtitle:
      "اختر البيانات التي تريد تعديلها فقط. طلب مفتوح واحد لكل بيان - والبيان الذي تجري مراجعته يبقى مقفلًا حتى تقرر هوتيليانا.",
    lockedTitle: "{count} بيانات مقفلة بالطلب {id}",
    lockedBody:
      "رقم الهاتف والسجل التجاري والآيبان لدى هوتيليانا. اسحب ذلك الطلب من صفحة الطلبات إن احتجت تعديلها الآن. وما عداها يمكن طلبه فورًا.",
    lockedPill: "قيد المراجعة · {id}",
    optional: "(اختياري)",
    step1Overline: "الخطوة ١ · اختيار البيانات",
    step1Title: "ما الذي يحتاج تعديلًا؟",
    groups: {
      company: "الشركة",
      documents: "المستندات",
      owner: "المالك والبنك",
    },
    note: {
      title: "الاتفاقية التجارية ليست تصحيح بيانات",
      body: "المدة والتسوية ونموذج المخزون تخصّ اتفاقية مورّد هوتيليانا - إصدار جديد لا طلب تعديل.",
    },
    step2Overline: "الخطوة ٢ · القيم الجديدة",
    step2OverlineSelected: "الخطوة ٢ · {count} بيانات مختارة",
    step2Title: "أدخل المعلومات البديلة",
    step2Body: "تُرسل البيانات المختارة فقط إلى هوتيليانا للمراجعة.",
    emptyTitle: "لم تختر شيئًا بعد",
    emptyBody: "حدّد بيانًا من القائمة. ستظهر قيمته الحالية وحقل للقيمة الجديدة هنا.",
    current: "الحالي",
    newValue: "القيمة الجديدة",
    remove: "إزالة",
    evidenceTitle: "خطاب بنكي مطلوب لتعديل الآيبان",
    evidenceBody: "يجب أن يُظهر اسم صاحب الحساب مطابقًا تمامًا للاسم القانوني المسجّل للشركة.",
    uploadLetter: "رفع الخطاب البنكي",
    uploadFile: "رفع الملف البديل",
    uploaded: "جاهز للإرسال",
    evidenceRule:
      "تُقبل تعديلات المستندات بصيغة PDF أو JPG أو PNG حتى ١٠ ميجابايت، وتحتاج تاريخي الإصدار والانتهاء. يبقى الملف المعتمد ساريًا حتى تعتمد هوتيليانا البديل.",
    letter: {
      overline: "آيبان البنك · المستند",
      title: "ارفع خطاب البنك",
      body: "تحتاج هوتيليانا خطابًا مختومًا من البنك لتغيير الآيبان. يراجعه موظف، لذلك يجب أن تطابق التفاصيل أدناه - عادةً خلال يومي عمل.",
      dropTitle: "أفلت الخطاب هنا أو تصفّح",
      dropMeta: "PDF أو JPG · حتى ١٠ م.ب",
      choose: "اختر ملفًا",
      replace: "استبدل الملف",
      sample: "bank-letter-sep-2026.pdf · ٢٤٠ ك.ب",
      remove: "إزالة",
      rulesLabel: "يجب أن يظهر الخطاب",
      rule1: "اسم صاحب الحساب كما هو في اسم الشركة القانوني المسجّل تمامًا",
      rule2: "رقم الآيبان المراد تسجيله كاملاً",
      rule3: "ختم البنك وتاريخ إصدار خلال آخر ٣٠ يومًا",
      attach: "إرفاق الخطاب",
    },
    reviewDisabled: "مراجعة التعديلات",
    review: "مراجعة {count} تعديلات",
  },
  review: {
    overline: "اتفاقية المورّد · طلب تعديل · الخطوة ٣",
    title: "مراجعة التعديلات المطلوبة",
    subtitle: "راجع كل قيمة جديدة قبل إرسالها إلى هوتيليانا. لا يتغير شيء قبل الاعتماد.",
    cardOverline: "{count} تعديلات",
    cardTitle: "قبل وبعد",
    field: "البيان",
    currentRecord: "السجل الحالي",
    requested: "القيمة المطلوبة",
    evidence: "المستند",
    notRequired: "غير مطلوب",
    note: "تبقى السجلات غير المختارة كما هي. ورقم الهاتف والسجل التجاري والآيبان تبقى مقفلة ضمن CHG-00042.",
    nextOverline: "مسار الاعتماد",
    nextTitle: "ما يحدث بعد ذلك",
    steps: {
      one: {
        title: "إرسال الطلب",
        body: "تستلم هوتيليانا البيانات الظاهرة في هذه الصفحة فقط.",
      },
      two: {
        title: "المراجعة",
        body: "يتحقّق فريق العمليات من البيانات والمستندات.",
      },
      three: {
        title: "القرار",
        body: "القيم المعتمدة تحلّ محل السجل الحالي، والمرفوضة لا تتغير.",
      },
      four: {
        title: "الإشعار",
        body: "تستلم القرار وسبب الرفض عند وجوده.",
      },
    },
    backToEdit: "رجوع للتعديل",
    submit: "إرسال الطلب",
  },
  submitted: {
    overline: "تم إرسال الطلب",
    title: "تعديلاتك قيد المراجعة",
    subtitle:
      "ستقبل هوتيليانا كل بيان أو ترفضه. تبقى بياناتك المعتمدة سارية حتى صدور القرار، ويمكن طلب بقية البيانات بشكل منفصل.",
    statusLabel: "قيد المراجعة",
    statusNote: "أُرسل الآن",
    cardOverline: "طلب تعديل CHG-00043 · {count} بيانات",
    cardTitle: "المعلومات المُرسلة",
    pending: "قيد المراجعة",
    reference:
      "مرجع الطلب CHG-00043 · طلب مفتوح واحد لكل بيان: هذان البيانان مقفلان الآن حتى صدور القرار",
    timelineOverline: "الحالة",
    timelineTitle: "مسار المراجعة",
    timeline: {
      submitted: "أُرسل",
      submittedNote: "مكتمل · الآن",
      review: "مراجعة هوتيليانا",
      reviewNote: "جارية",
      decision: "القرار لكل بيان",
      decisionNote: "في الانتظار",
      notified: "إشعار المورّد",
      notifiedNote: "في الانتظار",
    },
    note: "في حال الرفض يبقى السجل المعتمد كما هو ويظهر سبب الرفض هنا.",
    withdrawModal: {
      overline: "سحب الطلب",
      title: "هل تسحب طلب التغيير CHG-00043؟",
      body: "تتوقف هوتيليانا عن مراجعته. ويعود {details} قابلين للتعديل، وتبقى قيمك المعتمدة الحالية سارية. ويتوقف رابط التأكيد المُرسل إلى finance@jewaralsafwah.com. يمكنك إرسال الملفات نفسها لاحقًا.",
      listLabel: "ما الذي يُسحب",
      valueItem: "{field} · القيمة الجديدة",
      fileItem: "{field} · الملف البديل",
      keep: "الاحتفاظ بالطلب",
    },
    withdraw: "سحب الطلب",
    returnToAgreement: "العودة إلى الشركة والاتفاقية",
  },
  library: {
    overline: "الملف · مكتبة الفنادق",
    title: "مكتبة الفنادق",
    subtitle: "اختر فندقًا موجودًا في هوتيليانا واطلب الوصول إليه، أو أضف فندقًا ناقصًا للاعتماد.",
    count: "{count} فندقًا",
    addMissing: "إضافة فندق ناقص",
    search: "بحث الفنادق",
    searchPh: "ابحث باسم الفندق",
    country: "الدولة",
    city: "المدينة",
    category: "الفئة",
    allStars: "كل الفئات",
    allCities: "كل المدن",
    filter: "تصفية",
    relationship: "حالتي",
    allStatuses: "أي حالة",
    stars: "{count} نجوم",
    selectionHint: "{names} - لا يُرسل شيء حتى تؤكد",
    clear: "إلغاء الاختيار",
    requestAccess: "طلب الوصول",
    pendingTitle: "{requests} قيد المراجعة لدى هوتيليانا",
    pendingBody: "تُحسم عادة خلال يومي عمل - وسيصلك إشعار في الحالتين.",
    viewRequests: "عرض الطلبات",
    notFound: "لم تجد الفندق؟ أضفه وتراجعه هوتيليانا قبل أن يصبح متاحًا.",
    linkedNote: "تُدار الفنادق المرتبطة من صفحة فنادقي.",
    openInMyHotels: "فتحه في فنادقي",
    sentAgo: "أُرسل قبل {days} أيام",
    sentJustNow: "أُرسل الآن",
    viewRequest: "عرض الطلب",
    rejectedReason: "السبب: لم تتمكن هوتيليانا من تأكيد تعاقدك مع هذا الفندق.",
    requestAgain: "يمكن إعادة الطلب من ١٠ ديسمبر",
    seeDecision: "عرض القرار",
    contractsPaused: "كل العقود موقوفة",
    seeWhy: "معرفة السبب",
    empty: "لا فنادق مطابقة لهذه الفلاتر.",
    status: {
      available: "متاح",
      requested: "مطلوب",
      linked: "مرتبط",
      notApproved: "مرفوض",
      suspended: "موقوف",
    },
  },
  myHotels: {
    allCountries: "جميع الدول",
    overline: "الملف · فنادقي",
    title: "فنادقي",
    subtitle: "تظهر هنا الفنادق المعتمدة. ولا يصبح الفندق قابلًا للحجز إلا عبر عقد توريد منشور.",
    browseLibrary: "تصفّح مكتبة الفنادق",
    empty: "لا فنادق مرتبطة بعد. اطلب الوصول من مكتبة الفنادق.",
    createContract: "إنشاء عقد توريد",
    continueDraft: "متابعة المسودة",
    openContract: "فتح العقد",
    reviewExpiring: "مراجعة العقد المنتهي قريبًا",
    rateContracts: "عقود التوريد",
    openProfile: "فتح ملف الفندق",
    search: "بحث",
    searchPh: "ابحث في الفنادق المرتبطة",
    city: "المدينة",
    allCities: "كل المدن",
    contractState: "حالة العقد",
    anyState: "أي حالة",
    statNoContract: "بدون عقد توريد",
    statNoContractNote: "فندق بلا عقد بعد",
    statDraft: "عقد مسودة",
    statDraftNote: "لم يُنشر بعد",
    statSelling: "متاح للبيع",
    statSellingNote: "{count} يحتاج انتباهك",
    note: "يبدأ الفندق بالبيع بمجرد نشر أحد عقود التوريد الخاصة به.",
    status: {
      selling: "يبيع",
      draft: "عقد مسودة",
      needsAttention: "يحتاج انتباهًا",
      noContract: "لا عقد بعد",
    },
  },
  profile: {
    overline: "فنادقي · ملف الفندق",
    badge: "معتمد ومرتبط",
    detailsOverline: "ملف هوتيليانا الرسمي · للقراءة فقط",
    detailsTitle: "بيانات الفندق",
    nameEn: "اسم الفندق (EN)",
    nameAr: "اسم الفندق (AR)",
    country: "الدولة",
    city: "المدينة",
    district: "الحي",
    category: "الفئة",
    hoteliaId: "معرّف هوتيليانا",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    distance: "المسافة إلى الحرم",
    roomsOverline: "دليل الغرف · للقراءة فقط",
    roomsTitle: "الغرف المسجّلة من هوتيليانا",
    table: {
      room: "اسم الغرفة",
      capacity: "الأساس",
      occupancy: "أقصى إشغال",
      adults: "البالغون",
      children: "الأطفال",
      childAge: "أقصى عمر للطفل",
      extra: "أسرّة إضافية",
      beds: "نوع السرير",
      size: "مساحة الغرفة",
      view: "الإطلالة",
      units: "الوحدات",
      images: "الصور",
      status: "الحالة",
    },

    imagesCounter: "{count} صور",
    note: "ملف الفندق ودليل الغرف مملوكان لهوتيليانا. الأسعار والمواسم والمخزون تُضبط داخل عقد الأسعار.",
  },
};

export const dict = {
  en: { ...en, ...extraEn, ...hotelEn, ...contractEn },
  ar: { ...ar, ...extraAr, ...hotelAr, ...contractAr },
};
export type Dict = typeof en & typeof extraEn & typeof hotelEn & typeof contractEn;
