export const teamCopy = {
  en: {
    overline: "TEAM & ACCESS",
    title: "Who in your company can do what",
    subtitle:
      "Five people from Jewar Al-Safwah use this portal and one invitation is still open. A role decides what each person reaches — there is nothing to configure beyond picking it.",
    peopleTab: "People",
    rolesTab: "Roles",
    createRole: "Create a role",
    rolesSubtitle:
      "Roles decide what each person can see and do. Built-in roles cannot be changed - duplicate one to make your own.",
    roleCol: "ROLE",
    typeCol: "TYPE",
    peopleCol: "PEOPLE",
    reachesCol: "WHAT IT REACHES",
    builtIn: "Built-in",
    custom: "Custom",
    onePerson: "1 person",
    manyPeople: "{count} people",
    cannotChange: "Cannot be changed",
    duplicate: "Duplicate",
    edit: "Edit",
    remove: "Delete",
    rolesFooter:
      "{total} roles · {builtIn} built-in, {custom} custom · {people} people. A role that still has people on it cannot be deleted.",
    roleCreated: "{name} created · assign it from Manage a person",
    areasTitle: "Areas are the summary, not the system",
    areasBody:
      "Every action in the portal is checked against what the person is allowed to do. That is what makes a custom role later a data change instead of a rebuild.",
    adminSubtitle:
      "You are an Admin - you manage everyone except the owner and other admins. Every change you make is logged in Activity and sent to Abdullrahman.",
    adminOwnersValue: "1 owner · 1 admin",
    ownersValue: "1 owner · no admins",
    adminInvitationNote: "an invitation opens nothing until it is accepted",
    viewPerson: "View",
    yourAccount: "Your account",
    primaryOwner: "Primary owner",
    youLabel: "You",
    youOwner: "You · primary owner",
    inviteExpired: "INVITE EXPIRED",
    adminReach: "Users · not owner or admins",
    activity: "Activity log",
    invite: "Invite someone",
    people: "PEOPLE WITH ACCESS",
    peopleNote: "active accounts · 1 deactivated",
    owners: "OWNER & ADMINS",
    ownersNote: "one primary owner · admins manage everyone but the owner and other admins",
    invitations: "INVITATIONS",
    invitationValue: "1 open",
    invitationNote: "and 1 expired · an invitation opens nothing until it is accepted",
    signed: "SIGNED IN TODAY",
    signedNote: "you, Ahmed and Noura",
    everyone: "Everyone",
    active: "Active",
    invited: "Invited",
    expired: "Expired",
    deactivated: "Deactivated",
    outside:
      "Nobody outside your company appears here — not Hoteliana staff, not agents, not another supplier.",
    person: "PERSON",
    role: "ROLE",
    reach: "WHAT THEY CAN REACH",
    status: "STATUS",
    lastSeen: "LAST SEEN",
    createdAt: "Created At",
    manage: "Manage",
    roleMatrix: "What each role reaches",
    roleMatrixNote:
      "Seven presets. What you see here is the summary — underneath, each one is a list of actions, and what a person can SEE is a separate permission from what they can DO.",
    permissionReference: "Open the permission reference",
    footer:
      "No role, yours included, ever sees another supplier, the agent’s selling price or the Hoteliana markup. The owner and admins can make custom roles under Roles.",
    inviteTitle: "Invite someone",
    inviteIntro:
      "They get an email, set their own password and land in Jewar Al-Safwah — you never handle a password.",
    who: "WHO ARE THEY",
    fullName: "FULL NAME",
    workEmail: "WORK EMAIL",
    emailHint: "It has to be a Jewar Al-Safwah address — a personal mailbox is refused",
    pickRole: "WHAT SHOULD THEY REACH · PICK ONE",
    pickAnother: "Pick another role",
    preview: "What {name} will and will not see",
    previewNote:
      "Green is what they reach. They will never see another supplier, the agent’s selling price or the Hoteliana markup.",
    inviteNote:
      "The invitation expires in 7 days. You can resend it or cancel it any time before it is accepted, and an unaccepted invitation gives no access at all.",
    cancel: "Cancel",
    send: "Send the invitation",
    invitationSent: "Invitation sent",
    invitationSentBody: "Khalid can now accept the invitation from his work email.",
    changeReach: "CHANGE WHAT THEY REACH",
    reachesNow: "Reaches now",
    addedBy: "Added by",
    saveRole: "Save the new role",
    deactivate: "Deactivate their account",
    reactivate: "Reactivate account",
    resend: "Resend invitation",
    cancelInvitation: "Cancel invitation",
    invitationResent: "Invitation resent",
    invitationCancelled: "Invitation cancelled",
    roleSaved: "Role updated",
    accountDeactivated: "Account deactivated",
    accountReactivated: "Account reactivated",
    transfer: "Transfer ownership",
    transferTitle: "Hand over this account",
    transferBody:
      "Choose an active person. They become the only primary owner, and you become an Admin.",
    newOwner: "NEW PRIMARY OWNER",
    reviewTransfer: "Review the transfer",
    confirmTransfer: "Confirm the transfer",
    transferred: "Ownership transferred",
    permissions: "Permission reference",
    permissionsNote:
      "Each preset is fixed. Auditor is the only role with optional read-only reach in Release 1.",
    auditorReach: "Auditor · how far the read-only reach goes",
    financeReach: "Finance · the account and its payments",
    bookingMoney: "The money side of a booking",
    guestIdentity: "Guest identity",
    alwaysSees: "An Auditor always sees these, and can never change them",
    saveReach: "Save the reach",
    activityOverline: "TEAM & ACCESS · ACTIVITY LOG",
    activityTitle: "Who did what, and what exactly changed",
    activitySubtitle:
      "Everything that moved a price, a room, a booking, a person or a number on your account. Four kinds of actor appear here — your team, Hoteliana, the system itself and a channel over the API - and each line keeps the role its author held at that moment.",
    perPage: "20 per page",
    showingPage: "Showing {from}-{to} of {total} entries · last 30 days",
    notYourTeam: "Not your team",
    notYourTeamShowing:
      "Hoteliana, the system and the API · Showing {from}-{to} of {total} entries",
    yourTeamActor: "your team",
    systemActor: "system",
    apiActor: "API",
    exportLog: "Export the log",
    entries: "ENTRIES TODAY",
    entriesNote: "5 your team · 2 Hoteliana · 1 system · 1 API",
    last30: "LAST 30 DAYS",
    immutable: "append-only · nothing here can be edited or deleted",
    mostActive: "MOST ACTIVE",
    mostActiveName: "Ahmed Saleh",
    mostActiveNote: "Revenue manager · 412 entries this month",
    kept: "KEPT UNTIL",
    contractEnds: "Contract ends",
    keptNote: "not even an owner can clear a line",
    allAreas: "All areas",
    search: "A record, a reference or a person",
    whoFilter: "WHO",
    area: "AREA",
    when: "WHEN",
    sort: "SORT",
    newest: "Newest first",
    date: "WHEN",
    actor: "WHO · ROLE AT THE TIME",
    did: "WHAT THEY DID",
    record: "THE RECORD IT TOUCHED",
    loadMore: "Load more",
    openLog: "Open",
    showing: "Showing 16 of 1,284 entries · last 30 days",
    logFooter:
      "The log is append-only. Nobody edits a line, nobody deletes one, nobody clears history — not Hoteliana, not an owner, not the person who did it. Each line also keeps the role its author held at that moment, so a person who is promoted later never rewrites what they did before.",
    filterLog: "Filter the log",
    filterIntro: "Narrow it to a person, an area or a window of time.",
    apply: "Apply · {count} entries",
    exportDone: "Activity log exported",
    logDetail: "Activity detail",
    actorType: "Actor type",
    roleAtTime: "Role at the time",
    exactChange: "Exact change",
    relatedRecord: "Related record",
    transferOnly: "transfer only",
  },
  ar: {
    createdAt: "تاريخ الإنشاء",
    overline: "الفريق والصلاحيات",
    title: "من يمكنه فعل ماذا داخل شركتك",
    subtitle:
      "يستخدم خمسة أشخاص من جوار الصفوة هذه البوابة ولا تزال هناك دعوة مفتوحة. يحدد الدور ما يصل إليه كل شخص دون إعدادات إضافية.",
    peopleTab: "الأشخاص",
    rolesTab: "الأدوار",
    createRole: "إنشاء دور",
    rolesSubtitle:
      "تحدّد الأدوار ما يراه كل شخص وما يفعله. والأدوار الجاهزة لا تُعدّل - انسخ أحدها لتصنع دورك.",
    roleCol: "الدور",
    typeCol: "النوع",
    peopleCol: "الأشخاص",
    reachesCol: "ما يصل إليه",
    builtIn: "جاهز",
    custom: "مخصص",
    onePerson: "شخص واحد",
    manyPeople: "{count} أشخاص",
    cannotChange: "لا يمكن تعديله",
    duplicate: "نسخ",
    edit: "تعديل",
    remove: "حذف",
    rolesFooter:
      "{total} أدوار · {builtIn} جاهزة، {custom} مخصص · {people} أشخاص. والدور الذي لا يزال عليه أشخاص لا يُحذف.",
    roleCreated: "أُنشئ {name} · عيّنه من «إدارة شخص»",
    areasTitle: "الأقسام ملخص وليست النظام",
    areasBody:
      "يُراجع كل إجراء في البوابة أمام ما يُسمح للشخص به. وهذا ما يجعل الدور المخصص لاحقًا تغيير بيانات لا إعادة بناء.",
    adminSubtitle:
      "أنت مدير - تدير الجميع عدا المالك والمديرين الآخرين. ويُسجّل كل تغيير تجريه في سجل النشاط ويُرسل إلى عبدالرحمن.",
    adminOwnersValue: "مالك واحد · مدير واحد",
    ownersValue: "مالك واحد · دون مديرين",
    adminInvitationNote: "لا تمنح الدعوة أي وصول حتى تُقبل",
    viewPerson: "عرض",
    yourAccount: "حسابك",
    primaryOwner: "المالك الأساسي",
    youLabel: "أنت",
    youOwner: "أنت · المالك الأساسي",
    inviteExpired: "انتهت الدعوة",
    adminReach: "المستخدمون · دون المالك والمديرين",
    activity: "سجل النشاط",
    invite: "دعوة شخص",
    people: "أشخاص لديهم صلاحية",
    peopleNote: "حسابات نشطة · حساب معطّل",
    owners: "المالك والمديرون",
    ownersNote: "مالك أساسي واحد · والمديرون يديرون الجميع عدا المالك والمديرين الآخرين",
    invitations: "الدعوات",
    invitationValue: "١ مفتوحة",
    invitationNote: "و١ منتهية · لا تمنح الدعوة أي وصول حتى تُقبل",
    signed: "سجّلوا الدخول اليوم",
    signedNote: "أنت وأحمد ونورة",
    everyone: "الجميع",
    active: "نشط",
    invited: "مدعو",
    expired: "منتهية",
    deactivated: "معطّل",
    outside: "لا يظهر هنا أي شخص خارج شركتك — لا موظفو Hoteliana ولا الوكلاء ولا مورّد آخر.",
    person: "الشخص",
    role: "الدور",
    reach: "ما يمكنه الوصول إليه",
    status: "الحالة",
    lastSeen: "آخر ظهور",
    manage: "إدارة",
    roleMatrix: "ما يصل إليه كل دور",
    roleMatrixNote:
      "سبعة أدوار ثابتة. الظاهر هنا ملخص؛ كل دور يضم إجراءات، وما يمكن للشخص رؤيته منفصل عما يمكنه فعله.",
    permissionReference: "فتح مرجع الصلاحيات",
    footer:
      "لا يرى أي دور — بما فيها دورك — مورّدًا آخر أو سعر بيع الوكيل أو هامش Hoteliana. الأدوار المخصصة تأتي بعد الإصدار الأول.",
    inviteTitle: "دعوة شخص",
    inviteIntro:
      "سيصله بريد إلكتروني ليحدد كلمة مروره ويدخل حساب جوار الصفوة — لن تتعامل أنت مع كلمة المرور.",
    who: "من هو",
    fullName: "الاسم الكامل",
    workEmail: "بريد العمل",
    emailHint: "يجب أن يكون عنوانًا تابعًا لجوار الصفوة — البريد الشخصي مرفوض",
    pickRole: "ما الذي يجب أن يصل إليه · اختر دورًا",
    pickAnother: "اختيار دور آخر",
    preview: "ما الذي سيراه {name} وما الذي لن يراه",
    previewNote:
      "الأخضر هو ما يصل إليه. لن يرى أبدًا مورّدًا آخر أو سعر بيع الوكيل أو هامش Hoteliana.",
    inviteNote:
      "تنتهي الدعوة خلال ٧ أيام. يمكنك إعادة إرسالها أو إلغاؤها قبل قبولها، والدعوة غير المقبولة لا تمنح أي وصول.",
    cancel: "إلغاء",
    send: "إرسال الدعوة",
    invitationSent: "تم إرسال الدعوة",
    invitationSentBody: "يمكن لخالد الآن قبول الدعوة من بريد العمل.",
    changeReach: "تغيير ما يمكنه الوصول إليه",
    reachesNow: "يصل حاليًا إلى",
    addedBy: "أضافه",
    saveRole: "حفظ الدور الجديد",
    deactivate: "تعطيل حسابه",
    reactivate: "إعادة تفعيل الحساب",
    resend: "إعادة إرسال الدعوة",
    cancelInvitation: "إلغاء الدعوة",
    invitationResent: "أُعيد إرسال الدعوة",
    invitationCancelled: "أُلغيت الدعوة",
    roleSaved: "تم تحديث الدور",
    accountDeactivated: "تم تعطيل الحساب",
    accountReactivated: "تمت إعادة تفعيل الحساب",
    transfer: "نقل الملكية",
    transferTitle: "تسليم هذا الحساب",
    transferBody: "اختر شخصًا نشطًا. سيصبح المالك الأساسي الوحيد، وستصبح أنت مديرًا.",
    newOwner: "المالك الأساسي الجديد",
    reviewTransfer: "مراجعة النقل",
    confirmTransfer: "تأكيد النقل",
    transferred: "تم نقل الملكية",
    permissions: "مرجع الصلاحيات",
    permissionsNote:
      "كل دور ثابت. المدقق هو الدور الوحيد ذو صلاحيات قراءة اختيارية في الإصدار الأول.",
    auditorReach: "المدقق · مدى صلاحية القراءة فقط",
    financeReach: "المالية · الحساب والمدفوعات",
    bookingMoney: "الجانب المالي للحجز",
    guestIdentity: "هوية النزيل",
    alwaysSees: "يرى المدقق هذه البيانات دائمًا ولا يمكنه تغييرها",
    saveReach: "حفظ الصلاحيات",
    activityOverline: "الفريق والصلاحيات · سجل النشاط",
    activityTitle: "من فعل ماذا، وما الذي تغيّر تحديدًا",
    activitySubtitle:
      "كل ما غيّر سعرًا أو غرفة أو حجزًا أو شخصًا أو رقمًا في حسابك. تظهر أربعة أنواع من المنفذين: فريقك وHoteliana والنظام وقناة عبر API - ويحتفظ كل سطر بالدور الذي كان لصاحبه في تلك اللحظة.",
    perPage: "٢٠ لكل صفحة",
    showingPage: "عرض {from}-{to} من {total} قيد · آخر ٣٠ يومًا",
    notYourTeam: "من خارج فريقك",
    notYourTeamShowing: "هوتيليانا والنظام والـAPI · عرض {from}-{to} من {total} قيد",
    yourTeamActor: "فريقك",
    systemActor: "النظام",
    apiActor: "API",
    exportLog: "تصدير السجل",
    entries: "إدخالات اليوم",
    entriesNote: "٥ فريقك · ٢ Hoteliana · ١ النظام · ١ API",
    last30: "آخر ٣٠ يومًا",
    immutable: "إضافة فقط · لا يمكن تعديل أو حذف أي شيء",
    mostActive: "الأكثر نشاطًا",
    mostActiveName: "أحمد صالح",
    mostActiveNote: "مدير الإيرادات · ٤١٢ إدخالًا هذا الشهر",
    kept: "محفوظ حتى",
    contractEnds: "نهاية العقد",
    keptNote: "حتى المالك لا يستطيع مسح سطر",
    allAreas: "كل الأقسام",
    search: "سجل أو مرجع أو شخص",
    whoFilter: "من",
    area: "القسم",
    when: "متى",
    sort: "الترتيب",
    newest: "الأحدث أولًا",
    date: "متى",
    actor: "من · دوره وقتها",
    did: "ماذا فعل",
    record: "السجل المتأثر",
    loadMore: "تحميل المزيد",
    openLog: "فتح",
    showing: "عرض ١٦ من ١٬٢٨٤ إدخالًا · آخر ٣٠ يومًا",
    logFooter:
      "السجل للإضافة فقط. لا يعدّل أحد سطرًا ولا يحذفه ولا يمحو التاريخ — لا Hoteliana ولا المالك ولا من نفّذ الإجراء.",
    filterLog: "تصفية السجل",
    filterIntro: "ضيّق النتائج حسب الشخص أو القسم أو الفترة.",
    apply: "تطبيق · {count} إدخالًا",
    exportDone: "تم تصدير سجل النشاط",
    logDetail: "تفاصيل النشاط",
    actorType: "نوع المنفّذ",
    roleAtTime: "الدور وقتها",
    exactChange: "التغيير الدقيق",
    relatedRecord: "السجل المرتبط",
    transferOnly: "بالنقل فقط",
  },
} as const;

export function teamFill(template: string, vars: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}

export const roleNames = {
  en: {
    owner: "Owner",
    admin: "Admin",
    revenue: "Revenue manager",
    reservations: "Reservations",
    frontOffice: "Front office",
    finance: "Finance",
    auditor: "Auditor · read only",
  },
  ar: {
    owner: "المالك",
    admin: "مدير",
    revenue: "مدير الإيرادات",
    reservations: "الحجوزات",
    frontOffice: "الاستقبال",
    finance: "المالية",
    auditor: "مدقق · قراءة فقط",
  },
} as const;

export const roleDescriptions = {
  en: {
    owner: "one per account · the only role that can hand the account over",
    admin:
      "runs the team day to day - not the owner, not other admins · only the owner gives this role",
    revenue: "prices, rooms and availability",
    reservations: "answers bookings — but never prices them",
    frontOffice: "the desk — arrivals, departures, the confirmation number",
    finance: "the account, and the money side of a booking",
    auditor: "sees, changes nothing — and its reach is a choice",
  },
  ar: {
    owner: "واحد لكل حساب · الوحيد الذي يمكنه تسليم الحساب",
    admin: "يدير الفريق يوميًا - دون المالك ولا المديرين الآخرين · والمالك وحده يمنح هذا الدور",
    revenue: "الأسعار والغرف والتوفر",
    reservations: "يرد على الحجوزات — ولا يحدد أسعارها",
    frontOffice: "الاستقبال — الوصول والمغادرة ورقم التأكيد",
    finance: "الحساب والجانب المالي للحجز",
    auditor: "يرى ولا يغيّر — ومدى وصوله اختياري",
  },
} as const;
