import { createFileRoute, Link } from "@tanstack/react-router";
import { RowsPerPage } from "@/components/layout/rows-per-page";
import { useMemo, useState } from "react";
import { AlertTriangle, ChevronDown, Download, Filter, MoreHorizontal, Search, SlidersHorizontal } from "lucide-react";
import { PageHeader, PageShell, StatusPill } from "@/components/layout/page-shell";
import { ChangeRequestStatus } from "@/components/change-requests/change-request-status";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { changeRequestCopy, crFill } from "@/lib/change-request-copy";
import type { ChangeRequest } from "@/lib/change-request-data";
import { useLanguage } from "@/lib/i18n";
import { usePortal } from "@/lib/portal-store";

export const Route = createFileRoute("/bookings/change-requests/")({
  head:()=>({meta:[{title:"Change requests · Hoteliana Supplier Portal"},{name:"description",content:"Review booking cancellation and amendment requests."},{property:"og:title",content:"Change requests · Hoteliana Supplier Portal"},{property:"og:description",content:"Review booking cancellation and amendment requests."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),
  component: ChangeRequestsPage,
});

type Tab = "all"|"cancellations"|"amendments"|"agent"|"handled";
function ChangeRequestsPage(){
  const {lang}=useLanguage(); const t=changeRequestCopy[lang]; const {changeRequests}=usePortal();
  const [tab,setTab]=useState<Tab>("all"); const [term,setTerm]=useState(""); const [hotel,setHotel]=useState("all"); const [kind,setKind]=useState("all"); const [asked,setAsked]=useState("any"); const [sort,setSort]=useState("oldest");
  const [filtersOpen,setFiltersOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [exportOpen,setExportOpen]=useState(false);
  const filtered=useMemo(()=>changeRequests.filter((r)=>{
    const tabOk=tab==="all"||(tab==="cancellations"?["cancellation","partial","shortened"].includes(r.kind):tab==="amendments"?["amendment","quote","nonCommercial"].includes(r.kind):tab==="agent"?r.state==="agent":["handled","approved","declined","cancelled"].includes(r.state));
    const q=term.trim().toLowerCase(); const askedOk=asked==="any"||(asked==="today"&&r.asked.includes("today")); return tabOk&&askedOk&&(!q||`${r.bookingId} ${r.guest} ${r.guestAr}`.toLowerCase().includes(q))&&(hotel==="all"||r.hotel===hotel)&&(kind==="all"||r.kind===kind);
  }).sort((a,b)=>sort==="newest"?b.asked.localeCompare(a.asked):a.asked.localeCompare(b.asked)),[changeRequests,tab,term,hotel,kind,asked,sort]);
  const urgent=changeRequests.filter((r)=>r.state==="waiting").slice(0,2);
  const waitingCount=changeRequests.filter((r)=>r.state==="waiting").length;
  const count=(value:Tab)=>changeRequests.filter((r)=>value==="all"||(value==="cancellations"?["cancellation","partial","shortened"].includes(r.kind):value==="amendments"?["amendment","quote","nonCommercial"].includes(r.kind):value==="agent"?r.state==="agent":["handled","approved","declined","cancelled"].includes(r.state))).length;
  /* A count reads in the digits of the language around it. */
  const num=(value:number)=>value.toLocaleString(lang==="ar"?"ar-EG":"en-US");
  const tabs:Array<[Tab,string,string]>=[["all",t.all,num(count("all"))],["cancellations",t.cancellations,num(count("cancellations"))],["amendments",t.amendments,num(count("amendments"))],["agent",t.agent,num(count("agent"))],["handled",t.handled,num(count("handled"))]];
  return <PageShell>
    <PageHeader overline={t.overline} title={t.title} subtitle={t.subtitle} pill={<StatusPill tone="warning">{crFill(t.waiting,{count:urgent.length})}</StatusPill>} right={<div className="flex gap-2"><Link to="/bookings"><Button variant="outline">{t.allBookings}</Button></Link><Button variant="outline" onClick={()=>setExportOpen(true)}><Download className="h-4 w-4"/>{t.export}</Button></div>}/>
    <section className="mb-6 rounded-xl border border-status-warning/30 bg-status-warning-bg p-5 sm:p-6"><div className="mb-5 flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-surface-default text-status-warning"><AlertTriangle className="h-5 w-5"/></span><div><h2 className="font-semibold text-text-primary">{crFill(t.urgentTitle,{count:urgent.length})}</h2><p className="mt-1 max-w-4xl text-sm text-text-secondary">{t.urgentBody}</p></div></div><div className="grid gap-3 xl:grid-cols-3">{urgent.map((r)=><UrgentCard key={r.id} request={r} lang={lang} t={t}/>)}</div></section>
    <section className="overflow-hidden rounded-xl border border-border-subtle bg-surface-default shadow-card">
      <div className="scrollbar-none flex gap-1 overflow-x-auto border-b border-border-subtle p-3">{tabs.map(([value,label,count])=><button key={value} onClick={()=>setTab(value)} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-medium ${tab===value?"bg-surface-inverse text-text-inverse":"text-text-secondary hover:bg-surface-subtle"}`}>{label} <span className="ms-1 opacity-70">{count}</span></button>)}</div>
      <div className="grid gap-3 border-b border-border-subtle p-4 md:grid-cols-[minmax(250px,1fr)_190px_165px_145px_155px_auto]">
        <button onClick={()=>setSearchOpen(true)} className="flex h-12 items-center gap-3 rounded-lg border border-border-default px-4 text-start text-sm text-text-muted"><Search className="h-4 w-4"/>{term||t.search}</button>
        <Select label={t.hotelLabel} value={hotel} onChange={setHotel} searchable={false} options={[{value:"all",label:t.allHotels},{value:"Al Noor Makkah Hotel",label:lang==="ar"?"فندق النور مكة":"Al Noor Makkah Hotel"},{value:"Rawdah Suites",label:lang==="ar"?"أجنحة الروضة":"Rawdah Suites"}]}/>
        <Select label={t.typeLabel} value={kind} onChange={setKind} searchable={false} options={[{value:"all",label:t.allTypes},{value:"cancellation",label:t.cancellations},{value:"amendment",label:t.amendments}]}/>
        <Select label={t.respondLabel} value={asked} onChange={setAsked} searchable={false} options={[{value:"any",label:t.anyTime},{value:"today",label:lang==="ar"?"اليوم":"Today"}]}/>
        <Select label={t.sortLabel} value={sort} onChange={setSort} searchable={false} options={[{value:"oldest",label:t.oldest},{value:"newest",label:lang==="ar"?"الأحدث أولًا":"Newest first"}]}/>
        <Button variant="outline" size="icon" aria-label={t.filter} onClick={()=>setFiltersOpen(true)}><SlidersHorizontal className="h-4 w-4"/></Button>
      </div>
      {filtered.length?<><div className="hidden overflow-x-auto lg:block"><div className="min-w-[1220px]"><div className="grid grid-cols-[105px_145px_1.2fr_155px_1.25fr_100px_105px_42px] gap-3 border-b border-border-subtle px-5 py-3 text-overline text-text-muted"><span>{t.reference}</span><span>{t.guest}</span><span>{t.ask}</span><span>{t.stay}</span><span>{t.meaning}</span><span>{t.asked}</span><span/><span/></div>{filtered.map((r)=><RequestRow key={r.id} request={r} lang={lang} t={t}/>)}</div></div><div className="grid gap-3 p-4 lg:hidden">{filtered.map((r)=><RequestCard key={r.id} request={r} lang={lang} t={t}/>)}</div></>:<div className="p-14 text-center">{tab==="agent"?<><p className="text-base font-semibold text-text-primary">{t.agentEmptyTitle}</p><p className="mx-auto mt-2 max-w-md text-sm text-text-secondary">{t.agentEmptyBody}</p></>:<p className="text-sm text-text-muted">{t.noResults}</p>}</div>}
      <div className="flex flex-col items-center justify-between gap-3 border-t border-border-subtle p-4 sm:flex-row"><p className="text-xs text-text-muted">{crFill(tab==="amendments"?t.showingAmendments:tab==="agent"?t.showingAgent:tab==="handled"?t.showingHandled:t.showing,{shown:filtered.length,total:tab==="all"?changeRequests.length:filtered.length})}</p><RowsPerPage value={20}/>{filtered.length<changeRequests.length&&<Button variant="outline">{t.load}<ChevronDown className="h-4 w-4"/></Button>}</div>
    </section><p className="mx-auto mt-5 max-w-4xl text-center text-xs leading-5 text-text-muted">{t.footer}</p>
    <FilterDialog open={filtersOpen} setOpen={setFiltersOpen} t={t} lang={lang} hotel={hotel} setHotel={setHotel} kind={kind} setKind={setKind} asked={asked} setAsked={setAsked} count={filtered.length}/>
    <SearchDialog open={searchOpen} setOpen={setSearchOpen} t={t} term={term} setTerm={setTerm} results={filtered} lang={lang}/>
    <ExportDialog open={exportOpen} setOpen={setExportOpen} t={t} rows={filtered} allRows={changeRequests}/>
  </PageShell>
}
function UrgentCard({request:r,lang,t}:{request:ChangeRequest;lang:"en"|"ar";t:any}){return <article className="flex min-w-0 flex-col rounded-lg border border-status-warning/25 bg-surface-default p-4"><div className="flex items-center justify-between gap-3"><p className="font-data text-xs font-semibold text-text-muted">{r.bookingId}</p><span className="rounded-full bg-status-warning-bg px-2 py-1 text-[10px] font-semibold text-status-warning">{lang==="ar"?r.badgeAr:r.badge}</span></div><h3 className="mt-3 font-semibold text-text-primary">{lang==="ar"?r.guestAr:r.guest}</h3><p className="mt-1 text-sm text-text-primary">{lang==="ar"?r.titleAr:r.title}</p><p className="mt-2 flex-1 text-xs leading-5 text-text-muted">{lang==="ar"?r.meaningAr:r.meaning}</p><Link className="mt-4" to="/bookings/change-requests/$requestId" params={{requestId:r.id}}><Button className="w-full" size="sm">{r.kind==="quote"?t.quote:t.review}</Button></Link></article>}
function RequestRow({request:r,lang,t}:{request:ChangeRequest;lang:"en"|"ar";t:any}){return <div className="grid grid-cols-[105px_145px_1.2fr_155px_1.25fr_100px_105px_42px] items-center gap-3 border-b border-border-subtle px-5 py-4 last:border-0"><b className="font-data text-xs text-text-primary">{r.bookingId}</b><div className="min-w-0"><p className="truncate text-sm font-medium text-text-primary">{lang==="ar"?r.guestAr:r.guest}</p><p className="truncate text-xs text-text-muted">{r.agency}</p></div><p className="text-sm text-text-primary">{lang==="ar"?r.titleAr:r.title}</p><p className="text-xs text-text-secondary">{lang==="ar"?r.stayAr:r.stay}</p><p className="text-xs leading-5 text-text-secondary">{lang==="ar"?r.meaningAr:r.meaning}</p><p className="text-xs text-text-muted">{lang==="ar"?r.askedAr:r.asked}</p><Link to="/bookings/change-requests/$requestId" params={{requestId:r.id}}><Button size="sm" variant={r.state==="waiting"?"default":"outline"}>{r.state==="waiting"?t.review:t.view}</Button></Link><RowMenu r={r} t={t}/></div>}
function RequestCard({request:r,lang,t}:{request:ChangeRequest;lang:"en"|"ar";t:any}){return <article className="rounded-lg border border-border-subtle p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-data text-xs font-semibold text-text-muted">{r.bookingId}</p><h3 className="mt-1 font-semibold text-text-primary">{lang==="ar"?r.guestAr:r.guest}</h3></div><ChangeRequestStatus request={r}/></div><p className="mt-4 text-sm font-medium text-text-primary">{lang==="ar"?r.titleAr:r.title}</p><p className="mt-2 text-xs leading-5 text-text-secondary">{lang==="ar"?r.meaningAr:r.meaning}</p><p className="mt-3 text-xs text-text-muted">{lang==="ar"?r.stayAr:r.stay}</p><Link className="mt-4 block" to="/bookings/change-requests/$requestId" params={{requestId:r.id}}><Button className="w-full" size="sm" variant={r.state==="waiting"?"default":"outline"}>{r.state==="waiting"?t.review:t.view}</Button></Link></article>}
function RowMenu({r,t}:{r:ChangeRequest;t:any}){
  const items=t.rowItems as Array<[string,string]>;
  const targets=["review","booking","policy","copy","issue"] as const;
  return <DropdownMenu>
    <DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Actions"><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger>
    <DropdownMenuContent align="end" className="w-[320px] p-0">
      <div className="border-b border-border-subtle px-3 py-2.5">
        <p className="truncate text-sm font-semibold text-text-primary">{r.bookingId} · {r.guest}</p>
        <p className="mt-0.5 truncate text-xs text-text-muted">{t.rowMenuMeta}</p>
      </div>
      <div className="p-1">
        {items.map(([title,hint],index)=>{
          const target=targets[index];
          const body=<span className="flex min-w-0 flex-col gap-0.5"><span className="text-sm font-medium text-text-primary">{title}</span><span className="text-xs leading-4 text-text-muted">{hint.replace("{id}",r.bookingId)}</span></span>;
          if(target==="review")return <DropdownMenuItem key={title} asChild className="items-start py-2"><Link to="/bookings/change-requests/$requestId" params={{requestId:r.id}}>{body}</Link></DropdownMenuItem>;
          if(target==="booking")return <DropdownMenuItem key={title} asChild className="items-start py-2"><Link to="/bookings/$bookingId" params={{bookingId:r.bookingId}}>{body}</Link></DropdownMenuItem>;
          if(target==="copy")return <DropdownMenuItem key={title} className="items-start py-2" onSelect={()=>navigator.clipboard?.writeText(r.bookingId)}>{body}</DropdownMenuItem>;
          return <DropdownMenuItem key={title} className="items-start py-2">{body}</DropdownMenuItem>;
        })}
      </div>
      <p className="border-t border-border-subtle px-3 py-2.5 text-xs leading-4 text-text-muted">{t.rowMenuNote}</p>
    </DropdownMenuContent>
  </DropdownMenu>;
}
function FilterDialog({open,setOpen,t,lang,hotel,setHotel,kind,setKind,asked,setAsked,count}:{open:boolean;setOpen:(v:boolean)=>void;t:any;lang:"en"|"ar";hotel:string;setHotel:(v:string)=>void;kind:string;setKind:(v:string)=>void;asked:string;setAsked:(v:string)=>void;count:number}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[640px]"><DialogHeader><DialogTitle>{t.filter}</DialogTitle><DialogDescription>{t.subtitle}</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Select label={lang==="ar"?"الفندق":"Hotel"} value={hotel} onChange={setHotel} searchable={false} options={[{value:"all",label:t.allHotels},{value:"Al Noor Makkah Hotel",label:"Al Noor Makkah Hotel"},{value:"Rawdah Suites",label:"Rawdah Suites"}]}/><Select label={lang==="ar"?"نوع الطلب":"Request type"} value={kind} onChange={setKind} searchable={false} options={[{value:"all",label:t.allTypes},{value:"cancellation",label:t.cancellations},{value:"amendment",label:t.amendments}]}/><Select label={lang==="ar"?"وقت الطلب":"Asked"} value={asked} onChange={setAsked} searchable={false} options={[{value:"any",label:t.anyTime},{value:"today",label:lang==="ar"?"اليوم":"Today"}]}/></div><DialogFooter><Button variant="outline" onClick={()=>{setHotel("all");setKind("all");setAsked("any")}}>{t.clear}</Button><Button onClick={()=>setOpen(false)}>{crFill(t.apply,{count})}</Button></DialogFooter></DialogContent></Dialog>}
function SearchDialog({open,setOpen,t,term,setTerm,results,lang}:{open:boolean;setOpen:(v:boolean)=>void;t:any;term:string;setTerm:(v:string)=>void;results:ChangeRequest[];lang:"en"|"ar"}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[680px]"><DialogHeader><DialogTitle>{t.searchTitle}</DialogTitle></DialogHeader><div className="relative"><Search className="pointer-events-none absolute start-4 top-[17px] z-10 h-4 w-4 text-text-muted"/><Input autoFocus placeholder={t.search} value={term} onChange={(e)=>setTerm(e.target.value)} className="[&_input]:ps-11"/></div><p className="text-overline text-text-muted">{t.matches}</p><div className="max-h-72 overflow-y-auto">{results.slice(0,6).map((r)=><Link key={r.id} onClick={()=>setOpen(false)} to="/bookings/change-requests/$requestId" params={{requestId:r.id}} className="flex items-center justify-between gap-3 border-b border-border-subtle py-3"><div><b className="font-data text-xs">{r.bookingId}</b><p className="text-sm text-text-primary">{lang==="ar"?r.guestAr:r.guest}</p></div><span className="text-xs text-text-muted">{lang==="ar"?r.titleAr:r.title}</span></Link>)}</div></DialogContent></Dialog>}
function ExportDialog({open,setOpen,t,rows,allRows}:{open:boolean;setOpen:(v:boolean)=>void;t:any;rows:ChangeRequest[];allRows:ChangeRequest[]}){const [format,setFormat]=useState("csv");const [scope,setScope]=useState("view");const [cols,setCols]=useState(["Reference","Guest","Agency","What was asked","Stay","Money at stake","Asked at","Your answer"]);const run=()=>{const picked=scope==="view"?rows:scope==="open"?allRows.filter(r=>r.state==="waiting"||r.state==="agent"):allRows;const csv=[cols.join(","),...picked.map((r)=>[r.bookingId,r.guest,r.agency,r.title,r.stay,r.ceiling,r.asked,r.state].map((v)=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");const blob=new Blob([csv],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`change-requests.${format==="excel"?"xls":"csv"}`;a.click();URL.revokeObjectURL(url);setOpen(false)};return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[680px]"><DialogHeader><DialogTitle>{t.exportTitle}</DialogTitle><DialogDescription>{t.subtitle}</DialogDescription></DialogHeader><div className="grid gap-2">{[["view",t.inView],["open",t.openOnly],["all",t.everything]].map(([v,l])=><label key={v} className="flex cursor-pointer items-center gap-3 rounded-lg border border-border-subtle p-3"><input type="radio" checked={scope===v} onChange={()=>setScope(v)}/><span className="text-sm text-text-primary">{l}</span></label>)}</div><div className="grid grid-cols-2 gap-3"><Button variant={format==="csv"?"dark":"outline"} onClick={()=>setFormat("csv")}>CSV</Button><Button variant={format==="excel"?"dark":"outline"} onClick={()=>setFormat("excel")}>Excel</Button></div><p className="text-overline text-text-muted">{t.columns}</p><div className="grid gap-2 sm:grid-cols-2">{["Reference","Guest","Agency","What was asked","Type","Stay","Rooms · nights","Money at stake","Asked at","Your answer","Amount charged","Answered at","Financial status"].map((c)=><label key={c} className="flex items-center gap-2 text-sm text-text-secondary"><Checkbox checked={cols.includes(c)} onCheckedChange={(v)=>setCols(v?[...cols,c]:cols.filter((x)=>x!==c))}/>{c}</label>)}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.cancel}</Button><Button onClick={run}><Download className="h-4 w-4"/>{crFill(t.exportRows,{count:rows.length})}</Button></DialogFooter></DialogContent></Dialog>}
