import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { AlertTriangle, Check, Download, Paperclip, Phone, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { StatusPill } from "@/components/layout/page-shell";
import { financeCopy, financeFill } from "@/lib/finance-copy";
import { financeEntries, financeMovements, type FinanceEntryDetail, type FinanceMovement } from "@/lib/finance-data";
import { useLanguage } from "@/lib/i18n";
import { downloadText } from "@/lib/download";
import { notify } from "@/lib/notify";

export function EntryDrawer({reference,onClose}:{reference:string|null;onClose:()=>void}){
  const {lang,dir}=useLanguage(); const t=financeCopy[lang]; const entry=reference?financeEntries[reference]:undefined;
  return <Sheet open={Boolean(entry)} onOpenChange={(open)=>{if(!open)onClose()}}><SheetContent side={dir==="rtl"?"left":"right"} className="w-full overflow-y-auto bg-surface-default p-0 sm:max-w-[560px]">{entry&&<div className="p-6"><SheetHeader className="pe-10 text-start"><div className="flex flex-wrap items-center gap-2"><StatusPill tone={entry.direction==="against"?"danger":"brand"}>{entry.direction==="against"?t.entryAgainst:t.entryFavour}</StatusPill><span className="font-data text-xs text-text-muted">{entry.reference}</span></div><SheetTitle className="text-2xl leading-tight">{lang==="ar"?entry.titleAr:entry.title}</SheetTitle><SheetDescription className="sr-only">{lang==="ar"?entry.titleAr:entry.title}</SheetDescription></SheetHeader><div className={`mt-5 rounded-lg border p-4 ${entry.direction==="against"?"border-status-danger/20 bg-status-danger-bg":"border-primary-subtle-border bg-primary-subtle"}`}><p className="text-overline text-text-muted">{entry.direction==="against"?t.taken:t.added}</p><p className={`mt-1 font-data text-2xl font-semibold ${entry.amount<0?"text-status-danger":"text-status-success"}`}>{signed(entry.amount)} SAR</p><p className="mt-1 text-xs text-text-secondary">{entry.before.toLocaleString()} → {entry.after.toLocaleString()} SAR</p></div><p className="mb-3 mt-5 text-overline text-text-muted">{t.entryTitle}</p><div className="divide-y divide-border-subtle border-y border-border-subtle"><Detail label={t.postedBy}>Hoteliana · Reem Tarek<br/><small>{lang==="ar"?"عمليات المورّدين":"supplier operations"}</small></Detail><Detail label={t.postedOn}>{lang==="ar"?entry.postedOnAr:entry.postedOn}</Detail><Detail label={t.why}>{lang==="ar"?entry.whyAr:entry.why}</Detail><Detail label={t.booking}>{entry.bookingId?<><b>{entry.bookingId}</b><br/><small>{lang==="ar"?entry.bookingSummaryAr:entry.bookingSummary}</small></>:lang==="ar"?"غير مرتبط بحجز":"Not linked to a booking"}</Detail><Detail label={t.coverage}>{lang==="ar"?entry.coverageAr:entry.coverage}</Detail>{entry.replaces&&<Detail label={lang==="ar"?"يستبدل":"What it replaces"}>{entry.replaces}</Detail>}{entry.attachment&&<Detail label={t.attached}><button className="font-data text-text-link" onClick={()=>downloadText(entry.attachment??"entry.txt",entry.reference)}>{entry.attachment}</button></Detail>}<Detail label={t.effect}>{t.none}</Detail></div><div className="mt-5 rounded-lg bg-surface-subtle p-4 text-xs leading-5 text-text-secondary">{t.note}</div><div className="mt-5 flex flex-wrap gap-2"><ContactDialog movement={financeMovements.find((m)=>m.reference===entry.reference)} /><BookingLink id={entry.bookingId} label={t.openBooking}/></div></div>}</SheetContent></Sheet>
}

function Detail({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-2 py-3 text-sm sm:grid-cols-[180px_1fr]"><span className="text-text-secondary">{label}</span><div className="min-w-0 break-words text-text-primary">{children}</div></div>}
function BookingLink({id,label}:{id:string|undefined;label:string}){return id?<Link to="/bookings/$bookingId" params={{bookingId:id}}><Button variant="outline">{label}</Button></Link>:null}
export function ContactDialog({movement}:{movement:FinanceMovement|undefined}){const {lang}=useLanguage();const t=financeCopy[lang];const [open,setOpen]=useState(false);const [sent,setSent]=useState(false);const [note,setNote]=useState("");return <Dialog open={open} onOpenChange={(v)=>{setOpen(v);if(!v)setSent(false)}}><Button variant="outline" onClick={()=>setOpen(true)}><Phone className="h-4 w-4"/>{t.call}</Button><DialogContent className="max-w-[600px]">{sent?<><DialogHeader><span className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary-subtle text-status-success"><Check className="h-5 w-5"/></span><DialogTitle>{t.sentTitle}</DialogTitle><DialogDescription>{t.sentRef}</DialogDescription></DialogHeader><div className="rounded-lg border border-border-subtle"><Detail label={t.sentAbout}>{movement?.reference} · {signed(movement?.amount??0)} SAR</Detail><Detail label={t.sentWho}>Reem Tarek · supplier operations</Detail><Detail label={t.sentReply}>{t.sentReplyValue}</Detail><Detail label={t.sentMeanwhile}>{t.sentMeanwhileValue}</Detail><Detail label={t.sentAgree}>{t.sentAgreeValue}</Detail></div><div className="rounded-lg bg-surface-subtle p-4 text-xs leading-5 text-text-secondary">{t.sentFooter}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.followMessage}</Button><Button onClick={()=>setOpen(false)}>{t.backAccount}</Button></DialogFooter></>:<><DialogHeader><DialogTitle>{t.contactTitle}</DialogTitle><DialogDescription>{t.contactBody}</DialogDescription></DialogHeader><div className="rounded-lg border border-border-subtle"><Detail label={t.movementLabel}>{movement?.reference} · {movement?.type==="entryAgainst"?t.entryAgainst:t.booking}</Detail><Detail label={t.amountLabel}>{signed(movement?.amount??0)} SAR</Detail><Detail label={t.manager}>Reem Tarek · supplier operations</Detail><Detail label={t.direct}>+966 11 000 0000 · Sun – Thu, 09:00 – 18:00</Detail><Detail label={t.quote}>{movement?.reference} · posted 13 Sep 11:20</Detail></div><label className="text-[13px] font-medium text-text-primary">{t.write}</label><Textarea value={note} onChange={(e)=>setNote(e.target.value)} placeholder={t.writePh}/><p className="text-xs leading-5 text-text-muted">{t.noteNote}</p><p className="text-xs font-medium text-text-link">{t.disputeInstead}</p><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.close}</Button><Button onClick={()=>{setSent(true);notify.success(t.sentTitle)}}>{t.send}</Button></DialogFooter></>}</DialogContent></Dialog>}

export function SearchStatement({open,setOpen,onOpen}:{open:boolean;setOpen:(v:boolean)=>void;onOpen:(m:FinanceMovement)=>void}){const {lang}=useLanguage();const t=financeCopy[lang];const [term,setTerm]=useState("PAY-014");const rows=financeMovements.filter(m=>`${m.reference} ${m.title} ${m.detail}`.toLowerCase().includes(term.toLowerCase())).slice(0,5);return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[720px]"><DialogHeader><DialogTitle>{t.searchTitle}</DialogTitle><DialogDescription>{t.search}</DialogDescription></DialogHeader><div className="relative"><Search className="absolute start-4 top-4 h-4 w-4 text-text-muted"/><Input value={term} onChange={e=>setTerm(e.target.value)} className="[&_input]:ps-11"/></div><p className="text-overline text-text-muted">{t.matches}</p><div className="divide-y divide-border-subtle rounded-lg border border-border-subtle">{rows.map(m=><button key={m.reference} onClick={()=>{onOpen(m);setOpen(false)}} className="flex w-full items-center justify-between gap-4 p-4 text-start hover:bg-surface-subtle"><span><b className="font-data text-sm">{m.reference}</b><small className="mt-1 block text-text-muted">{lang==="ar"?m.titleAr:m.title}</small></span><span className="font-data text-sm">{signed(m.amount)} SAR</span></button>)}</div></DialogContent></Dialog>}

export function FilterStatement({open,setOpen,hotel,setHotel,count}:{open:boolean;setOpen:(v:boolean)=>void;hotel:string;setHotel:(v:string)=>void;count:number}){const {lang}=useLanguage();const t=financeCopy[lang];return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[900px]"><DialogHeader><DialogTitle>{t.filterTitle}</DialogTitle><DialogDescription>{t.filterBody}</DialogDescription></DialogHeader><div className="grid gap-6 md:grid-cols-2"><div><p className="mb-2 text-overline text-text-muted">{t.hotel}</p>{["all","Al Noor Makkah Hotel","Rawdah Suites","Central Haram Hotel"].map(v=><label key={v} className="flex items-center gap-3 border-b border-border-subtle py-3"><Checkbox checked={hotel===v} onCheckedChange={()=>setHotel(v)}/><span>{v==="all"?t.allHotels:v}</span></label>)}</div><div><p className="mb-2 text-overline text-text-muted">{t.movement}</p>{[["all",t.everything],["booking",t.bookings],["entry",t.entries],["payment",t.paymentsTab]].map(([v,l])=><label key={v} className="flex items-center gap-3 border-b border-border-subtle py-3"><Checkbox checked={v==="all"}/><span>{l}</span></label>)}</div></div><DialogFooter><Button variant="outline" onClick={()=>setHotel("all")}>{t.clear}</Button><Button onClick={()=>setOpen(false)}>{financeFill(t.apply,{count})}</Button></DialogFooter></DialogContent></Dialog>}

export function ExportStatement({open,setOpen,rows}:{open:boolean;setOpen:(v:boolean)=>void;rows:FinanceMovement[]}){const {lang}=useLanguage();const t=financeCopy[lang];const [scope,setScope]=useState("view");const [format,setFormat]=useState("csv");const [columns,setColumns]=useState<string[]>([t.date,t.movement,t.reference,t.what,t.amount,t.balanceAfter]);const available:string[]=[t.date,t.movement,t.reference,t.what,t.amount,t.balanceAfter,t.hotel,t.currency];const run=()=>{const csv=[columns.join(","),...rows.map(m=>[m.date,m.type,m.reference,m.title,m.amount,m.balance].map(v=>`"${String(v).replaceAll('"','""')}"`).join(","))].join("\n");downloadText(`hoteliana-statement.${format==="excel"?"xls":format}`,csv);setOpen(false);notify.success(t.download)};return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-[620px]"><DialogHeader><DialogTitle>{t.exportTitle}</DialogTitle><DialogDescription>{t.exportBody}</DialogDescription></DialogHeader><p className="text-overline text-text-muted">{t.fileScope}</p><RadioGroup value={scope} onValueChange={setScope} className="grid gap-2">{[["view",t.inView],["unpaid",t.unpaid],["year",t.fullYear],["payment",t.onePayment]].map(([v,l])=><label key={v} className="flex items-center gap-3 rounded-lg border border-border-subtle p-3"><RadioGroupItem value={v??""}/>{l}</label>)}</RadioGroup><p className="text-overline text-text-muted">{t.format}</p><div className="grid grid-cols-3 gap-2">{["csv","excel","pdf"].map(v=><Button key={v} variant={format===v?"dark":"outline"} onClick={()=>setFormat(v)}>{v.toUpperCase()}</Button>)}</div><p className="text-overline text-text-muted">{t.columns}</p><div className="flex flex-wrap gap-2">{available.map(col=><label key={col} className="flex items-center gap-2 rounded-full border border-border-subtle px-3 py-2 text-xs"><Checkbox checked={columns.includes(col)} onCheckedChange={(yes)=>setColumns(yes?[...columns,col]:columns.filter(c=>c!==col))}/>{col}</label>)}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.cancel}</Button><Button onClick={run}><Download className="h-4 w-4"/>{t.download}</Button></DialogFooter></DialogContent></Dialog>}

/** OV 07.14 / 07.14A / 07.14E — dispute an entry, with the two evidence states. */
export function DisputeDialog({movement,open,setOpen}:{movement:FinanceMovement|undefined;open:boolean;setOpen:(v:boolean)=>void}){
  const {lang}=useLanguage();const t=financeCopy[lang];
  const [reason,setReason]=useState("");const [happened,setHappened]=useState("");
  const [evidence,setEvidence]=useState<"none"|"attached"|"rejected">("none");
  const amount=Math.abs(movement?.amount??0).toLocaleString();
  const close=()=>{setOpen(false);setEvidence("none");setReason("");setHappened("")};
  return <Dialog open={open} onOpenChange={(v)=>v?setOpen(true):close()}><DialogContent className="max-w-[640px]">
    <DialogHeader>
      <p className="text-overline text-text-muted">{movement?.reference} · {(lang==="ar"?movement?.titleAr:movement?.title)?.toUpperCase()}</p>
      <DialogTitle>{t.dispTitle}</DialogTitle>
      <DialogDescription>{t.dispBody}</DialogDescription>
    </DialogHeader>
    <div className="rounded-lg border border-border-subtle">
      <Detail label={t.dispEntry}>{financeFill(t.dispPosted,{ref:movement?.reference??""})}</Detail>
      <Detail label={t.dispWhat}>{lang==="ar"?movement?.titleAr:movement?.title}</Detail>
      <Detail label={t.dispAmountRow}><b className="font-data">{signed(movement?.amount??0)} SAR</b></Detail>
      <Detail label={t.dispStatusNow}><StatusPill tone="warning">{t.stPending}</StatusPill></Detail>
    </div>
    <label className="text-overline text-text-muted">{t.dispReason}</label>
    <Input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder={t.dispReasonPh}/>
    <label className="text-overline text-text-muted">{t.dispAmountLabel}</label>
    <Input value={financeFill(t.dispAmountValue,{amount})} readOnly/>
    <label className="text-overline text-text-muted">{t.dispHappened}</label>
    <Textarea value={happened} onChange={(e)=>setHappened(e.target.value)} placeholder={t.dispHappenedPh}/>
    <label className="text-overline text-text-muted">{t.dispEvidence}</label>
    {evidence==="none"&&<Button variant="outline" className="justify-start" onClick={()=>setEvidence("attached")}><Paperclip className="h-4 w-4"/>{t.dispAttach}</Button>}
    {evidence==="attached"&&<div className="flex items-center justify-between gap-3 rounded-lg border border-border-subtle p-3 text-xs"><span className="flex items-center gap-2"><Paperclip className="h-4 w-4 text-text-muted"/>{t.dispAttached}</span><Button size="sm" variant="ghost" onClick={()=>setEvidence("rejected")}>{t.dispReplace}</Button></div>}
    {evidence==="rejected"&&<div className="flex items-center justify-between gap-3 rounded-lg border border-status-danger/20 bg-status-danger-bg p-3 text-xs"><span className="flex items-center gap-2 text-status-danger"><AlertTriangle className="h-4 w-4"/>{t.dispRejected}</span><Button size="sm" variant="ghost" onClick={()=>setEvidence("attached")}>{t.dispAnother}</Button></div>}
    <p className="rounded-lg bg-surface-subtle p-4 text-xs leading-5 text-text-secondary">{t.dispNote}</p>
    <DialogFooter><Button variant="outline" onClick={close}>{t.cancel}</Button><Button disabled={evidence==="rejected"} onClick={()=>{notify.success(t.dispSent);close()}}>{t.dispSend}</Button></DialogFooter>
  </DialogContent></Dialog>
}

export function signed(value:number){return `${value>=0?"+ ":"− "}${Math.abs(value).toLocaleString()}`}
