import { useState } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { dashboardCopy } from "@/lib/dashboard-copy";
import { dashboardMonths } from "@/lib/dashboard-data";
import { DatePicker, dateOf, type DayRange } from "@/components/ui/date-picker";
import { datePickerCopy } from "@/lib/date-picker-copy";
import { useLanguage } from "@/lib/i18n";
import { notify } from "@/lib/notify";

export function PeriodDialog({open,setOpen}:{open:boolean;setOpen:(open:boolean)=>void}){
 const {lang}=useLanguage();const t=dashboardCopy[lang];const [period,setPeriod]=useState("12");const [compare,setCompare]=useState("year");const [hotel,setHotel]=useState("all");const [range,setRange]=useState<DayRange|null>(null);
 const periods=lang==="ar"?[["12","آخر ١٢ شهرًا","أكتوبر ٢٠٢٥ – سبتمبر ٢٠٢٦"],["term","مدة العقد الحالية","١ أكتوبر – ٣١ ديسمبر ٢٠٢٦"],["90","آخر ٩٠ يومًا","٢٠ يونيو – ١٧ سبتمبر ٢٠٢٦"],["ytd","منذ بداية العام","يناير – سبتمبر ٢٠٢٦"],["range","نطاق تحدده","اختر تاريخ البداية والنهاية"]]:[["12","Last 12 months","Oct 2025 – Sep 2026"],["term","This contract term","1 Oct 2026 – 31 Dec 2026"],["90","Last 90 days","20 Jun – 17 Sep 2026"],["ytd","Year to date","Jan – Sep 2026"],["range","A range you pick","Choose start and end dates"]];
 const compares=lang==="ar"?[["year","الفترة نفسها من العام السابق"],["before","الفترة السابقة مباشرة"],["none","بدون مقارنة"]]:[["year","The same period last year"],["before","The period immediately before"],["none","Nothing — just show me this period"]];
 const hotels=lang==="ar"?[["all","كل الفنادق الثلاثة"],["noor","النور مكة فقط · ٦٤٪ من لياليك"],["rawdah","أجنحة الروضة فقط"],["central","الحرم المركزي فقط"]]:[["all","All 3 hotels"],["noor","Al Noor Makkah only · 64% of your nights"],["rawdah","Rawdah Suites only"],["central","Central Haram only"]];
 return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] max-w-[640px] overflow-y-auto"><DialogHeader><DialogTitle>{t.periodTitle}</DialogTitle><DialogDescription>{t.periodBody}</DialogDescription></DialogHeader><Choice title={lang==="ar"?"الفترة":"Period"} value={period} setValue={setPeriod} rows={periods}/>{period==="range"&&<DatePicker actions={false} onChange={setRange} onApply={()=>undefined} onCancel={()=>setPeriod("12")} className="w-full"/>}<Choice title={t.compare} value={compare} setValue={setCompare} rows={compares}/><Choice title={t.hotels} value={hotel} setValue={setHotel} rows={hotels}/><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.cancel}</Button><Button disabled={period==="range"&&!range?.end} onClick={()=>{setOpen(false);const ms=datePickerCopy[lang==="ar"?"ar":"en"].monthsShort;const fmt=(key:string)=>{const d=dateOf(key);return `${d.getDate()} ${ms[d.getMonth()]}`};const span=range?.end?` · ${fmt(range.start)} – ${fmt(range.end)}`:"";notify.success((lang==="ar"?"تم تطبيق نطاق التحليلات":"Analytics scope applied")+span)}}>{t.apply}</Button></DialogFooter></DialogContent></Dialog>
}
function Choice({title,value,setValue,rows}:{title:string;value:string;setValue:(v:string)=>void;rows:string[][]}){return <div><p className="mb-2 text-overline text-text-muted">{title}</p><RadioGroup value={value} onValueChange={setValue} className="gap-2">{rows.map(([v,label,note])=><label key={v} className="flex cursor-pointer items-start gap-3 rounded-lg border border-border-subtle p-3 hover:bg-surface-subtle"><RadioGroupItem value={v??""} className="mt-0.5"/><span className="text-sm text-text-primary">{label}{note&&<small className="mt-0.5 block text-text-muted">{note}</small>}</span></label>)}</RadioGroup></div>}

export function ChartDataDialog({open,setOpen}:{open:boolean;setOpen:(open:boolean)=>void}){const {lang}=useLanguage();const t=dashboardCopy[lang];const exportCsv=()=>{const csv=[[t.month,t.roomNights,t.yourRate,t.vsLast].join(","),...dashboardMonths.map(m=>[lang==="ar"?m.monthAr:m.month,m.nights,m.rate,m.yoy].join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="hoteliana-dashboard.csv";a.click();URL.revokeObjectURL(url);notify.success(t.exportCsv)};return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-[720px] overflow-y-auto"><DialogHeader><DialogTitle>{t.roomNightsTitle}</DialogTitle><DialogDescription>{dashboardCopy[lang].period}</DialogDescription></DialogHeader><div className="overflow-x-auto rounded-lg border border-border-subtle"><table className="w-full min-w-[540px] text-sm"><thead className="bg-surface-subtle text-overline text-text-muted"><tr>{[t.month,t.roomNights,t.yourRate,t.vsLast].map(h=><th key={h} className="px-4 py-3 text-start">{h}</th>)}</tr></thead><tbody>{dashboardMonths.map(m=><tr key={m.month} className="border-t border-border-subtle"><td className="px-4 py-3 font-medium">{lang==="ar"?m.monthAr:m.month}</td><td className="font-data px-4 py-3">{m.nights}</td><td className="font-data px-4 py-3">{m.rate} SAR</td><td className="font-data px-4 py-3 text-status-success">{m.yoy}</td></tr>)}</tbody></table></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>{t.close}</Button><Button onClick={exportCsv}><Download className="h-4 w-4"/>{t.exportCsv}</Button></DialogFooter></DialogContent></Dialog>}
