/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as ActivateAccountPageRouteImport } from './routes/activate-account-page'
import { Route as AddHotelRouteImport } from './routes/add-hotel'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ChangeApprovedRouteImport } from './routes/change-approved'
import { Route as ChangePartlyApprovedRouteImport } from './routes/change-partly-approved'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ChangeRejectedRouteImport } from './routes/change-rejected'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmptyStatesRouteImport } from './routes/empty-states'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as InformationRequestsRouteImport } from './routes/information-requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyHotelsRouteImport } from './routes/my-hotels'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RateCalendarRouteImport } from './routes/rate-calendar'
import { Route as RateContractsRouteImport } from './routes/rate-contracts'
import { Route as RequestChangesRouteImport } from './routes/request-changes'
import { Route as RequestSubmittedRouteImport } from './routes/request-submitted'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewChangesRouteImport } from './routes/review-changes'
import { Route as SecureAccountRouteImport } from './routes/secure-account'
import { Route as SellStatusRouteImport } from './routes/sell-status'
import { Route as SystemStatesRouteImport } from './routes/system-states'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as BookingsChangeRequestsRouteImport } from './routes/bookings.change-requests'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as FinanceAdjustmentsRouteImport } from './routes/finance.adjustments'
import { Route as FinanceBankRouteImport } from './routes/finance.bank'
import { Route as FinanceEarningsRouteImport } from './routes/finance.earnings'
import { Route as FinancePaymentsRouteImport } from './routes/finance.payments'
import { Route as FinanceTaxInvoicesRouteImport } from './routes/finance.tax-invoices'
import { Route as HotelHotelIdRouteImport } from './routes/hotel.$hotelId'
import { Route as RateContractsIndexRouteImport } from './routes/rate-contracts.index'
import { Route as RateContractsContractIdRouteImport } from './routes/rate-contracts.$contractId'
import { Route as RateContractsNewRouteImport } from './routes/rate-contracts.new'
import { Route as RatesWinListRouteImport } from './routes/rates.win-list'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamActivityRouteImport } from './routes/team.activity'
import { Route as BookingsBookingIdIndexRouteImport } from './routes/bookings.$bookingId.index'
import { Route as BookingsChangeRequestsIndexRouteImport } from './routes/bookings.change-requests.index'
import { Route as BookingsChangeRequestsRequestIdRouteImport } from './routes/bookings.change-requests.$requestId'
import { Route as FinancePaymentsIndexRouteImport } from './routes/finance.payments.index'
import { Route as FinanceReportsIndexRouteImport } from './routes/finance.reports.index'
import { Route as FinanceReportsReportRouteImport } from './routes/finance.reports.$report'
import { Route as FinanceStatementsIndexRouteImport } from './routes/finance.statements.index'
import { Route as FinanceStatementsMonthRouteImport } from './routes/finance.statements.$month'
import { Route as RateContractsContractIdIndexRouteImport } from './routes/rate-contracts.$contractId.index'
import { Route as RateContractsContractIdEditRouteImport } from './routes/rate-contracts.$contractId.edit'
import { Route as RateContractsContractIdQueueRouteImport } from './routes/rate-contracts.$contractId.queue'
import { Route as BookingsChangeRequestsRequestIdIndexRouteImport } from './routes/bookings.change-requests.$requestId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateAccountPageRoute = ActivateAccountPageRouteImport.update({
  id: '/activate-account-page',
  path: '/activate-account-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AddHotelRoute = AddHotelRouteImport.update({
  id: '/add-hotel',
  path: '/add-hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeApprovedRoute = ChangeApprovedRouteImport.update({
  id: '/change-approved',
  path: '/change-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePartlyApprovedRoute = ChangePartlyApprovedRouteImport.update({
  id: '/change-partly-approved',
  path: '/change-partly-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRejectedRoute = ChangeRejectedRouteImport.update({
  id: '/change-rejected',
  path: '/change-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmptyStatesRoute = EmptyStatesRouteImport.update({
  id: '/empty-states',
  path: '/empty-states',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRequestsRoute = InformationRequestsRouteImport.update({
  id: '/information-requests',
  path: '/information-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHotelsRoute = MyHotelsRouteImport.update({
  id: '/my-hotels',
  path: '/my-hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCalendarRoute = RateCalendarRouteImport.update({
  id: '/rate-calendar',
  path: '/rate-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const RateContractsRoute = RateContractsRouteImport.update({
  id: '/rate-contracts',
  path: '/rate-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestChangesRoute = RequestChangesRouteImport.update({
  id: '/request-changes',
  path: '/request-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSubmittedRoute = RequestSubmittedRouteImport.update({
  id: '/request-submitted',
  path: '/request-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewChangesRoute = ReviewChangesRouteImport.update({
  id: '/review-changes',
  path: '/review-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureAccountRoute = SecureAccountRouteImport.update({
  id: '/secure-account',
  path: '/secure-account',
  getParentRoute: () => rootRouteImport,
} as any)
const SellStatusRoute = SellStatusRouteImport.update({
  id: '/sell-status',
  path: '/sell-status',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatesRoute = SystemStatesRouteImport.update({
  id: '/system-states',
  path: '/system-states',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => BookingsRoute,
} as any)
const BookingsChangeRequestsRoute = BookingsChangeRequestsRouteImport.update({
  id: '/change-requests',
  path: '/change-requests',
  getParentRoute: () => BookingsRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CasesRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAdjustmentsRoute = FinanceAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceBankRoute = FinanceBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceEarningsRoute = FinanceEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => FinanceRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceTaxInvoicesRoute = FinanceTaxInvoicesRouteImport.update({
  id: '/tax-invoices',
  path: '/tax-invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const HotelHotelIdRoute = HotelHotelIdRouteImport.update({
  id: '/hotel/$hotelId',
  path: '/hotel/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const RateContractsIndexRoute = RateContractsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RateContractsRoute,
} as any)
const RateContractsContractIdRoute = RateContractsContractIdRouteImport.update({
  id: '/$contractId',
  path: '/$contractId',
  getParentRoute: () => RateContractsRoute,
} as any)
const RateContractsNewRoute = RateContractsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RateContractsRoute,
} as any)
const RatesWinListRoute = RatesWinListRouteImport.update({
  id: '/rates/win-list',
  path: '/rates/win-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamActivityRoute = TeamActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => TeamRoute,
} as any)
const BookingsBookingIdIndexRoute = BookingsBookingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookingsBookingIdRoute,
} as any)
const BookingsChangeRequestsIndexRoute =
  BookingsChangeRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookingsChangeRequestsRoute,
  } as any)
const BookingsChangeRequestsRequestIdRoute =
  BookingsChangeRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => BookingsChangeRequestsRoute,
  } as any)
const FinancePaymentsIndexRoute = FinancePaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinancePaymentsRoute,
} as any)
const FinanceReportsIndexRoute = FinanceReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsReportRoute = FinanceReportsReportRouteImport.update({
  id: '/reports/$report',
  path: '/reports/$report',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceStatementsIndexRoute = FinanceStatementsIndexRouteImport.update({
  id: '/statements/',
  path: '/statements/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceStatementsMonthRoute = FinanceStatementsMonthRouteImport.update({
  id: '/statements/$month',
  path: '/statements/$month',
  getParentRoute: () => FinanceRoute,
} as any)
const RateContractsContractIdIndexRoute =
  RateContractsContractIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RateContractsContractIdRoute,
  } as any)
const RateContractsContractIdEditRoute =
  RateContractsContractIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => RateContractsContractIdRoute,
  } as any)
const RateContractsContractIdQueueRoute =
  RateContractsContractIdQueueRouteImport.update({
    id: '/queue',
    path: '/queue',
    getParentRoute: () => RateContractsContractIdRoute,
  } as any)
const BookingsChangeRequestsRequestIdIndexRoute =
  BookingsChangeRequestsRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BookingsChangeRequestsRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-account-page': typeof ActivateAccountPageRoute
  '/add-hotel': typeof AddHotelRoute
  '/agreement': typeof AgreementRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/cases': typeof CasesRouteWithChildren
  '/change-approved': typeof ChangeApprovedRoute
  '/change-partly-approved': typeof ChangePartlyApprovedRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-rejected': typeof ChangeRejectedRoute
  '/dashboard': typeof DashboardRoute
  '/empty-states': typeof EmptyStatesRoute
  '/finance': typeof FinanceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/hotels': typeof HotelsRoute
  '/information-requests': typeof InformationRequestsRoute
  '/login': typeof LoginRoute
  '/my-hotels': typeof MyHotelsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/profile': typeof ProfileRoute
  '/rate-calendar': typeof RateCalendarRoute
  '/rate-contracts': typeof RateContractsRouteWithChildren
  '/request-changes': typeof RequestChangesRoute
  '/request-submitted': typeof RequestSubmittedRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review-changes': typeof ReviewChangesRoute
  '/secure-account': typeof SecureAccountRoute
  '/sell-status': typeof SellStatusRoute
  '/system-states': typeof SystemStatesRoute
  '/team': typeof TeamRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/bookings/change-requests': typeof BookingsChangeRequestsRouteWithChildren
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/finance/adjustments': typeof FinanceAdjustmentsRoute
  '/finance/bank': typeof FinanceBankRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/payments': typeof FinancePaymentsRouteWithChildren
  '/finance/tax-invoices': typeof FinanceTaxInvoicesRoute
  '/hotel/$hotelId': typeof HotelHotelIdRoute
  '/rate-contracts/$contractId': typeof RateContractsContractIdRouteWithChildren
  '/rate-contracts/new': typeof RateContractsNewRoute
  '/rates/win-list': typeof RatesWinListRoute
  '/team/activity': typeof TeamActivityRoute
  '/bookings/': typeof BookingsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/rate-contracts/': typeof RateContractsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/bookings/change-requests/$requestId': typeof BookingsChangeRequestsRequestIdRouteWithChildren
  '/finance/reports/$report': typeof FinanceReportsReportRoute
  '/finance/statements/$month': typeof FinanceStatementsMonthRoute
  '/rate-contracts/$contractId/edit': typeof RateContractsContractIdEditRoute
  '/rate-contracts/$contractId/queue': typeof RateContractsContractIdQueueRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/bookings/change-requests/': typeof BookingsChangeRequestsIndexRoute
  '/finance/payments/': typeof FinancePaymentsIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/finance/statements/': typeof FinanceStatementsIndexRoute
  '/rate-contracts/$contractId/': typeof RateContractsContractIdIndexRoute
  '/bookings/change-requests/$requestId/': typeof BookingsChangeRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-account-page': typeof ActivateAccountPageRoute
  '/add-hotel': typeof AddHotelRoute
  '/agreement': typeof AgreementRoute
  '/change-approved': typeof ChangeApprovedRoute
  '/change-partly-approved': typeof ChangePartlyApprovedRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-rejected': typeof ChangeRejectedRoute
  '/dashboard': typeof DashboardRoute
  '/empty-states': typeof EmptyStatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/hotels': typeof HotelsRoute
  '/information-requests': typeof InformationRequestsRoute
  '/login': typeof LoginRoute
  '/my-hotels': typeof MyHotelsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/profile': typeof ProfileRoute
  '/rate-calendar': typeof RateCalendarRoute
  '/request-changes': typeof RequestChangesRoute
  '/request-submitted': typeof RequestSubmittedRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review-changes': typeof ReviewChangesRoute
  '/secure-account': typeof SecureAccountRoute
  '/sell-status': typeof SellStatusRoute
  '/system-states': typeof SystemStatesRoute
  '/two-factor': typeof TwoFactorRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/finance/adjustments': typeof FinanceAdjustmentsRoute
  '/finance/bank': typeof FinanceBankRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/tax-invoices': typeof FinanceTaxInvoicesRoute
  '/hotel/$hotelId': typeof HotelHotelIdRoute
  '/rate-contracts/new': typeof RateContractsNewRoute
  '/rates/win-list': typeof RatesWinListRoute
  '/team/activity': typeof TeamActivityRoute
  '/bookings': typeof BookingsIndexRoute
  '/cases': typeof CasesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/rate-contracts': typeof RateContractsIndexRoute
  '/team': typeof TeamIndexRoute
  '/finance/reports/$report': typeof FinanceReportsReportRoute
  '/finance/statements/$month': typeof FinanceStatementsMonthRoute
  '/rate-contracts/$contractId/edit': typeof RateContractsContractIdEditRoute
  '/rate-contracts/$contractId/queue': typeof RateContractsContractIdQueueRoute
  '/bookings/$bookingId': typeof BookingsBookingIdIndexRoute
  '/bookings/change-requests': typeof BookingsChangeRequestsIndexRoute
  '/finance/payments': typeof FinancePaymentsIndexRoute
  '/finance/reports': typeof FinanceReportsIndexRoute
  '/finance/statements': typeof FinanceStatementsIndexRoute
  '/rate-contracts/$contractId': typeof RateContractsContractIdIndexRoute
  '/bookings/change-requests/$requestId': typeof BookingsChangeRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/activate-account-page': typeof ActivateAccountPageRoute
  '/add-hotel': typeof AddHotelRoute
  '/agreement': typeof AgreementRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/cases': typeof CasesRouteWithChildren
  '/change-approved': typeof ChangeApprovedRoute
  '/change-partly-approved': typeof ChangePartlyApprovedRoute
  '/change-password': typeof ChangePasswordRoute
  '/change-rejected': typeof ChangeRejectedRoute
  '/dashboard': typeof DashboardRoute
  '/empty-states': typeof EmptyStatesRoute
  '/finance': typeof FinanceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/hotels': typeof HotelsRoute
  '/information-requests': typeof InformationRequestsRoute
  '/login': typeof LoginRoute
  '/my-hotels': typeof MyHotelsRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/profile': typeof ProfileRoute
  '/rate-calendar': typeof RateCalendarRoute
  '/rate-contracts': typeof RateContractsRouteWithChildren
  '/request-changes': typeof RequestChangesRoute
  '/request-submitted': typeof RequestSubmittedRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review-changes': typeof ReviewChangesRoute
  '/secure-account': typeof SecureAccountRoute
  '/sell-status': typeof SellStatusRoute
  '/system-states': typeof SystemStatesRoute
  '/team': typeof TeamRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRouteWithChildren
  '/bookings/change-requests': typeof BookingsChangeRequestsRouteWithChildren
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/finance/adjustments': typeof FinanceAdjustmentsRoute
  '/finance/bank': typeof FinanceBankRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/payments': typeof FinancePaymentsRouteWithChildren
  '/finance/tax-invoices': typeof FinanceTaxInvoicesRoute
  '/hotel/$hotelId': typeof HotelHotelIdRoute
  '/rate-contracts/$contractId': typeof RateContractsContractIdRouteWithChildren
  '/rate-contracts/new': typeof RateContractsNewRoute
  '/rates/win-list': typeof RatesWinListRoute
  '/team/activity': typeof TeamActivityRoute
  '/bookings/': typeof BookingsIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/rate-contracts/': typeof RateContractsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/bookings/change-requests/$requestId': typeof BookingsChangeRequestsRequestIdRouteWithChildren
  '/finance/reports/$report': typeof FinanceReportsReportRoute
  '/finance/statements/$month': typeof FinanceStatementsMonthRoute
  '/rate-contracts/$contractId/edit': typeof RateContractsContractIdEditRoute
  '/rate-contracts/$contractId/queue': typeof RateContractsContractIdQueueRoute
  '/bookings/$bookingId/': typeof BookingsBookingIdIndexRoute
  '/bookings/change-requests/': typeof BookingsChangeRequestsIndexRoute
  '/finance/payments/': typeof FinancePaymentsIndexRoute
  '/finance/reports/': typeof FinanceReportsIndexRoute
  '/finance/statements/': typeof FinanceStatementsIndexRoute
  '/rate-contracts/$contractId/': typeof RateContractsContractIdIndexRoute
  '/bookings/change-requests/$requestId/': typeof BookingsChangeRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activate-account-page'
    | '/add-hotel'
    | '/agreement'
    | '/bookings'
    | '/cases'
    | '/change-approved'
    | '/change-partly-approved'
    | '/change-password'
    | '/change-rejected'
    | '/dashboard'
    | '/empty-states'
    | '/finance'
    | '/forgot-password'
    | '/getting-started'
    | '/hotels'
    | '/information-requests'
    | '/login'
    | '/my-hotels'
    | '/notification-settings'
    | '/profile'
    | '/rate-calendar'
    | '/rate-contracts'
    | '/request-changes'
    | '/request-submitted'
    | '/requests'
    | '/reset-password'
    | '/review-changes'
    | '/secure-account'
    | '/sell-status'
    | '/system-states'
    | '/team'
    | '/two-factor'
    | '/bookings/$bookingId'
    | '/bookings/change-requests'
    | '/cases/$caseId'
    | '/finance/adjustments'
    | '/finance/bank'
    | '/finance/earnings'
    | '/finance/payments'
    | '/finance/tax-invoices'
    | '/hotel/$hotelId'
    | '/rate-contracts/$contractId'
    | '/rate-contracts/new'
    | '/rates/win-list'
    | '/team/activity'
    | '/bookings/'
    | '/cases/'
    | '/finance/'
    | '/rate-contracts/'
    | '/team/'
    | '/bookings/change-requests/$requestId'
    | '/finance/reports/$report'
    | '/finance/statements/$month'
    | '/rate-contracts/$contractId/edit'
    | '/rate-contracts/$contractId/queue'
    | '/bookings/$bookingId/'
    | '/bookings/change-requests/'
    | '/finance/payments/'
    | '/finance/reports/'
    | '/finance/statements/'
    | '/rate-contracts/$contractId/'
    | '/bookings/change-requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activate-account-page'
    | '/add-hotel'
    | '/agreement'
    | '/change-approved'
    | '/change-partly-approved'
    | '/change-password'
    | '/change-rejected'
    | '/dashboard'
    | '/empty-states'
    | '/forgot-password'
    | '/getting-started'
    | '/hotels'
    | '/information-requests'
    | '/login'
    | '/my-hotels'
    | '/notification-settings'
    | '/profile'
    | '/rate-calendar'
    | '/request-changes'
    | '/request-submitted'
    | '/requests'
    | '/reset-password'
    | '/review-changes'
    | '/secure-account'
    | '/sell-status'
    | '/system-states'
    | '/two-factor'
    | '/cases/$caseId'
    | '/finance/adjustments'
    | '/finance/bank'
    | '/finance/earnings'
    | '/finance/tax-invoices'
    | '/hotel/$hotelId'
    | '/rate-contracts/new'
    | '/rates/win-list'
    | '/team/activity'
    | '/bookings'
    | '/cases'
    | '/finance'
    | '/rate-contracts'
    | '/team'
    | '/finance/reports/$report'
    | '/finance/statements/$month'
    | '/rate-contracts/$contractId/edit'
    | '/rate-contracts/$contractId/queue'
    | '/bookings/$bookingId'
    | '/bookings/change-requests'
    | '/finance/payments'
    | '/finance/reports'
    | '/finance/statements'
    | '/rate-contracts/$contractId'
    | '/bookings/change-requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/activate-account-page'
    | '/add-hotel'
    | '/agreement'
    | '/bookings'
    | '/cases'
    | '/change-approved'
    | '/change-partly-approved'
    | '/change-password'
    | '/change-rejected'
    | '/dashboard'
    | '/empty-states'
    | '/finance'
    | '/forgot-password'
    | '/getting-started'
    | '/hotels'
    | '/information-requests'
    | '/login'
    | '/my-hotels'
    | '/notification-settings'
    | '/profile'
    | '/rate-calendar'
    | '/rate-contracts'
    | '/request-changes'
    | '/request-submitted'
    | '/requests'
    | '/reset-password'
    | '/review-changes'
    | '/secure-account'
    | '/sell-status'
    | '/system-states'
    | '/team'
    | '/two-factor'
    | '/bookings/$bookingId'
    | '/bookings/change-requests'
    | '/cases/$caseId'
    | '/finance/adjustments'
    | '/finance/bank'
    | '/finance/earnings'
    | '/finance/payments'
    | '/finance/tax-invoices'
    | '/hotel/$hotelId'
    | '/rate-contracts/$contractId'
    | '/rate-contracts/new'
    | '/rates/win-list'
    | '/team/activity'
    | '/bookings/'
    | '/cases/'
    | '/finance/'
    | '/rate-contracts/'
    | '/team/'
    | '/bookings/change-requests/$requestId'
    | '/finance/reports/$report'
    | '/finance/statements/$month'
    | '/rate-contracts/$contractId/edit'
    | '/rate-contracts/$contractId/queue'
    | '/bookings/$bookingId/'
    | '/bookings/change-requests/'
    | '/finance/payments/'
    | '/finance/reports/'
    | '/finance/statements/'
    | '/rate-contracts/$contractId/'
    | '/bookings/change-requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  ActivateAccountPageRoute: typeof ActivateAccountPageRoute
  AddHotelRoute: typeof AddHotelRoute
  AgreementRoute: typeof AgreementRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CasesRoute: typeof CasesRouteWithChildren
  ChangeApprovedRoute: typeof ChangeApprovedRoute
  ChangePartlyApprovedRoute: typeof ChangePartlyApprovedRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ChangeRejectedRoute: typeof ChangeRejectedRoute
  DashboardRoute: typeof DashboardRoute
  EmptyStatesRoute: typeof EmptyStatesRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GettingStartedRoute: typeof GettingStartedRoute
  HotelsRoute: typeof HotelsRoute
  InformationRequestsRoute: typeof InformationRequestsRoute
  LoginRoute: typeof LoginRoute
  MyHotelsRoute: typeof MyHotelsRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  ProfileRoute: typeof ProfileRoute
  RateCalendarRoute: typeof RateCalendarRoute
  RateContractsRoute: typeof RateContractsRouteWithChildren
  RequestChangesRoute: typeof RequestChangesRoute
  RequestSubmittedRoute: typeof RequestSubmittedRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewChangesRoute: typeof ReviewChangesRoute
  SecureAccountRoute: typeof SecureAccountRoute
  SellStatusRoute: typeof SellStatusRoute
  SystemStatesRoute: typeof SystemStatesRoute
  TeamRoute: typeof TeamRouteWithChildren
  TwoFactorRoute: typeof TwoFactorRoute
  HotelHotelIdRoute: typeof HotelHotelIdRoute
  RatesWinListRoute: typeof RatesWinListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate-account-page': {
      id: '/activate-account-page'
      path: '/activate-account-page'
      fullPath: '/activate-account-page'
      preLoaderRoute: typeof ActivateAccountPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-hotel': {
      id: '/add-hotel'
      path: '/add-hotel'
      fullPath: '/add-hotel'
      preLoaderRoute: typeof AddHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-approved': {
      id: '/change-approved'
      path: '/change-approved'
      fullPath: '/change-approved'
      preLoaderRoute: typeof ChangeApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-partly-approved': {
      id: '/change-partly-approved'
      path: '/change-partly-approved'
      fullPath: '/change-partly-approved'
      preLoaderRoute: typeof ChangePartlyApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-rejected': {
      id: '/change-rejected'
      path: '/change-rejected'
      fullPath: '/change-rejected'
      preLoaderRoute: typeof ChangeRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empty-states': {
      id: '/empty-states'
      path: '/empty-states'
      fullPath: '/empty-states'
      preLoaderRoute: typeof EmptyStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information-requests': {
      id: '/information-requests'
      path: '/information-requests'
      fullPath: '/information-requests'
      preLoaderRoute: typeof InformationRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-hotels': {
      id: '/my-hotels'
      path: '/my-hotels'
      fullPath: '/my-hotels'
      preLoaderRoute: typeof MyHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-calendar': {
      id: '/rate-calendar'
      path: '/rate-calendar'
      fullPath: '/rate-calendar'
      preLoaderRoute: typeof RateCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-contracts': {
      id: '/rate-contracts'
      path: '/rate-contracts'
      fullPath: '/rate-contracts'
      preLoaderRoute: typeof RateContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-changes': {
      id: '/request-changes'
      path: '/request-changes'
      fullPath: '/request-changes'
      preLoaderRoute: typeof RequestChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-submitted': {
      id: '/request-submitted'
      path: '/request-submitted'
      fullPath: '/request-submitted'
      preLoaderRoute: typeof RequestSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-changes': {
      id: '/review-changes'
      path: '/review-changes'
      fullPath: '/review-changes'
      preLoaderRoute: typeof ReviewChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-account': {
      id: '/secure-account'
      path: '/secure-account'
      fullPath: '/secure-account'
      preLoaderRoute: typeof SecureAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-status': {
      id: '/sell-status'
      path: '/sell-status'
      fullPath: '/sell-status'
      preLoaderRoute: typeof SellStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-states': {
      id: '/system-states'
      path: '/system-states'
      fullPath: '/system-states'
      preLoaderRoute: typeof SystemStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/bookings/change-requests': {
      id: '/bookings/change-requests'
      path: '/change-requests'
      fullPath: '/bookings/change-requests'
      preLoaderRoute: typeof BookingsChangeRequestsRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof CasesRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/adjustments': {
      id: '/finance/adjustments'
      path: '/adjustments'
      fullPath: '/finance/adjustments'
      preLoaderRoute: typeof FinanceAdjustmentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/bank': {
      id: '/finance/bank'
      path: '/bank'
      fullPath: '/finance/bank'
      preLoaderRoute: typeof FinanceBankRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/earnings': {
      id: '/finance/earnings'
      path: '/earnings'
      fullPath: '/finance/earnings'
      preLoaderRoute: typeof FinanceEarningsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/tax-invoices': {
      id: '/finance/tax-invoices'
      path: '/tax-invoices'
      fullPath: '/finance/tax-invoices'
      preLoaderRoute: typeof FinanceTaxInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/hotel/$hotelId': {
      id: '/hotel/$hotelId'
      path: '/hotel/$hotelId'
      fullPath: '/hotel/$hotelId'
      preLoaderRoute: typeof HotelHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-contracts/': {
      id: '/rate-contracts/'
      path: '/'
      fullPath: '/rate-contracts/'
      preLoaderRoute: typeof RateContractsIndexRouteImport
      parentRoute: typeof RateContractsRoute
    }
    '/rate-contracts/$contractId': {
      id: '/rate-contracts/$contractId'
      path: '/$contractId'
      fullPath: '/rate-contracts/$contractId'
      preLoaderRoute: typeof RateContractsContractIdRouteImport
      parentRoute: typeof RateContractsRoute
    }
    '/rate-contracts/new': {
      id: '/rate-contracts/new'
      path: '/new'
      fullPath: '/rate-contracts/new'
      preLoaderRoute: typeof RateContractsNewRouteImport
      parentRoute: typeof RateContractsRoute
    }
    '/rates/win-list': {
      id: '/rates/win-list'
      path: '/rates/win-list'
      fullPath: '/rates/win-list'
      preLoaderRoute: typeof RatesWinListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/activity': {
      id: '/team/activity'
      path: '/activity'
      fullPath: '/team/activity'
      preLoaderRoute: typeof TeamActivityRouteImport
      parentRoute: typeof TeamRoute
    }
    '/bookings/$bookingId/': {
      id: '/bookings/$bookingId/'
      path: '/'
      fullPath: '/bookings/$bookingId/'
      preLoaderRoute: typeof BookingsBookingIdIndexRouteImport
      parentRoute: typeof BookingsBookingIdRoute
    }
    '/bookings/change-requests/': {
      id: '/bookings/change-requests/'
      path: '/'
      fullPath: '/bookings/change-requests/'
      preLoaderRoute: typeof BookingsChangeRequestsIndexRouteImport
      parentRoute: typeof BookingsChangeRequestsRoute
    }
    '/bookings/change-requests/$requestId': {
      id: '/bookings/change-requests/$requestId'
      path: '/$requestId'
      fullPath: '/bookings/change-requests/$requestId'
      preLoaderRoute: typeof BookingsChangeRequestsRequestIdRouteImport
      parentRoute: typeof BookingsChangeRequestsRoute
    }
    '/finance/payments/': {
      id: '/finance/payments/'
      path: '/'
      fullPath: '/finance/payments/'
      preLoaderRoute: typeof FinancePaymentsIndexRouteImport
      parentRoute: typeof FinancePaymentsRoute
    }
    '/finance/reports/': {
      id: '/finance/reports/'
      path: '/reports'
      fullPath: '/finance/reports/'
      preLoaderRoute: typeof FinanceReportsIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports/$report': {
      id: '/finance/reports/$report'
      path: '/reports/$report'
      fullPath: '/finance/reports/$report'
      preLoaderRoute: typeof FinanceReportsReportRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/statements/': {
      id: '/finance/statements/'
      path: '/statements'
      fullPath: '/finance/statements/'
      preLoaderRoute: typeof FinanceStatementsIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/statements/$month': {
      id: '/finance/statements/$month'
      path: '/statements/$month'
      fullPath: '/finance/statements/$month'
      preLoaderRoute: typeof FinanceStatementsMonthRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/rate-contracts/$contractId/': {
      id: '/rate-contracts/$contractId/'
      path: '/'
      fullPath: '/rate-contracts/$contractId/'
      preLoaderRoute: typeof RateContractsContractIdIndexRouteImport
      parentRoute: typeof RateContractsContractIdRoute
    }
    '/rate-contracts/$contractId/edit': {
      id: '/rate-contracts/$contractId/edit'
      path: '/edit'
      fullPath: '/rate-contracts/$contractId/edit'
      preLoaderRoute: typeof RateContractsContractIdEditRouteImport
      parentRoute: typeof RateContractsContractIdRoute
    }
    '/rate-contracts/$contractId/queue': {
      id: '/rate-contracts/$contractId/queue'
      path: '/queue'
      fullPath: '/rate-contracts/$contractId/queue'
      preLoaderRoute: typeof RateContractsContractIdQueueRouteImport
      parentRoute: typeof RateContractsContractIdRoute
    }
    '/bookings/change-requests/$requestId/': {
      id: '/bookings/change-requests/$requestId/'
      path: '/'
      fullPath: '/bookings/change-requests/$requestId/'
      preLoaderRoute: typeof BookingsChangeRequestsRequestIdIndexRouteImport
      parentRoute: typeof BookingsChangeRequestsRequestIdRoute
    }
  }
}

interface BookingsBookingIdRouteChildren {
  BookingsBookingIdIndexRoute: typeof BookingsBookingIdIndexRoute
}

const BookingsBookingIdRouteChildren: BookingsBookingIdRouteChildren = {
  BookingsBookingIdIndexRoute: BookingsBookingIdIndexRoute,
}

const BookingsBookingIdRouteWithChildren =
  BookingsBookingIdRoute._addFileChildren(BookingsBookingIdRouteChildren)

interface BookingsChangeRequestsRequestIdRouteChildren {
  BookingsChangeRequestsRequestIdIndexRoute: typeof BookingsChangeRequestsRequestIdIndexRoute
}

const BookingsChangeRequestsRequestIdRouteChildren: BookingsChangeRequestsRequestIdRouteChildren =
  {
    BookingsChangeRequestsRequestIdIndexRoute:
      BookingsChangeRequestsRequestIdIndexRoute,
  }

const BookingsChangeRequestsRequestIdRouteWithChildren =
  BookingsChangeRequestsRequestIdRoute._addFileChildren(
    BookingsChangeRequestsRequestIdRouteChildren,
  )

interface BookingsChangeRequestsRouteChildren {
  BookingsChangeRequestsRequestIdRoute: typeof BookingsChangeRequestsRequestIdRouteWithChildren
  BookingsChangeRequestsIndexRoute: typeof BookingsChangeRequestsIndexRoute
}

const BookingsChangeRequestsRouteChildren: BookingsChangeRequestsRouteChildren =
  {
    BookingsChangeRequestsRequestIdRoute:
      BookingsChangeRequestsRequestIdRouteWithChildren,
    BookingsChangeRequestsIndexRoute: BookingsChangeRequestsIndexRoute,
  }

const BookingsChangeRequestsRouteWithChildren =
  BookingsChangeRequestsRoute._addFileChildren(
    BookingsChangeRequestsRouteChildren,
  )

interface BookingsRouteChildren {
  BookingsBookingIdRoute: typeof BookingsBookingIdRouteWithChildren
  BookingsChangeRequestsRoute: typeof BookingsChangeRequestsRouteWithChildren
  BookingsIndexRoute: typeof BookingsIndexRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsBookingIdRoute: BookingsBookingIdRouteWithChildren,
  BookingsChangeRequestsRoute: BookingsChangeRequestsRouteWithChildren,
  BookingsIndexRoute: BookingsIndexRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface FinancePaymentsRouteChildren {
  FinancePaymentsIndexRoute: typeof FinancePaymentsIndexRoute
}

const FinancePaymentsRouteChildren: FinancePaymentsRouteChildren = {
  FinancePaymentsIndexRoute: FinancePaymentsIndexRoute,
}

const FinancePaymentsRouteWithChildren = FinancePaymentsRoute._addFileChildren(
  FinancePaymentsRouteChildren,
)

interface FinanceRouteChildren {
  FinanceAdjustmentsRoute: typeof FinanceAdjustmentsRoute
  FinanceBankRoute: typeof FinanceBankRoute
  FinanceEarningsRoute: typeof FinanceEarningsRoute
  FinancePaymentsRoute: typeof FinancePaymentsRouteWithChildren
  FinanceTaxInvoicesRoute: typeof FinanceTaxInvoicesRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  FinanceReportsReportRoute: typeof FinanceReportsReportRoute
  FinanceStatementsMonthRoute: typeof FinanceStatementsMonthRoute
  FinanceReportsIndexRoute: typeof FinanceReportsIndexRoute
  FinanceStatementsIndexRoute: typeof FinanceStatementsIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAdjustmentsRoute: FinanceAdjustmentsRoute,
  FinanceBankRoute: FinanceBankRoute,
  FinanceEarningsRoute: FinanceEarningsRoute,
  FinancePaymentsRoute: FinancePaymentsRouteWithChildren,
  FinanceTaxInvoicesRoute: FinanceTaxInvoicesRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  FinanceReportsReportRoute: FinanceReportsReportRoute,
  FinanceStatementsMonthRoute: FinanceStatementsMonthRoute,
  FinanceReportsIndexRoute: FinanceReportsIndexRoute,
  FinanceStatementsIndexRoute: FinanceStatementsIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface RateContractsContractIdRouteChildren {
  RateContractsContractIdEditRoute: typeof RateContractsContractIdEditRoute
  RateContractsContractIdQueueRoute: typeof RateContractsContractIdQueueRoute
  RateContractsContractIdIndexRoute: typeof RateContractsContractIdIndexRoute
}

const RateContractsContractIdRouteChildren: RateContractsContractIdRouteChildren =
  {
    RateContractsContractIdEditRoute: RateContractsContractIdEditRoute,
    RateContractsContractIdQueueRoute: RateContractsContractIdQueueRoute,
    RateContractsContractIdIndexRoute: RateContractsContractIdIndexRoute,
  }

const RateContractsContractIdRouteWithChildren =
  RateContractsContractIdRoute._addFileChildren(
    RateContractsContractIdRouteChildren,
  )

interface RateContractsRouteChildren {
  RateContractsContractIdRoute: typeof RateContractsContractIdRouteWithChildren
  RateContractsNewRoute: typeof RateContractsNewRoute
  RateContractsIndexRoute: typeof RateContractsIndexRoute
}

const RateContractsRouteChildren: RateContractsRouteChildren = {
  RateContractsContractIdRoute: RateContractsContractIdRouteWithChildren,
  RateContractsNewRoute: RateContractsNewRoute,
  RateContractsIndexRoute: RateContractsIndexRoute,
}

const RateContractsRouteWithChildren = RateContractsRoute._addFileChildren(
  RateContractsRouteChildren,
)

interface TeamRouteChildren {
  TeamActivityRoute: typeof TeamActivityRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamActivityRoute: TeamActivityRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  ActivateAccountPageRoute: ActivateAccountPageRoute,
  AddHotelRoute: AddHotelRoute,
  AgreementRoute: AgreementRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CasesRoute: CasesRouteWithChildren,
  ChangeApprovedRoute: ChangeApprovedRoute,
  ChangePartlyApprovedRoute: ChangePartlyApprovedRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ChangeRejectedRoute: ChangeRejectedRoute,
  DashboardRoute: DashboardRoute,
  EmptyStatesRoute: EmptyStatesRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GettingStartedRoute: GettingStartedRoute,
  HotelsRoute: HotelsRoute,
  InformationRequestsRoute: InformationRequestsRoute,
  LoginRoute: LoginRoute,
  MyHotelsRoute: MyHotelsRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  ProfileRoute: ProfileRoute,
  RateCalendarRoute: RateCalendarRoute,
  RateContractsRoute: RateContractsRouteWithChildren,
  RequestChangesRoute: RequestChangesRoute,
  RequestSubmittedRoute: RequestSubmittedRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewChangesRoute: ReviewChangesRoute,
  SecureAccountRoute: SecureAccountRoute,
  SellStatusRoute: SellStatusRoute,
  SystemStatesRoute: SystemStatesRoute,
  TeamRoute: TeamRouteWithChildren,
  TwoFactorRoute: TwoFactorRoute,
  HotelHotelIdRoute: HotelHotelIdRoute,
  RatesWinListRoute: RatesWinListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
